from .core import Score, BuildResult, BuildCache, GACheckpoint, save_checkpoint, load_checkpoint, compute_args_hash
from .scoring import _normalize_reloc_x86_32, score_candidate, diff_functions
from .parsers import parse_coff_obj_symbol_bytes, parse_coff_symbol_bytes, list_coff_obj_symbols, extract_function_from_pe, extract_function_from_lib
from .compiler import build_candidate, build_candidate_obj_only, flag_sweep, generate_flag_combinations, MSVC6_FLAG_AXES
from .mutator import _split_preamble_body, _quick_validate, crossover, compute_population_diversity, mutate_code
from .mutator import (
    mut_commute_simple_add,
    mut_commute_simple_mul,
    mut_flip_eq_zero,
    mut_flip_lt_ge,
    mut_add_redundant_parens,
    mut_reassociate_add,
    mut_insert_noop_block,
    mut_toggle_bool_not,
    mut_swap_eq_operands,
    mut_swap_ne_operands,
    mut_swap_or_operands,
    mut_swap_and_operands,
    mut_return_to_goto,
    mut_goto_to_return,
    mut_introduce_local_alias,
    mut_reorder_declarations,
    mut_swap_if_else,
    mut_reorder_elseif,
    mut_add_cast,
    mut_remove_cast,
    mut_toggle_volatile,
    mut_add_register_keyword,
    mut_remove_register_keyword,
    mut_if_false_to_bitand,
    mut_bitand_to_if_false,
    mut_introduce_temp_for_call,
    mut_remove_temp_var,
    mut_toggle_signedness,
    mut_swap_adjacent_declarations,
    mut_split_declaration_init,
    mut_merge_declaration_init,
    mut_while_to_dowhile,
    mut_dowhile_to_while,
    mut_early_return_to_accum,
    mut_accum_to_early_return,
    mut_pointer_to_int_param,
    mut_int_to_pointer_param,
    mut_duplicate_loop_body,
    mut_fold_constant_add,
    mut_unfold_constant_add,
    mut_change_array_index_order,
    mut_struct_vs_ptr_access,
    mut_split_cmp_chain,
    mut_merge_cmp_chain,
    mut_combine_ptr_arith,
    mut_split_ptr_arith,
    mut_change_return_type,
    mut_change_param_order,
)
