"""Tests for rebrew sync --pull-data (Ghidra data label fetching)."""

import re
import sys
from types import SimpleNamespace
from typing import Any

from rebrew.ghidra.commands import pull_data


class _FakeClient:
    def __init__(self, timeout: float) -> None:
        self.timeout = timeout

    def __enter__(self) -> "_FakeClient":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        return None

    def post(self, *args: Any, **kwargs: Any) -> Any:
        return SimpleNamespace(headers={"Mcp-Session-Id": "sess123"})

    def delete(self, *args: Any, **kwargs: Any) -> Any:
        # Session teardown (end_mcp_session) runs on every exit path; the
        # fake client answers it so no real httpx is ever needed.
        return SimpleNamespace()


def _mock_httpx(monkeypatch: Any) -> None:
    fake_httpx = SimpleNamespace(
        Client=lambda timeout: _FakeClient(timeout),
        RequestError=RuntimeError,
        HTTPError=RuntimeError,
    )
    monkeypatch.setitem(sys.modules, "httpx", fake_httpx)


def _runpull_data(
    monkeypatch: Any,
    tmp_path: Any,
    symbols: list[dict[str, Any]],
    data_by_addr: dict[str, dict[str, Any]],
    *,
    dry_run: bool = False,
    sections: list[dict[str, Any]] | None = None,
) -> None:
    _mock_httpx(monkeypatch)

    def _fake_init(client: Any, endpoint: str) -> str:
        _ = client, endpoint
        return "session-1"

    def _fake_fetch_raw(
        client: Any,
        endpoint: str,
        tool_name: str,
        arguments: dict[str, Any],
        request_id: int,
        session_id: str = "",
    ) -> Any:
        _ = client, endpoint, request_id, session_id
        if tool_name == "get-symbols-count":
            return {"count": len(symbols)}
        if tool_name == "get-symbols":
            start = int(arguments["startIndex"])
            max_count = int(arguments["maxCount"])
            return symbols[start : start + max_count]
        if tool_name == "get-data":
            return data_by_addr.get(str(arguments["addressOrSymbol"]))
        raise AssertionError(f"unexpected tool call: {tool_name}")

    monkeypatch.setattr("rebrew.ghidra.commands.init_mcp_session", _fake_init)
    monkeypatch.setattr("rebrew.ghidra.commands.fetch_mcp_tool_raw", _fake_fetch_raw)

    if sections is not None:
        sec_objs = {
            sec["name"]: SimpleNamespace(
                name=sec["name"],
                va=sec["va"],
                size=sec["size"],
                raw_size=sec.get("raw_size", sec["size"]),
            )
            for sec in sections
        }

        def _fake_load_binary(path: Any, fmt: str = "auto") -> Any:
            _ = path, fmt
            return SimpleNamespace(sections=sec_objs)

        monkeypatch.setitem(
            sys.modules,
            "rebrew.binary_loader",
            SimpleNamespace(load_binary=_fake_load_binary),
        )

    cfg = SimpleNamespace(
        reversed_dir=tmp_path,
        target_binary=tmp_path / "target.exe",
        format="pe",
    )
    pull_data(cfg, "http://localhost:8080/mcp/message", "/target.exe", dry_run)


class TestPullDataGlobalsHeader:
    def test_generates_header_file(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [
            {"name": "g_playerCount", "address": "0x00403010", "isFunction": False},
            {"name": "g_windowTitle", "address": "0x00403014", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_playerCount",
            },
            "0x00403014": {
                "address": "0x00403014",
                "dataType": "pointer",
                "length": 4,
                "symbolName": "g_windowTitle",
            },
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)

        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "Auto-generated by rebrew sync pull-data" in header
        assert "extern int g_playerCount;" in header
        assert "extern void* g_windowTitle;" in header

    def test_non_ascii_symbols_do_not_collide(self, tmp_path: Any, monkeypatch: Any) -> None:
        """Two symbols that sanitize to one C identifier get distinct names.

        Every non-ASCII code point becomes ``_``, so ``α_table`` and ``β_table``
        both reduce to ``_table``; the header declares each name once, so the
        second would be a redefinition the project cannot compile.
        """
        symbols = [
            {"name": "α_table", "address": "0x00403010", "isFunction": False},
            {"name": "β_table", "address": "0x00403014", "isFunction": False},
            {"name": "γ", "address": "0x00403018", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "α_table",
            },
            "0x00403014": {
                "address": "0x00403014",
                "dataType": "int",
                "length": 4,
                "symbolName": "β_table",
            },
            "0x00403018": {
                "address": "0x00403018",
                "dataType": "int",
                "length": 4,
                "symbolName": "γ",
            },
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)

        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        declared = re.findall(r"^extern \w+ \*?(\w+);", header, re.MULTILINE)
        assert len(declared) == len(set(declared)) == 3

    def test_regeneration_is_idempotent(self, tmp_path: Any, monkeypatch: Any) -> None:
        """Re-running --pull-data must not rewrite when only Generated: would change."""
        symbols = [
            {"name": "g_playerCount", "address": "0x00403010", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_playerCount",
            },
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        out = tmp_path / "rebrew_globals.h"
        first = out.read_text(encoding="utf-8")
        assert "Generated:" in first
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        assert out.read_text(encoding="utf-8") == first

    def test_type_mapping_int(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [{"name": "g_value", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_value",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern int g_value;" in header

    def test_type_mapping_pointer(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [{"name": "g_ptr", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "pointer32",
                "length": 4,
                "symbolName": "g_ptr",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern void* g_ptr;" in header

    def test_type_mapping_undefined(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [{"name": "g_blob", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "undefined4",
                "length": 4,
                "symbolName": "g_blob",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern unsigned char g_blob[4];" in header

    def test_type_mapping_undefined_array(self, tmp_path: Any, monkeypatch: Any) -> None:
        # Ghidra arrays of undefined bytes must map to unsigned char like the
        # scalar case, not leak `extern undefined g_blob[16];`.
        symbols = [{"name": "g_blob", "address": "0x00405000", "isFunction": False}]
        data_by_addr = {
            "0x00405000": {
                "address": "0x00405000",
                "dataType": "undefined[16]",
                "length": 16,
                "symbolName": "g_blob",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern unsigned char g_blob[16];" in header
        assert "extern undefined" not in header

    def test_type_mapping_array(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [{"name": "g_name", "address": "0x00405000", "isFunction": False}]
        data_by_addr = {
            "0x00405000": {
                "address": "0x00405000",
                "dataType": "char[32]",
                "length": 32,
                "symbolName": "g_name",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern char g_name[32];" in header

    def test_type_mapping_float(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [
            {"name": "g_f", "address": "0x00403010", "isFunction": False},
            {"name": "g_d", "address": "0x00403018", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "float",
                "length": 4,
                "symbolName": "g_f",
            },
            "0x00403018": {
                "address": "0x00403018",
                "dataType": "double",
                "length": 8,
                "symbolName": "g_d",
            },
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern float g_f;" in header
        assert "extern double g_d;" in header

    def test_filters_function_symbols(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [
            {"name": "real_fn", "address": "0x00401000", "isFunction": True},
            {"name": "g_ok", "address": "0x00403010", "isFunction": False},
        ]
        requests: list[str] = []

        def _fake_init(client: Any, endpoint: str) -> str:
            _ = client, endpoint
            return "session-1"

        def _fake_fetch_raw(
            client: Any,
            endpoint: str,
            tool_name: str,
            arguments: dict[str, Any],
            request_id: int,
            session_id: str = "",
        ) -> Any:
            _ = client, endpoint, request_id, session_id
            if tool_name == "get-symbols-count":
                return {"count": len(symbols)}
            if tool_name == "get-symbols":
                start = int(arguments["startIndex"])
                max_count = int(arguments["maxCount"])
                return symbols[start : start + max_count]
            if tool_name == "get-data":
                addr = str(arguments["addressOrSymbol"])
                requests.append(addr)
                return {
                    "address": addr,
                    "dataType": "int",
                    "length": 4,
                    "symbolName": "g_ok",
                }
            raise AssertionError(f"unexpected tool call: {tool_name}")

        _mock_httpx(monkeypatch)
        monkeypatch.setattr("rebrew.ghidra.commands.init_mcp_session", _fake_init)
        monkeypatch.setattr("rebrew.ghidra.commands.fetch_mcp_tool_raw", _fake_fetch_raw)
        cfg = SimpleNamespace(
            reversed_dir=tmp_path,
            target_binary=tmp_path / "target.exe",
            format="pe",
        )

        pull_data(cfg, "http://localhost:8080/mcp/message", "/target.exe", False)

        assert requests == ["0x00403010"]

    def test_dry_run_no_write(self, tmp_path: Any, monkeypatch: Any, capsys: Any) -> None:
        symbols = [{"name": "g_value", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_value",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr, dry_run=True)

        assert not (tmp_path / "rebrew_globals.h").exists()
        out = capsys.readouterr().err
        assert "Dry run: would write" in out

    def test_empty_symbols_no_file(self, tmp_path: Any, monkeypatch: Any) -> None:
        _runpull_data(monkeypatch, tmp_path, [], {}, dry_run=False)
        assert not (tmp_path / "rebrew_globals.h").exists()

    def test_header_has_include_guard(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [{"name": "g_value", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_value",
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "#ifndef REBREW_GLOBALS_H" in header
        assert "#define REBREW_GLOBALS_H" in header
        assert "#endif /* REBREW_GLOBALS_H */" in header

    def test_hostile_section_name_cannot_break_out(self, tmp_path: Any, monkeypatch: Any) -> None:
        """A PE section name is attacker-controlled, so ``*/`` in one must not
        close the section comment and inject C into a header the next
        ``rebrew test`` compiles."""
        symbols = [{"name": "g_data", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_data",
            },
        }
        sections = [
            {"name": '.weird*/ system("pwned"); /*', "va": 0x00403000, "size": 0x1000},
        ]

        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr, sections=sections)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "*/ system(" not in header
        assert ".weird* / system(" in header

    def test_hostile_data_type_cannot_inject_c(self, tmp_path: Any, monkeypatch: Any) -> None:
        """A Ghidra ``dataType`` comes from the analysed program, so a name
        carrying a ``;`` must not reach the compiled header as a second
        declaration."""
        symbols = [{"name": "g_evil", "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": 'int; system("pwned")',
                "length": 4,
                "symbolName": "g_evil",
            },
        }

        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern unsigned char g_evil;" in header
        assert "extern int; system(" not in header

    def test_hostile_array_bound_cannot_inject_c(self, tmp_path: Any, monkeypatch: Any) -> None:
        """The array bound is spliced into the declarator the same way."""
        symbols = [{"name": "g_evil", "address": "0x00405000", "isFunction": False}]
        data_by_addr = {
            "0x00405000": {
                "address": "0x00405000",
                "dataType": 'char[4]; system("pwned")]',
                "length": 4,
                "symbolName": "g_evil",
            },
        }

        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern unsigned char g_evil[];" in header
        assert "char[4]; system(" not in header

    def test_qualified_pointer_type_is_kept(self, tmp_path: Any, monkeypatch: Any) -> None:
        """The grammar accepts real declarators, not just bare words."""
        symbols = [{"name": "g_msg", "address": "0x00405000", "isFunction": False}]
        data_by_addr = {
            "0x00405000": {
                "address": "0x00405000",
                "dataType": "char * const",
                "length": 4,
                "symbolName": "g_msg",
            },
        }

        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "extern char * const g_msg;" in header

    def test_section_grouping(self, tmp_path: Any, monkeypatch: Any) -> None:
        symbols = [
            {"name": "g_data", "address": "0x00403010", "isFunction": False},
            {"name": "g_const", "address": "0x00405010", "isFunction": False},
            {"name": "g_bss", "address": "0x00406010", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_data",
            },
            "0x00405010": {
                "address": "0x00405010",
                "dataType": "char[16]",
                "length": 16,
                "symbolName": "g_const",
            },
            "0x00406010": {
                "address": "0x00406010",
                "dataType": "int",
                "length": 4,
                "symbolName": "g_bss",
            },
        }
        sections = [
            {"name": ".data", "va": 0x00403000, "size": 0x1000},
            {"name": ".rdata", "va": 0x00405000, "size": 0x1000},
            {"name": ".bss", "va": 0x00406000, "size": 0x1000},
        ]

        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr, sections=sections)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "/* .data section globals */" in header
        assert "/* .rdata section globals */" in header
        assert "/* .bss section globals */" in header

    def test_unicode_normalization_nfc_nfd_symbol_name(
        self, tmp_path: Any, monkeypatch: Any
    ) -> None:
        # NFD symbol name: e + combining acute
        nfd_name = "g_item_\u0065\u0301"
        symbols = [{"name": nfd_name, "address": "0x00403010", "isFunction": False}]
        data_by_addr = {
            "0x00403010": {
                "address": "0x00403010",
                "dataType": "int",
                "length": 4,
                "symbolName": nfd_name,
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        # Under NFC normalization, é (\u00e9) becomes _ under [^A-Za-z0-9_] -> g_item__
        # Without normalization, NFD leaves 'e' and replaces \u0301 with _ -> g_item_e_
        assert "g_item__" in header


class TestPullDataCountsDroppedSymbols:
    def test_malformed_get_data_reply_is_counted_not_silently_dropped(
        self, tmp_path: Any, monkeypatch: Any, capsys: Any
    ) -> None:
        """A symbol asked for and not written is a loss, and must be counted.

        The ``get-data`` reply for the second symbol is missing, which is the
        shape a dropped symbol takes.  Counting it as a failure is what puts it
        in the closing tally; counted silently the run reported every label it
        wrote and the generated header quietly omitted a global.
        """
        symbols = [
            {"name": "g_playerCount", "address": "0x00403010", "isFunction": False},
            {"name": "g_windowTitle", "address": "0x00403014", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {"address": "0x00403010", "symbolName": "g_playerCount", "length": 4},
            # "0x00403014" absent: the reply is not a symbol dict.
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)

        out = capsys.readouterr().err
        assert "holds 1 of 2 data labels" in out, out
        # The header is what the compiler reads, so the loss is in the file too.
        header = (tmp_path / "rebrew_globals.h").read_text(encoding="utf-8")
        assert "g_windowTitle" not in header

    def test_unparseable_address_is_counted(
        self, tmp_path: Any, monkeypatch: Any, capsys: Any
    ) -> None:
        """A reply whose address will not parse is the same loss, and is named."""
        symbols = [
            {"name": "g_playerCount", "address": "0x00403010", "isFunction": False},
        ]
        data_by_addr = {
            "0x00403010": {
                "address": "0xZZZZ",
                "symbolName": "g_playerCount",
                "length": 4,
            }
        }
        _runpull_data(monkeypatch, tmp_path, symbols, data_by_addr)

        out = capsys.readouterr().err
        assert "unparseable address" in out, out
        assert "all 1 symbol(s) failed to pull" in out, out
