"""Tests for the byte-identity link tools: order-sources, calibrate-bss,
gen-link-stubs, verify-placement, and gen-layout --data-gap."""

from __future__ import annotations

import struct
from pathlib import Path

import pytest
from typer.testing import Result

from rebrew.calibrate_bss import find_link_cmd, read_data_vs
from rebrew.gen_layout import gen_data_restore
from rebrew.gen_link_stubs import gen_link_stubs, load_data_symbols, read_calibrated_tail
from rebrew.link_order import file_va, order_sources

# ---------------------------------------------------------------------------
# order-sources
# ---------------------------------------------------------------------------


def _mk_src(tmp_path: Path, name: str, va: int | None) -> Path:
    p = tmp_path / name
    content = "int x;\n"
    if va is not None:
        content += f"// FUNCTION: server.dll 0x{va:x}\nvoid f(void) {{}}\n"
    p.write_text(content)
    return p


def test_file_va(tmp_path: Path) -> None:
    assert file_va(_mk_src(tmp_path, "a.c", 0x10002000)) == 0x10002000
    assert file_va(_mk_src(tmp_path, "b.c", None)) is None


def test_order_sources(tmp_path: Path) -> None:
    a = _mk_src(tmp_path, "a.c", 0x10003000)
    b = _mk_src(tmp_path, "b.c", 0x10001000)
    c = _mk_src(tmp_path, "c.c", None)
    ordered, excluded = order_sources([a, c, b], {}, set())
    assert ordered == [b, a, c]


def test_order_sources_first_va_and_exclude(tmp_path: Path) -> None:
    z = _mk_src(tmp_path, "zlib.c", None)
    g = _mk_src(tmp_path, "game.c", 0x10001000)
    dead = _mk_src(tmp_path, "uncompr.c", None)
    ordered, excluded = order_sources([z, g, dead], {"zlib.c": 0x10000000}, {"uncompr.c"})
    assert ordered == [z, g]
    assert excluded == ["uncompr.c"]


def test_order_sources_first_va_matches_prefixed_key(tmp_path: Path) -> None:
    """A --first-va key carrying a directory (zlib/adler32.c) matches the
    file's basename, so library tables resolve instead of sorting last."""
    sub = tmp_path / "src" / "zlib"
    sub.mkdir(parents=True)
    adler = _mk_src(sub, "adler32.c", None)
    game = _mk_src(tmp_path, "game.c", 0x10002000)
    ordered, _ = order_sources([game, adler], {"zlib/adler32.c": 0x10001000}, set())
    assert ordered == [adler, game]


def test_order_sources_exclude_matches_basename(tmp_path: Path) -> None:
    dead = _mk_src(tmp_path, "dead.c", 0x10001000)
    ordered, excluded = order_sources([dead], {}, {"src/dead.c"})
    assert ordered == []
    assert excluded == ["dead.c"]


# ---------------------------------------------------------------------------
# gen-link-stubs
# ---------------------------------------------------------------------------


def test_load_data_symbols(tmp_path: Path) -> None:
    meta = tmp_path / "rebrew-data.toml"
    meta.write_text(
        '["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\ntype = "int"\n'
        '["SERVER.0x10027004"]\nname = "g_b"\nsection = ".bss"\n'
        '["SERVER.0x10027010"]\nname = "g_c"\nsection = ".data"\n',
        encoding="utf-8",
    )
    syms = load_data_symbols(meta)
    assert [(a, n) for a, n, _ in syms] == [
        (0x10027000, "g_a"),
        (0x10027010, "g_c"),
    ]


def test_gen_link_stubs(tmp_path: Path) -> None:
    meta = tmp_path / "rebrew-data.toml"
    meta.write_text('["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\n', encoding="utf-8")
    text = gen_link_stubs(meta)
    assert "char g_a[1] = {0};" in text
    assert "g_bss_tail[0x400000]" in text
    assert "AUTO-GENERATED by rebrew build link-stubs" in text


def test_gen_link_stubs_json_still_writes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``--json`` changes encoding only — the output TU must still be written."""
    import json

    from typer.testing import CliRunner

    from rebrew.gen_link_stubs import app

    monkeypatch.chdir(tmp_path)
    meta = tmp_path / "src" / "rebrew-data.toml"
    meta.parent.mkdir(parents=True)
    meta.write_text('["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\n', encoding="utf-8")
    out = tmp_path / "src" / "link_stubs.c"
    result = CliRunner().invoke(app, ["--data-metadata", str(meta), "--output", str(out), "--json"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert payload["written"] is True
    assert out.is_file()
    assert "char g_a[1] = {0};" in out.read_text(encoding="utf-8")


def test_gen_link_stubs_keeps_calibrated_tail(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Re-running after calibrate-bss must not reset the pad it measured.

    calibrate-bss tunes ``g_bss_tail`` in the generated TU and leaves it
    there; a regeneration that hard-codes the placeholder silently reverts a
    byte-match the user had already converged.
    """
    import json

    from typer.testing import CliRunner

    from rebrew.gen_link_stubs import app

    monkeypatch.chdir(tmp_path)
    meta = tmp_path / "src" / "rebrew-data.toml"
    meta.parent.mkdir(parents=True)
    meta.write_text('["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\n', encoding="utf-8")
    out = tmp_path / "src" / "link_stubs.c"
    runner = CliRunner()
    args = ["--data-metadata", str(meta), "--output", str(out), "--json"]

    assert runner.invoke(app, args).exit_code == 0
    # Stand in for a converged calibrate-bss run.
    out.write_text(
        out.read_text(encoding="utf-8").replace("g_bss_tail[0x400000]", "g_bss_tail[0x1234]"),
        encoding="utf-8",
    )
    assert read_calibrated_tail(out) == 0x1234

    result = runner.invoke(app, args)
    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert payload["tail"] == "0x1234"
    assert payload["tail_preserved"] is True
    text = out.read_text(encoding="utf-8")
    assert "g_bss_tail[0x1234]" in text
    assert "char g_a[1] = {0};" in text


def test_read_calibrated_tail_ignores_hand_written_stub(tmp_path: Path) -> None:
    """A stub this command did not generate is not ours to measure."""
    p = tmp_path / "link_stubs.c"
    p.write_text("unsigned char g_bss_tail[0x99] = {0};\n", encoding="utf-8")
    assert read_calibrated_tail(p) is None
    assert read_calibrated_tail(tmp_path / "missing.c") is None


def test_gen_link_stubs_dedups_repeated_names(tmp_path: Path) -> None:
    """Two addresses with one name would emit the definition twice."""
    meta = tmp_path / "rebrew-data.toml"
    meta.write_text(
        '["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\n'
        '["SERVER.0x10027010"]\nname = "g_a"\nsection = ".data"\n',
        encoding="utf-8",
    )
    text = gen_link_stubs(meta)
    assert text.count("char g_a[1] = {0};") == 1


# ---------------------------------------------------------------------------
# gen-layout --data-gap
# ---------------------------------------------------------------------------


def _mk_pe_with_data(data_size: int = 0x100) -> bytes:
    """Minimal 4-section PE (text/rdata/data/reloc) with a .data raw region."""
    text_va, rdata_va, data_va, reloc_va = 0x1000, 0x2000, 0x3000, 0x4000
    raw_off = 0x200
    text_raw = b"\xc3" + b"\x00" * (0x1000 - 1)
    data_raw = bytes(range(data_size)) + b"\x00" * (0x200 - data_size)

    dos = bytearray(0x80)
    dos[0:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, 0x80)
    coff = struct.pack("<HHIIIHH", 0x14C, 4, 0, 0, 0, 0xE0, 0x0102)
    opt = bytearray(struct.pack("<H", 0x10B))
    opt += b"\x00" * (0xE0 - 2)
    struct.pack_into("<I", opt, 0x38, 0x1000)  # SizeOfImage
    secs = b""
    for name, vs, va, raw_sz, chars in (
        (b".text\x00\x00\x00", 0x1000, text_va, 0x1000, 0x60000020),
        (b".rdata\x00\x00", 0x200, rdata_va, 0x200, 0x40000040),
        (b".data\x00\x00\x00", 0x200, data_va, 0x200, 0xC0000040),
        (b".reloc\x00\x00", 0x200, reloc_va, 0x200, 0x42000040),
    ):
        secs += struct.pack("<8sIIIIIIHHI", name, vs, va, raw_sz, raw_off, 0, 0, 0, 0, chars)
        raw_off += raw_sz
    hdrs = dos + b"PE\x00\x00" + coff + opt + secs
    hdrs += b"\x00" * (0x200 - len(hdrs))
    out = bytearray(hdrs)
    out += text_raw  # .text at 0x200 .. 0x1200
    out += b"\x00" * 0x200  # .rdata at 0x1200
    out += data_raw  # .data at 0x1400
    out += b"\x00" * 0x200  # .reloc at 0x1600
    return bytes(out)


def test_gen_data_restore() -> None:
    pe = _mk_pe_with_data(0x100)
    text = gen_data_restore(pe, "TEST", 0x40)
    assert "/* data gap TEST 3040 */" in text
    assert "// DATA:" not in text
    assert "g_data_restore_gap[0x1c0]" in text
    assert "0x40,0x41" in text  # bytes [0x40:0x100] of the .data raw
    assert text.count("0x") > 5


# ---------------------------------------------------------------------------
# calibrate-bss helpers
# ---------------------------------------------------------------------------


def test_read_data_vs(tmp_path: Path) -> None:
    pe = _mk_pe_with_data()
    p = tmp_path / "out.dll"
    p.write_bytes(pe)
    assert read_data_vs(p) == 0x200


def test_find_link_cmd(tmp_path: Path) -> None:
    build = tmp_path / "build" / "CMakeFiles" / "server_dll.dir"
    build.mkdir(parents=True)
    (build / "link.txt").write_text(
        "/nologo /out:/abs/server.dll /pdb:/abs/server.pdb /dll a.obj", encoding="utf-8"
    )
    link_cwd, tpl, target_dir = find_link_cmd(tmp_path)
    assert link_cwd == tmp_path / "build"
    assert target_dir == build
    assert "/out:{out}" in tpl and "/pdb:{out}.pdb" in tpl
    assert "{options}" in tpl


# ---------------------------------------------------------------------------
# order-sources CLI
# ---------------------------------------------------------------------------


class TestOrderSourcesCli:
    """The command's own argument gate: a malformed --first-va must name the
    problem and exit, not reach int("", 0) and leak a raw ValueError."""

    @staticmethod
    def _run(*args: str) -> Result:
        from typer.testing import CliRunner

        from rebrew import order_sources as mod

        return CliRunner().invoke(mod.app, list(args))

    def test_prints_ordered_files(self, tmp_path: Path) -> None:
        lo = _mk_src(tmp_path, "b.c", 0x10001000)
        hi = _mk_src(tmp_path, "a.c", 0x10003000)
        result = self._run(str(hi), str(lo))
        assert result.exit_code == 0
        assert result.stdout.split() == [str(lo), str(hi)]

    def test_json_orders_and_reports_excluded(self, tmp_path: Path) -> None:
        import json

        lo = _mk_src(tmp_path, "b.c", 0x10001000)
        dead = _mk_src(tmp_path, "dead.c", None)
        result = self._run("--json", "--exclude", "dead.c", str(dead), str(lo))
        assert result.exit_code == 0
        payload = json.loads(result.stdout)
        assert payload["ordered"] == [str(lo)]
        assert payload["excluded"] == ["dead.c"]

    def test_first_va_table_orders_a_markerless_file(self, tmp_path: Path) -> None:
        zlib = _mk_src(tmp_path, "zlib.c", None)
        game = _mk_src(tmp_path, "game.c", 0x10002000)
        result = self._run("--json", "--first-va", "zlib.c=0x10001000", str(game), str(zlib))
        assert result.exit_code == 0
        import json

        assert json.loads(result.stdout)["ordered"] == [str(zlib), str(game)]

    @pytest.mark.parametrize("entry", ["zlib.c", "=0x1000", "zlib.c=", "zlib.c=0xzz"])
    def test_malformed_first_va_exits_with_the_offending_value(
        self, tmp_path: Path, entry: str
    ) -> None:
        src = _mk_src(tmp_path, "a.c", 0x1000)
        result = self._run("--first-va", entry, str(src))
        assert result.exit_code == 2  # EXIT_ERROR
        assert entry in result.stderr

    def test_malformed_first_va_is_json_when_json_is_requested(self, tmp_path: Path) -> None:
        import json

        src = _mk_src(tmp_path, "a.c", 0x1000)
        result = self._run("--json", "--first-va", "nope", str(src))
        assert result.exit_code != 0
        assert "nope" in json.loads(result.stdout)["error"]
