"""Tests for the checked-in binary fixtures in ``tests/fixtures/``.

The fixtures are tiny synthetic PE/COFF/ELF/.lib files generated by
``tools/gen_fixtures.py`` (no wine, no vendored toolchain).  These tests
prove the parse / compare / reloc paths — and the ``gen_flirt_pat`` →
``flirt`` pipeline — run end-to-end in CI, and assert the checked-in bytes
never drift from the generator.
"""

from __future__ import annotations

import struct
from pathlib import Path

import lief

from rebrew.binary_loader import extract_bytes_at_va, load_binary
from rebrew.core.matching import smart_reloc_compare
from rebrew.gen_flirt_pat import bytes_to_pat_line, parse_archive, parse_coff_obj
from rebrew.matcher.parsers import (
    CoffRelocRecord,
    list_obj_symbols,
    parse_obj_relocs_full,
    parse_obj_symbol_and_relocs,
)

FIXTURES = Path(__file__).parent / "fixtures"

# Mirrors tools/gen_fixtures.py (kept in sync by the freshness test below).
FUNC1 = bytes.fromhex("55 8b ec 8b 05 00 00 00 00 5d c3")
FUNC2 = bytes.fromhex("55 8b ec e8 00 00 00 00 5d c3")
FUNC2_OFFSET = 0x10
CODE = FUNC1 + b"\xcc" * (FUNC2_OFFSET - len(FUNC1)) + FUNC2 + b"\xcc\xcc"

FUNC1_VA = 0x401000
FUNC2_VA = 0x401010
EXTERN_VA = 0x402000
CALLEE_VA = 0x402010
DECOY_VA = 0x403000  # second catalog symbol — a value pointing at it is provably wrong


def test_fixtures_match_generator() -> None:
    """Checked-in fixture bytes are byte-identical to the generator output."""
    from tools.gen_fixtures import build_all

    for name, expected in build_all().items():
        path = FIXTURES / name
        assert path.exists(), f"missing fixture {name} — run python tools/gen_fixtures.py"
        assert path.read_bytes() == expected, (
            f"{name} is stale — run python tools/gen_fixtures.py to regenerate"
        )


class TestCoffObj:
    """The .obj fixture parses into the exact two functions with typed relocs."""

    def test_func1_bytes_and_dir32_reloc(self) -> None:
        code, relocs, records = parse_obj_symbol_and_relocs(FIXTURES / "mini.obj", "_func1")
        assert code == FUNC1
        assert relocs == {5: "_extern_var"}
        assert records == [CoffRelocRecord(offset=5, type=0x06, symbol="_extern_var")]

    def test_func2_bytes_and_rel32_reloc(self) -> None:
        code, relocs, records = parse_obj_symbol_and_relocs(FIXTURES / "mini.obj", "_func2")
        assert code == FUNC2
        assert relocs == {4: "_callee"}  # offset relative to _func2's start
        assert records == [CoffRelocRecord(offset=4, type=0x14, symbol="_callee")]

    def test_func1_boundary_stops_at_func2(self) -> None:
        """func_end for _func1 is the next symbol's offset, not section end."""
        code, _, _ = parse_obj_symbol_and_relocs(FIXTURES / "mini.obj", "_func1")
        assert code == FUNC1  # int3 inter-function padding is trimmed, 11 bytes exactly

    def test_relocs_full_roundtrip(self) -> None:
        records = parse_obj_relocs_full(FIXTURES / "mini.obj", "_func1")
        assert [(r.offset, r.type, r.symbol) for r in records] == [(5, 0x06, "_extern_var")]

    def test_list_symbols(self) -> None:
        assert set(list_obj_symbols(FIXTURES / "mini.obj")) == {"_func1", "_func2"}


class TestPeFixture:
    def test_format_detection(self) -> None:
        path = FIXTURES / "mini_pe.exe"
        assert lief.is_pe(str(path))
        info = load_binary(path)
        assert info.format == "pe"
        assert info.image_base == 0x400000
        assert ".text" in info.sections

    def test_extract_functions_at_va(self) -> None:
        info = load_binary(FIXTURES / "mini_pe.exe")
        assert extract_bytes_at_va(info, FUNC1_VA, len(FUNC1)) == FUNC1
        assert extract_bytes_at_va(info, FUNC2_VA, len(FUNC2)) == FUNC2

    def test_import_table_parses(self) -> None:
        """The KERNEL32 import directory wired into the fixture is real."""
        pe = lief.PE.parse(str(FIXTURES / "mini_pe.exe"))
        assert pe is not None
        imports = pe.imports
        assert len(imports) == 1
        assert imports[0].name == "KERNEL32.dll"
        assert [e.name for e in imports[0].entries] == ["GetTickCount"]


class TestElfFixture:
    def test_format_detection_and_extraction(self) -> None:
        path = FIXTURES / "mini.elf"
        assert lief.is_elf(str(path))
        info = load_binary(path)
        assert info.format == "elf"
        assert extract_bytes_at_va(info, FUNC1_VA, len(FUNC1)) == FUNC1
        assert extract_bytes_at_va(info, FUNC2_VA, len(FUNC2)) == FUNC2


class TestSmartRelocCompare:
    """smart_reloc_compare over real parsed typed records from the fixture."""

    def _records(self, symbol: str) -> list[CoffRelocRecord]:
        return parse_obj_relocs_full(FIXTURES / "mini.obj", symbol)

    def test_dir32_valid_and_invalid(self) -> None:
        records = self._records("_func1")
        name_to_va = {"_extern_var": EXTERN_VA, "_decoy": DECOY_VA}
        # Valid: target imm32 == catalog VA.
        good = FUNC1[:5] + struct.pack("<I", EXTERN_VA) + FUNC1[9:]
        matched, count, total, valid, invalid = smart_reloc_compare(
            FUNC1, good, records, name_to_va, section_va=FUNC1_VA
        )
        assert matched and count > 0 and valid == [5] and invalid == []
        # Invalid: target imm32 points at a *different* cataloged symbol —
        # the only case smart_reloc_compare can prove wrong for DIR32.
        bad = FUNC1[:5] + struct.pack("<I", DECOY_VA) + FUNC1[9:]
        matched, count, total, valid, invalid = smart_reloc_compare(
            FUNC1, bad, records, name_to_va, section_va=FUNC1_VA
        )
        assert not matched and invalid == [5]

    def test_rel32_valid_and_invalid(self) -> None:
        records = self._records("_func2")
        name_to_va = {"_callee": CALLEE_VA}
        # Valid: imm32 == callee_va - pc, pc = section_va + offset + 4.
        pc = FUNC2_VA + 4 + 4
        imm = (CALLEE_VA - pc) & 0xFFFFFFFF
        good = FUNC2[:4] + struct.pack("<I", imm) + FUNC2[8:]
        matched, count, total, valid, invalid = smart_reloc_compare(
            FUNC2, good, records, name_to_va, section_va=FUNC2_VA
        )
        assert matched and valid == [4] and invalid == []
        # Invalid: imm32 for a different target.
        bad = FUNC2[:4] + struct.pack("<I", (EXTERN_VA - pc) & 0xFFFFFFFF) + FUNC2[8:]
        matched, count, total, valid, invalid = smart_reloc_compare(
            FUNC2, bad, records, name_to_va, section_va=FUNC2_VA
        )
        assert not matched and invalid == [4]


class TestFlirtPipeline:
    """gen_flirt_pat → python-flirt .pat → scan mini_pe.exe, all offline."""

    def test_parse_archive_yields_member(self) -> None:
        members = list(parse_archive(str(FIXTURES / "mini.lib")))
        assert [(name, data) for name, data in members] and members[0][0] == "mini.obj"

    def test_parse_coff_obj_extracts_both_functions(self) -> None:
        ((_, obj_data),) = parse_archive(str(FIXTURES / "mini.lib"))
        funcs = {name: (code, relocs) for name, code, relocs in parse_coff_obj(obj_data)}
        # gen_flirt_pat keeps the raw section slice (int3 padding included).
        assert funcs["_func1"] == (FUNC1 + b"\xcc" * 5, {5, 6, 7, 8})  # DIR32 spans 4 bytes
        assert funcs["_func2"] == (FUNC2 + b"\xcc\xcc", {4, 5, 6, 7})  # REL32 spans 4 bytes

    def test_bytes_to_pat_line_masks_relocs(self) -> None:
        line = bytes_to_pat_line("_func1", FUNC1, {5, 6, 7, 8})
        assert line.startswith("558BEC8B05........5DC3")  # reloc slot masked
        assert line.endswith(":0000 _func1")

    def test_pat_line_scans_pe_text(self) -> None:
        import flirt  # python-flirt package (module name is flirt)

        line = bytes_to_pat_line("_func1", FUNC1, {5, 6, 7, 8})
        sigs = flirt.parse_pat(line + "\n---\n")  # .pat files end with a --- terminator
        assert sigs, "python-flirt must accept the generated .pat line"
        matcher = flirt.compile(sigs)

        info = load_binary(FIXTURES / "mini_pe.exe")
        text = info.sections[".text"]
        code_data = info.data[text.file_offset : text.file_offset + text.raw_size]
        matches = matcher.match(code_data[:1024])
        names = {n[0] if isinstance(n, tuple) else str(n) for m in matches for n in m.names}
        assert "_func1" in names
