"""Tests for the byte-identity link tools: order-sources, calibrate-bss,
gen-link-stubs, verify-placement, and gen-layout --data-gap."""

from __future__ import annotations

import struct
from pathlib import Path

from rebrew.calibrate_bss import find_link_cmd, read_data_vs
from rebrew.gen_layout import gen_data_restore
from rebrew.gen_link_stubs import gen_link_stubs, load_data_symbols
from rebrew.order_sources import file_va, order_sources

# ---------------------------------------------------------------------------
# order-sources
# ---------------------------------------------------------------------------


def _mk_src(tmp_path: Path, name: str, va: int | None) -> Path:
    p = tmp_path / name
    content = "int x;\n"
    if va is not None:
        content += f"// FUNCTION: server.dll 0x{va:x}\nvoid f(void) {{}}\n"
    p.write_text(content)
    return p


def test_file_va(tmp_path: Path) -> None:
    assert file_va(_mk_src(tmp_path, "a.c", 0x10002000)) == 0x10002000
    assert file_va(_mk_src(tmp_path, "b.c", None)) is None


def test_order_sources(tmp_path: Path) -> None:
    a = _mk_src(tmp_path, "a.c", 0x10003000)
    b = _mk_src(tmp_path, "b.c", 0x10001000)
    c = _mk_src(tmp_path, "c.c", None)
    ordered, excluded = order_sources([a, c, b], {}, set())
    assert ordered == [b, a, c]


def test_order_sources_first_va_and_exclude(tmp_path: Path) -> None:
    z = _mk_src(tmp_path, "zlib.c", None)
    g = _mk_src(tmp_path, "game.c", 0x10001000)
    dead = _mk_src(tmp_path, "uncompr.c", None)
    ordered, excluded = order_sources([z, g, dead], {"zlib.c": 0x10000000}, {"uncompr.c"})
    assert ordered == [z, g]
    assert excluded == ["uncompr.c"]


# ---------------------------------------------------------------------------
# gen-link-stubs
# ---------------------------------------------------------------------------


def test_load_data_symbols(tmp_path: Path) -> None:
    meta = tmp_path / "rebrew-data.toml"
    meta.write_text(
        '["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\ntype = "int"\n'
        '["SERVER.0x10027004"]\nname = "g_b"\nsection = ".bss"\n'
        '["SERVER.0x10027010"]\nname = "g_c"\nsection = ".data"\n',
        encoding="utf-8",
    )
    syms = load_data_symbols(meta)
    assert [(a, n) for a, n, _ in syms] == [
        (0x10027000, "g_a"),
        (0x10027010, "g_c"),
    ]


def test_gen_link_stubs(tmp_path: Path) -> None:
    meta = tmp_path / "rebrew-data.toml"
    meta.write_text('["SERVER.0x10027000"]\nname = "g_a"\nsection = ".data"\n', encoding="utf-8")
    text = gen_link_stubs(meta)
    assert "char g_a[1] = {0};" in text
    assert "g_bss_tail[0x400000]" in text
    assert "AUTO-GENERATED by rebrew gen-link-stubs" in text


# ---------------------------------------------------------------------------
# gen-layout --data-gap
# ---------------------------------------------------------------------------


def _mk_pe_with_data(data_size: int = 0x100) -> bytes:
    """Minimal 4-section PE (text/rdata/data/reloc) with a .data raw region."""
    text_va, rdata_va, data_va, reloc_va = 0x1000, 0x2000, 0x3000, 0x4000
    raw_off = 0x200
    text_raw = b"\xc3" + b"\x00" * (0x1000 - 1)
    data_raw = bytes(range(data_size)) + b"\x00" * (0x200 - data_size)

    dos = bytearray(0x80)
    dos[0:2] = b"MZ"
    struct.pack_into("<I", dos, 0x3C, 0x80)
    coff = struct.pack("<HHIIIHH", 0x14C, 4, 0, 0, 0, 0xE0, 0x0102)
    opt = bytearray(struct.pack("<H", 0x10B))
    opt += b"\x00" * (0xE0 - 2)
    struct.pack_into("<I", opt, 0x38, 0x1000)  # SizeOfImage
    secs = b""
    for name, vs, va, raw_sz, chars in (
        (b".text\x00\x00\x00", 0x1000, text_va, 0x1000, 0x60000020),
        (b".rdata\x00\x00", 0x200, rdata_va, 0x200, 0x40000040),
        (b".data\x00\x00\x00", 0x200, data_va, 0x200, 0xC0000040),
        (b".reloc\x00\x00", 0x200, reloc_va, 0x200, 0x42000040),
    ):
        secs += struct.pack("<8sIIIIIIHHI", name, vs, va, raw_sz, raw_off, 0, 0, 0, 0, chars)
        raw_off += raw_sz
    hdrs = dos + b"PE\x00\x00" + coff + opt + secs
    hdrs += b"\x00" * (0x200 - len(hdrs))
    out = bytearray(hdrs)
    out += text_raw  # .text at 0x200 .. 0x1200
    out += b"\x00" * 0x200  # .rdata at 0x1200
    out += data_raw  # .data at 0x1400
    out += b"\x00" * 0x200  # .reloc at 0x1600
    return bytes(out)


def test_gen_data_restore() -> None:
    pe = _mk_pe_with_data(0x100)
    text = gen_data_restore(pe, "TEST", 0x40)
    assert "// DATA: TEST 0x3040" in text
    assert "g_data_restore_gap[0x1c0]" in text
    assert "0x40,0x41" in text  # bytes [0x40:0x100] of the .data raw
    assert text.count("0x") > 5


# ---------------------------------------------------------------------------
# calibrate-bss helpers
# ---------------------------------------------------------------------------


def test_read_data_vs(tmp_path: Path) -> None:
    pe = _mk_pe_with_data()
    p = tmp_path / "out.dll"
    p.write_bytes(pe)
    assert read_data_vs(p) == 0x200


def test_find_link_cmd(tmp_path: Path) -> None:
    build = tmp_path / "build" / "CMakeFiles" / "server_dll.dir"
    build.mkdir(parents=True)
    (build / "link.txt").write_text(
        "/nologo /out:/abs/server.dll /pdb:/abs/server.pdb /dll a.obj", encoding="utf-8"
    )
    link_cwd, tpl, target_dir = find_link_cmd(tmp_path)
    assert link_cwd == tmp_path / "build"
    assert target_dir == build
    assert "/out:{out}" in tpl and "/pdb:{out}.pdb" in tpl
    assert "{options}" in tpl
