"""builtins.py — the packaged CLI components.

Every built-in tool is one :class:`rebrew.plugin.CliComponent`.  The loader
in :mod:`rebrew.main` activates these and any third-party components from
the ``rebrew.commands`` / ``rebrew.multicommands`` entry-point groups
through the same path, so built-ins hold no privileged place in the host.
"""

from __future__ import annotations

from rebrew.plugin import CliComponent, Panel

BUILTIN_COMPONENTS: tuple[CliComponent, ...] = (
    CliComponent(
        name="rename",
        module="rebrew.rename",
        help="Rename a function and update all cross-references.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="test",
        module="rebrew.test",
        help="Compile, byte-compare, and auto-update STATUS annotation.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="verify",
        module="rebrew.verify",
        help="Validate compiled bytes against target binary.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="skeleton",
        module="rebrew.skeleton",
        help="Generate skeleton C files for matching.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="sync",
        module="rebrew.ghidra.cli",
        help="Sync with Ghidra: BinSync state dir field sync + MCP structural ops.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="lint",
        module="rebrew.lint",
        help="Lint C annotations.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="fix",
        module="rebrew.fixup",
        help="Make raw decompiler output compilable (DecBench-style fixup: sanitize + inject).",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="recover-structs",
        module="rebrew.struct_recover",
        help="Recover struct definitions from decompiler output (offset evidence → typedefs).",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="decompile",
        module="rebrew.name_decomp",
        help="Decompile a function via kuna/r2ghidra/ghidra, optionally applying known struct names (--named).",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="match",
        module="rebrew.match",
        help="GA matching engine — single file or batch (--all).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="diff",
        module="rebrew.diff",
        help="Compile and diff a reversed function against the target binary.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="postlink",
        module="rebrew.postlink",
        help="Normalize a built binary's layout onto a reference (import records, .data/.reloc, PE stamps).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="stack-cmp",
        module="rebrew.stack_cmp",
        help="Compare the compiled function's stack frame against the target binary.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="asm",
        module="rebrew.asm",
        help="Disassemble a function (hex dump or NASM source).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="switch",
        module="rebrew.switch",
        help="Decode jump-table switch dispatches in a function (case → handler map).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="init",
        module="rebrew.init",
        help="Initialize a new rebrew project.",
        panel=Panel.PROJECT_SETUP,
        is_group=False,
    ),
    CliComponent(
        name="intake",
        module="rebrew.intake",
        help="One-shot binary onboarding: init + toolchain detect + functions + document.",
        panel=Panel.PROJECT_SETUP,
        is_group=False,
    ),
    CliComponent(
        name="gen-layout",
        module="rebrew.gen_layout",
        help="Generate linker-script scaffolding from the binary (.def, layout manifest, IAT seed).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="cmake-toolchain",
        module="rebrew.cmake_tc",
        help="Write a CMake toolchain file that drives a docker toolchain via rebrew-cmake-*.",
        panel=Panel.PROJECT_SETUP,
        is_group=False,
    ),
    CliComponent(
        name="order-sources",
        module="rebrew.order_sources",
        help="Order source files by their first function's original VA (position-aligned .text).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="calibrate-bss",
        module="rebrew.calibrate_bss",
        help="Calibrate a BSS tail pad so the raw link's .data VirtualSize matches the reference.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="gen-link-stubs",
        module="rebrew.gen_link_stubs",
        help="Generate a link_stubs.c-style BSS placeholder TU from the data metadata.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="gen-stubs",
        module="rebrew.gen_stubs",
        help="Generate a stub TU for unresolved linker symbols (LNK2001/LNK2019).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="inline-strings",
        module="rebrew.inline_strings",
        help="Inline string-literal globals (s_<hint>_<0xADDR>) from the reference binary.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="verify-placement",
        module="rebrew.verify_placement",
        help="Compare .data symbol VAs of the current build against the data metadata.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="text-audit",
        module="rebrew.text_audit",
        help="Compare .text function VAs of the current build against the source markers.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="link-sweep",
        module="rebrew.link_sweep",
        help="Sweep LINK options to reproduce the reference PE header (find stamp-only fields).",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="link-order",
        module="rebrew.link_order",
        help="Enforce VA-ordered sources into CMakeLists.txt SOURCES (drift gate).",
        panel=Panel.PROJECT_SETUP,
        is_group=False,
    ),
    CliComponent(
        name="document-unmatched",
        module="rebrew.document_unmatched",
        help="Document unmatched functions as STUB skeletons + blockers.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="pdb-info",
        module="rebrew.pdb_info",
        help="Extract compiler version, flags, and function names from a sibling PDB.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="discover-functions",
        module="rebrew.discover",
        help="Enumerate functions: rizin aaa/aap + capstone sweep, sizes validated.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="data",
        module="rebrew.data",
        help="Global data scanner for .data/.rdata/.bss sections.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="graph",
        module="rebrew.depgraph",
        help="Function dependency graph visualization (--cu-map for CU boundaries).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="status",
        module="rebrew.status",
        help="At-a-glance reversing progress overview.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="todo",
        module="rebrew.todo",
        help="Prioritized action list: what to work on next.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="unpack-lzexe",
        module="rebrew.lzexe_cli",
        help="Unpack an LZEXE 0.90/0.91 compressed DOS executable.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="crt-match",
        module="rebrew.crt_match",
        help="CRT source cross-reference matcher.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="lib-match",
        module="rebrew.lib_match",
        help="Byte-compare reversed functions against linked static libraries.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="imports",
        module="rebrew.imports",
        help="List PE import-table symbols and detect import stubs.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="fingerprints",
        module="rebrew.fingerprints",
        help="Binary fingerprint bundle: hashes, imphash, rich-header hash, section entropy.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="pe-info",
        module="rebrew.pe_info",
        help="Dump PE metadata: identity, sections, security flags, debug, Rich header.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="crypto-scan",
        module="rebrew.crypto_scan",
        help="Detect crypto constant tables, crypto imports, and crypto-named functions.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="security-scan",
        module="rebrew.security_scan",
        help="Scan C sources for unsafe API use (unbounded copies, format strings, command execution).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="verify-exports",
        module="rebrew.exports",
        help="Verify the recompiled binary's export table matches the original target.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="strings",
        module="rebrew.strings",
        help="Extract printable strings from data sections with cross-references.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="xrefs",
        module="rebrew.xrefs",
        help="Cross-reference explorer: find code that references an address.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="describe",
        module="rebrew.describe",
        help="Per-function recon dossier: callers, callees, strings, imports.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="analyze",
        module="rebrew.analyze",
        help="One-shot intelligence dossier: toolchain, strings, imports, dispatch, FLIRT.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="report",
        module="rebrew.report",
        help="Generate a static HTML documentation site for the project.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="diagnose",
        module="rebrew.diagnose",
        help="Explain why a function compiles with its toolchain+flags (resolution trace).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="flirt",
        module="rebrew.flirt",
        help="FLIRT signature scanning.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="identify-library",
        module="rebrew.identify_library",
        help="Identify library functions (FLIRT + imports + CRT) into library_*.h.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="gen-flirt-pat",
        module="rebrew.gen_flirt_pat",
        help="Generate FLIRT .pat files from COFF .lib archives.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="doctor",
        module="rebrew.doctor",
        help="Diagnostic checks for project health.",
        panel=Panel.PROJECT_SETUP,
        is_group=False,
    ),
    CliComponent(
        name="split",
        module="rebrew.split",
        help="Split multi-function C files into single-function files.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="merge",
        module="rebrew.merge",
        help="Merge single-function C files into one multi-function file.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="prove",
        module="rebrew.prove",
        help="Prove semantic equivalence via symbolic execution.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="solutions",
        module="rebrew.solutions_db",
        help="Query the GA solutions database (winning fingerprints + run history).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="round-trip",
        module="rebrew.round_trip",
        help="Splice matched functions back into target PE and verify.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="build-db",
        module="rebrew.build_db",
        help="Build SQLite coverage database from data JSON.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="dashboard",
        module="rebrew.dashboard",
        help="Serve a read-only web dashboard over the coverage database.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="binsync-export",
        module="rebrew.binsync.export",
        help="Export annotations to an experimental BinSync state directory.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="binsync-import",
        module="rebrew.binsync.importer",
        help="Import a BinSync state directory into rebrew metadata.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="binsync-diff",
        module="rebrew.binsync.diff",
        help="Show where rebrew and a BinSync state diverge (read-only).",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="binsync-init",
        module="rebrew.binsync.init",
        help="Initialize a BinSync git repo (root + user branches) for a target.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="binsync-overlay",
        module="rebrew.binsync.overlay",
        help="Overlay a related target's BinSync names onto this target.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="catalog",
        module="rebrew.catalog",
        help="Build coverage catalog, data JSON, CSV/Ghidra exports, and DB.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="similar",
        module="rebrew.similar",
        help="Find structurally similar functions in the target binary.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="binary-similarity",
        module="rebrew.binary_similarity",
        help="Whole-binary structural similarity vs another binary (versions/DLL+EXE).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="merge-sweep",
        module="rebrew.merge_sweep",
        help="Deterministic TU-partition search over cu-map clusters.",
        panel=Panel.MATCHING,
        is_group=False,
    ),
    CliComponent(
        name="climb",
        module="rebrew.climb",
        help="Deterministic single-statement hill-climb for one function.",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="cross-import",
        module="rebrew.cross_import",
        help="Import matched functions from another target (same code, different VAs).",
        panel=Panel.DEVELOPMENT,
        is_group=False,
    ),
    CliComponent(
        name="near-diag",
        module="rebrew.near_diag",
        help="Classify why a NEAR_MATCHING function does not byte-match.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="refactor",
        module="rebrew.refactor",
        help="Analyse the source tree and suggest refactoring opportunities.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="symbol-addrs",
        module="rebrew.symbol_addrs",
        help="Export function symbols as a splat-style symbol_addrs.csv.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="context",
        module="rebrew.context",
        help="Emit a universal C context file (types + signatures) for decompiler backends.",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="objdiff",
        module="rebrew.objdiff_project",
        help="Generate an objdiff project (target objects + objdiff.json) for GUI diffing.",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="decompme",
        module="rebrew.decompme",
        help="Upload a function to decomp.me as a collaborative scratch (claim URL returned).",
        panel=Panel.EXPORT_SYNC,
        is_group=False,
    ),
    CliComponent(
        name="layout-map",
        module="rebrew.layout_map",
        help="Dump reference-side layout measurements (sections, gaps, IAT, exports).",
        panel=Panel.ANALYSIS,
        is_group=False,
    ),
    CliComponent(
        name="blocker",
        module="rebrew.blocker",
        help="Manage BLOCKER metadata (set/clear/show) — programmatic only.",
        panel=Panel.ANALYSIS,
        is_group=True,
    ),
    CliComponent(
        name="orphans",
        module="rebrew.orphans",
        help="List or prune orphaned metadata blocks (no source marker).",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="types",
        module="rebrew.types_cli",
        help="Check declared struct layouts; apply types to signatures.",
        panel=Panel.ANALYSIS,
        is_group=True,
    ),
    CliComponent(
        name="extract",
        module="rebrew.extract",
        help="Extract and disassemble functions from binary.",
        panel=Panel.MATCHING,
        is_group=True,
    ),
    CliComponent(
        name="cfg",
        module="rebrew.cfg",
        help="Read and edit rebrew-project.toml programmatically.",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="cache",
        module="rebrew.cache_cli",
        help="Manage the compile result cache.",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="skills",
        module="rebrew.skills",
        help="Discover and display agent skills bundled with rebrew.",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="resource",
        module="rebrew.resource",
        help="Compare / extract PE resource (.rsrc) sections.",
        panel=Panel.ANALYSIS,
        is_group=True,
    ),
    CliComponent(
        name="library",
        module="rebrew.library",
        help="Per-library toolchain/flags overrides (rebrew-libraries.toml).",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="toolchain",
        module="rebrew.toolchain_cli",
        help="Manage toolchains (Windows/DOS profiles run in docker).",
        panel=Panel.PROJECT_SETUP,
        is_group=True,
    ),
    CliComponent(
        name="binsync",
        module="rebrew.binsync.cli",
        help="BinSync state sync: push/pull/summary plus init/diff/overlay.",
        panel=Panel.EXPORT_SYNC,
        is_group=True,
    ),
)
