"""Emit the per-file CFLAGS a CMake build must compile with.

The flags a translation unit compiles with are ``rebrew-functions.toml``'s
business: that is the store every tool resolves from, and rebrew's own lint
tells users to migrate inline ``// CFLAGS:`` into it.  A CMake build that reads
the ``.c`` annotation instead therefore compiles something the tools never
measured — guild-rebrew's ``gm_AllocSpieler`` ran that way, 363 linked bytes
behind the numbers recorded in its own notes (its annotation said
``/O2 /Gd /Oa``, its metadata ``/Oa /Ow``, and the notes described the second).

``rebrew cmake-flags`` closes that gap: it resolves each annotated source file's
effective flags through the same chain the tools use (per-function metadata →
nearest ``rebrew-libraries.toml`` → module preset → ``[compiler].cflags``) and
writes a CMake include that sets ``COMPILE_FLAGS`` for those files.  A CMake
project then does

    execute_process(COMMAND ${REBREW} cmake-flags -o ${CMAKE_BINARY_DIR}/rebrew-cflags.cmake)
    include(${CMAKE_BINARY_DIR}/rebrew-cflags.cmake)

and adds ``rebrew-functions.toml`` to ``CMAKE_CONFIGURE_DEPENDS`` so editing the
metadata reconfigures the build instead of silently reusing stale flags.

A compiler compiles a whole translation unit with one flag set, so a file whose
functions resolve to different flags cannot be honoured: that is reported as an
error naming the functions and their flags, not silently averaged.
"""

from __future__ import annotations

import os
from pathlib import Path

import typer
from rich.console import Console

from rebrew.annotation import parse_c_file_multi
from rebrew.cli import (
    EXIT_ERROR,
    TargetOption,
    json_print,
    require_config,
)
from rebrew.compile_overrides import resolve_compile_overrides
from rebrew.config import ProjectConfig
from rebrew.sources import iter_sources
from rebrew.utils import atomic_write_text, config_path

app = typer.Typer(add_completion=False, help=__doc__)
console = Console(stderr=True)

HEADER = """# Per-file compile flags from rebrew-functions.toml.
# Generated by `rebrew cmake-flags` — do not hand-edit; edit the metadata and
# re-run, or add rebrew-functions.toml to CMAKE_CONFIGURE_DEPENDS.
#
# A translation unit is compiled with one flag set, so a file whose functions
# resolve to different flags is an error (see the command's output).
"""


def _codegen_key(cflags: str) -> frozenset[str]:
    """The flags that decide emitted code — order-insensitive, no defines.

    ``/D`` is a compilation input, not an optimization decision, and this
    project's metadata carries ``/DREBREW_ALLOW_NAKED`` on some functions of a
    file and not others (the guard travels with the file, and the shipped build
    compiles neither).  A define alone therefore cannot make a translation unit
    ambiguous; a different ``/O``/``/G`` set can.
    """
    return frozenset(t for t in cflags.split() if not t.startswith(("/D", "-D")))


def _defines(cflags: str) -> set[str]:
    return {t for t in cflags.split() if t.startswith(("/D", "-D"))}


#: Markers that annotate CODE.  ``DATA``/``GLOBAL`` annotate bytes a file
#: defines (a generated string blob, a table) and carry no compile flags of
#: their own, so they must not participate in the per-file flag resolution: a
#: file legitimately holds both, and treating the data marker as a function
#: made the whole file look self-contradictory and refused to emit anything for
#: it (guild-rebrew's CrashDumpUnhandledExceptionFilter.c).
CODE_MARKERS = {"FUNCTION", "STUB", "LIBRARY"}


def collect(cfg: ProjectConfig, marker: str) -> tuple[dict[Path, str], list[str], list[str]]:
    """{absolute source path: cflags}, problem descriptions, and notes.

    `marker` is the annotation prefix (``SERVER``), not the target name: one
    source file carries one marker per target it belongs to, and only the
    requested target's entries may decide the flags.
    """
    files: dict[Path, str] = {}
    problems: list[str] = []
    notes: list[str] = []
    # iter_sources (not a bare reversed_dir rglob): shared sources serve every
    # target and need CMake flags too, and the glob honours source_ext
    # (a bare "*.c" drops every .cpp source).
    for src in iter_sources(cfg.reversed_dir, cfg):
        entries = [
            e
            for e in parse_c_file_multi(src, metadata_dir=cfg.metadata_dir)
            if e.va
            and e.module.upper() == marker.upper()
            and (not e.marker_type or e.marker_type.upper() in CODE_MARKERS)
        ]
        if not entries:
            continue
        seen: list[tuple[str, str]] = []
        for entry in entries:
            tc, flags = resolve_compile_overrides(
                cfg, src.parent, entry.toolchain or None, entry.cflags or None, entry.module
            )
            # A per-function `toolchain` pin is honoured by `rebrew test`/`verify`
            # (they invoke the compiler directly) but NOT by the CMake build, whose
            # compiler is fixed by the toolchain file.  Emitting only `flags` here
            # used to let a pin silently diverge: the metadata claimed one compiler
            # while the linked object came from another, so a function could read
            # NEAR_MATCHING at one score in `rebrew test` and contribute different
            # bytes to the deliverable.  Surface it instead of discarding it.
            if tc:
                notes.append(
                    f"{src.relative_to(cfg.root)}: "
                    f"{entry.symbol or f'0x{entry.va:08x}'} resolves toolchain "
                    f"'{tc}', but the CMake build's compiler is fixed by the "
                    f"toolchain file -- the pin affects `rebrew test`/`verify` "
                    f"only, never the linked bytes."
                )
            seen.append((entry.symbol or f"0x{entry.va:08x}", flags))
        distinct = {_codegen_key(f) for _, f in seen}
        if len(distinct) > 1:
            detail = "; ".join(f"{n} = '{f}'" for n, f in seen)
            problems.append(f"{src.relative_to(cfg.root)}: {detail}")
            continue
        # Defines are NOT emitted: the ones in this project's metadata are the
        # naked-reconstruction guard, which the shipped build must not compile.
        # Dropping is made visible rather than silent.
        dropped = set().union(*(_defines(f) for _, f in seen))
        if dropped:
            notes.append(
                f"{src.relative_to(cfg.root)}: define(s) "
                f"{' '.join(sorted(dropped))} not emitted (the shipped "
                f"build does not define them)"
            )
        files[src.resolve()] = " ".join(
            t for t in seen[0][1].split() if not t.startswith(("/D", "-D"))
        )
    return files, problems, notes


@app.callback(invoke_without_command=True)
def main(
    output: Path = typer.Option(
        Path("build/rebrew-cflags.cmake"), "--output", "-o", help="CMake include to write"
    ),
    sources_file: Path = typer.Option(
        None,
        "--sources-file",
        help="File listing the sources the build compiles (one path per line, "
        "relative to the project root).  Every listed file gets an entry: "
        "its metadata flags when it has any, the project default when it "
        "does not.  Without this, a file the build compiles but nothing "
        "annotates would silently lose its flags.",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Write the per-file CFLAGS table as a CMake include."""
    cfg = require_config(target=target, json_mode=json_output)
    files, problems, notes = collect(cfg, cfg.marker)

    # The table is keyed by the path spelling CMake knows: a listed source
    # keeps the spelling the build gave it (references/zlib-1.1.3 is a symlink
    # to references/zlib, so a resolved path would not match the target's
    # source entry).
    emit: dict[str, str] = {}
    listed: set[Path] = set()
    if sources_file is not None:
        for line in sources_file.read_text(encoding="utf-8").splitlines():
            rel = config_path(line.strip()).as_posix()
            if not rel or not (cfg.root / rel).is_file():
                continue
            path = (cfg.root / rel).resolve()
            listed.add(path)
            if path in files:
                emit[rel] = files[path]
            else:
                # Un-annotated source: the project default, resolved the same
                # way an annotated file's fallback is, so the table is complete
                # (without this a file the build compiles but nothing annotates
                # would silently lose its flags).
                _tc, flags = resolve_compile_overrides(cfg, path.parent, None, None, "")
                emit[rel] = flags
    for path, flags in files.items():
        if path in listed:
            continue
        emit[os.path.relpath(path, cfg.root).replace(os.sep, "/")] = flags

    if not json_output:
        for line in notes:
            console.print(f"[yellow]note:[/] {line}")
        for line in problems:
            console.print(
                f"[red]error:[/] functions in one file resolve to different "
                f"flags — split the file or align the metadata:\n  {line}"
            )

    lines = [HEADER]
    for rel, flags in sorted(emit.items()):
        lines.append(
            f'set_source_files_properties("${{CMAKE_CURRENT_SOURCE_DIR}}/{rel}"\n'
            f'    PROPERTIES COMPILE_FLAGS "{flags}")\n'
        )
    text = "".join(lines)

    if problems:
        if json_output:
            json_print(
                {
                    "written": None,
                    "files": dict(emit),
                    "problems": problems,
                    "notes": notes,
                }
            )
        raise typer.Exit(code=EXIT_ERROR)

    written: str | None = None
    if dry_run:
        if not json_output:
            print(text)
    else:
        atomic_write_text(output, text)
        written = str(output)

    if json_output:
        # Report the same table the include uses (emit), including
        # --sources-file entries that lack annotations — not collect()'s
        # annotated-only map.
        json_print(
            {
                "written": written,
                "files": dict(emit),
                "problems": problems,
                "notes": notes,
            }
        )
    elif not dry_run:
        console.print(f"[green]cmake-flags:[/] wrote {output} ({len(emit)} source files)")
