"""cmake_sources.py — emit the per-target source list a CMake build must compile.

A glob (``src/shared/*.c``) over-includes: a shared tree holds every
target's TUs, and a target must compile only the files carrying its own
``// FUNCTION: <marker>`` block — a GOLD-only TU linked into server.dll
is a composition break (duplicate symbols at best, foreign bytes at
worst).  ``rebrew cmake-sources`` partitions the tree by marker and writes
a CMake include setting ``<VAR>`` to exactly that target's files:

    execute_process(COMMAND ${REBREW} cmake-sources -o ${CMAKE_BINARY_DIR}/rebrew-sources.cmake)
    include(${CMAKE_BINARY_DIR}/rebrew-sources.cmake)
    add_library(server_dll SHARED ${REBREW_SOURCES})

``--var`` renames the variable (default ``REBREW_SOURCES``); ``--target``
picks the marker (default: current target).  Unannotated ``.c`` files
(helpers with no FUNCTION block, e.g. crt link shims) are included —
they belong to every target that globs them, same as before.
"""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console

from rebrew.annotation import parse_c_file_multi
from rebrew.cli import (
    TargetOption,
    json_print,
    require_config,
)
from rebrew.config import ProjectConfig
from rebrew.sources import iter_sources, target_marker
from rebrew.utils import atomic_write_text, read_source_text

app = typer.Typer(add_completion=False, help=__doc__)
console = Console(stderr=True)

HEADER = """# Per-target sources from rebrew annotations.
# Generated by `rebrew cmake-sources` — do not hand-edit; re-run after
# adding, moving, or re-marking sources.
#
# A file belongs to a target when it carries that target's FUNCTION/LIBRARY/
# STUB marker — or a `// SUPPORT: <marker>` line (link scaffolding with no
# VA markers by design).  Unannotated .c files are listed for every target.
# External `.lib` archives (targets.<name>.external_libs) are listed as
# REBREW_EXTERNAL_LIBS for target_link_libraries — the stock library links
# at build time instead of reversed copies.
"""


def collect(cfg: ProjectConfig, marker: str) -> tuple[list[Path], list[Path]]:
    """``(own, foreign)`` absolute source paths for *marker*.

    *own* holds files with at least one marker block for *marker*, files
    declaring ``// SUPPORT: <marker>`` (link scaffolding with no VA
    markers by design), plus all unannotated ``.c`` files; *foreign*
    holds annotated files with no block for *marker* (reported so the
    caller can confirm the exclusion).
    """
    from rebrew.lint import _support_declaration

    own: list[Path] = []
    foreign: list[Path] = []
    for src in iter_sources(cfg.reversed_dir, cfg):
        anns = [a for a in parse_c_file_multi(src, metadata_dir=cfg.metadata_dir) if a.va]
        if not anns:
            try:
                # read_source_text, not Path.read_text: the latter decodes
                # with the locale encoding, so under LANG=C a cp1252 or
                # Shift-JIS TU loses its SUPPORT line to U+FFFD and the file
                # silently lands in the wrong target's source list.
                support = _support_declaration(read_source_text(src)[0].splitlines())
            except OSError:
                support = None
            if support is not None and support[1].upper() == marker.upper():
                own.append(src.resolve())
            elif support is not None:
                foreign.append(src.resolve())
            else:
                own.append(src.resolve())
            continue
        if any(a.module.upper() == marker.upper() for a in anns):
            own.append(src.resolve())
        else:
            foreign.append(src.resolve())
    return sorted(own), sorted(foreign)


@app.callback(invoke_without_command=True)
def main(
    output: Path = typer.Option(
        Path("build/rebrew-sources.cmake"), "--output", "-o", help="CMake include to write"
    ),
    var: str = typer.Option(
        "REBREW_SOURCES", "--var", help="CMake variable to set with the source list"
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Write the target's source list as a CMake include."""
    cfg = require_config(target=target, json_mode=json_output)
    marker = target_marker(cfg) or cfg.target_name
    own, foreign = collect(cfg, marker)

    rels = [p.relative_to(cfg.root).as_posix() for p in own]
    # Config order IS link order ("link it at the right place" — e.g. a
    # static LIBCMT last), so dedupe without sorting.
    external: list[str] = []
    for spec in (getattr(cfg, "external_libs", None) or {}).values():
        s = (spec or "").strip()
        if s and s not in external:
            external.append(s)
    lines = [HEADER]
    lines.append(f"set({var}\n")
    for rel in rels:
        lines.append(f'  "${{CMAKE_CURRENT_SOURCE_DIR}}/{rel}"\n')
    lines.append(")\n")
    if external:
        lines.append("\nset(REBREW_EXTERNAL_LIBS\n")
        for spec in external:
            lines.append(f'  "{spec}"\n')
        lines.append(")\n")
    text = "".join(lines)

    if not json_output and foreign and not dry_run:
        console.print(
            f"[dim]cmake-sources: {len(foreign)} file(s) carry no {marker} marker "
            f"and are excluded from the build[/dim]"
        )
    if dry_run:
        if not json_output:
            print(text)
    else:
        atomic_write_text(output, text)
    if json_output:
        json_print(
            {
                "target": cfg.target_name,
                "marker": marker,
                "variable": var,
                "written": None if dry_run else str(output),
                "files": rels,
                "external_libs": external,
                "excluded": [p.relative_to(cfg.root).as_posix() for p in foreign],
            }
        )
    elif not dry_run:
        console.print(f"[green]cmake-sources:[/green] wrote {output} ({len(rels)} source files)")


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_standalone

    run_standalone(main)


if __name__ == "__main__":
    main_entry()
