"""context — emit a universal C context file for the decompiler backends.

m2c's decompilation workflow feeds the decompiler a single "context" file of
types and prototypes (the ``find include/ src/ -name '*.h' > ctx_includes.c``
recipe), so decompiled output arrives with real struct/typedef/function names
instead of raw addresses.  Rebrew's decompiler backends (kuna, r2ghidra) and
the struct-recovery tooling benefit from the same file: every library header
and reversed source contributes its structs, typedefs, enums, and function
signatures, deduplicated into one compilable ``ctx.c``.

Usage:
    rebrew context --out ctx.c
    rebrew context -t mygame --out include/ctx.c

The output is a plain C translation unit of declarations (no bodies) —
safe to ``#include`` from a single-purpose TU or to paste into a
decompiler's context pane.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from rebrew.cli import TargetOption, require_config
from rebrew.signature_parser import extract_function_prototypes, extract_function_signatures
from rebrew.sources import iter_library_headers, iter_sources
from rebrew.struct_parser import (
    extract_enums_from_file,
    extract_structs_from_file,
    extract_type_definitions,
)
from rebrew.utils import atomic_write_text

console = Console(stderr=True)

app = typer.Typer(
    help="Emit a universal C context file (types + signatures) for decompiler backends.",
    rich_markup_mode="rich",
)


def _collect_context(cfg: Any, include_sources: bool = True) -> tuple[list[str], int]:
    """Collect deduplicated declaration blocks from headers (and sources).

    Returns ``(blocks, file_count)`` — *blocks* are source snippets (struct
    definitions, typedefs, enums, function prototypes), deduplicated by their
    text, in stable (path-sorted) order.
    """
    files = list(iter_library_headers(cfg.reversed_dir))
    if include_sources:
        files += list(iter_sources(cfg.reversed_dir, cfg))
    seen: set[str] = set()
    blocks: list[str] = []
    for path in files:
        try:
            candidates = (
                list(extract_structs_from_file(path))
                + list(extract_type_definitions(path))
                + list(extract_enums_from_file(path))
                + [f"{sig};" for sig, _ in extract_function_signatures(path)]
                + [f"{sig};" for sig in extract_function_prototypes(path)]
            )
        except (OSError, ValueError, UnicodeDecodeError):
            continue
        for block in candidates:
            block = block.strip()
            if not block or block in seen:
                continue
            seen.add(block)
            blocks.append(block)
    return blocks, len(files)


@app.callback(invoke_without_command=True)
def main(
    out: Path = typer.Option(Path("ctx.c"), "--out", help="Output context file path"),
    sources_only: bool = typer.Option(
        False,
        "--sources-only",
        help="Include only reversed sources, not library headers",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Write the deduplicated context to *out*."""
    cfg = require_config(target=target, json_mode=json_output)
    blocks, file_count = _collect_context(cfg, include_sources=not sources_only)

    header = (
        "/* ctx.c - AUTO-GENERATED by `rebrew context`.\n"
        " * Universal decompiler context: structs, typedefs, enums, and\n"
        " * function signatures collected from the project's headers and\n"
        " * reversed sources, deduplicated.  Feed this to a decompiler\n"
        " * backend (kuna/r2ghidra context) or include it from a stub TU.\n"
        " * DO NOT hand-edit; regenerate with `rebrew context`.\n"
        " */\n"
    )
    text = header + "\n\n".join(blocks) + ("\n" if blocks else "")
    atomic_write_text(out, text, encoding="utf-8")

    if json_output:
        from rebrew.cli import json_print

        json_print(
            {
                "out": str(out),
                "files": file_count,
                "blocks": len(blocks),
            }
        )
        return
    console.print(
        f"[green]Wrote {len(blocks)} declaration block(s) from {file_count} file(s) to {out}[/green]"
    )


def main_entry() -> None:
    """Run the Typer CLI application.

    The callback is registered as a plain command on a fresh app: the
    group-style ``invoke_without_command`` callback fails to parse
    positional-then-option invocations (``rebrew-<cmd> ARG --opt`` — click
    treats the positional as a command name), while the umbrella's command
    registration parses both orderings (cli-review F1).
    """
    _standalone = typer.Typer()
    _standalone.command()(main)
    _standalone()


if __name__ == "__main__":
    main_entry()
