"""context — emit a universal C context file for the decompiler backends.

m2c's decompilation workflow feeds the decompiler a single "context" file of
types and prototypes (the ``find include/ src/ -name '*.h' > ctx_includes.c``
recipe), so decompiled output arrives with real struct/typedef/function names
instead of raw addresses.  Rebrew's decompiler backends (kuna, r2ghidra) and
the struct-recovery tooling benefit from the same file: every library header
and reversed source contributes its structs, typedefs, enums, and function
signatures, deduplicated into one compilable ``ctx.c``.

Usage:
    rebrew context --out ctx.c
    rebrew context -t mygame --out include/ctx.c

The output is a plain C translation unit of declarations (no bodies) —
safe to ``#include`` from a single-purpose TU or to paste into a
decompiler's context pane.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from rebrew.cli import TargetOption, require_config
from rebrew.signature_parser import extract_function_prototypes, extract_function_signatures
from rebrew.sources import iter_library_headers, iter_sources
from rebrew.struct_parser import (
    extract_enums_from_file,
    extract_structs_from_file,
    extract_type_definitions,
)
from rebrew.utils import atomic_write_text

console = Console(stderr=True)

#: Name a compile unit gives the context's declarations when they are merged
#: into the source (``compile.contextualized_source``), and the name the
#: generated document gives itself.  One constant, so the two cannot drift.
CONTEXT_UNIT_NAME = "ctx.c"

#: Header the ``rebrew context`` document starts with.
_CONTEXT_HEADER = (
    f"/* {CONTEXT_UNIT_NAME} - AUTO-GENERATED by `rebrew context`.\n"
    " * Universal decompiler context: structs, typedefs, enums, and\n"
    " * function signatures collected from the project's headers and\n"
    " * reversed sources, deduplicated.  Feed this to a decompiler\n"
    " * backend (kuna/r2ghidra context) or include it from a stub TU.\n"
    " * DO NOT hand-edit; regenerate with `rebrew context`.\n"
    " */\n"
)


@dataclass(frozen=True)
class CompileContext:
    """The project-supplied types/prototypes a compile is pinned to.

    Attributes:
        path: File the context was read from.
        text: Exact text the compile prepends (empty means "no declarations",
            which leaves the compile unit and its cache key unchanged).
        sha256: Hex digest of ``text`` encoded UTF-8.  Recorded beside a
            compile verdict so a stored result names the context it was
            earned under; a changed digest is a different compile input, not
            a still-valid match.
    """

    path: Path
    text: str
    sha256: str


def context_sha256(text: str) -> str:
    """SHA-256 hex digest of a context document (UTF-8)."""
    return hashlib.sha256(text.encode("utf-8", errors="surrogateescape")).hexdigest()


def load_compile_context(path: Path | None) -> CompileContext | None:
    """Read *path* as the compile context, or return ``None``.

    ``None`` only when *path* is ``None`` (no context asked for).  A file
    that exists but holds nothing yields a :class:`CompileContext` with an
    empty ``text``: its digest still pins "a context was supplied and it was
    empty", while the compile unit stays byte-identical to the bare source.

    Raises:
        FileNotFoundError: the named file does not exist.  An explicit
            ``--context`` that points nowhere must fail loud rather than
            silently compile without the context the user asked for.
    """
    if path is None:
        return None
    text = path.read_text(encoding="utf-8", errors="surrogateescape")
    return CompileContext(path=path, text=text, sha256=context_sha256(text))


def render_context_text(blocks: list[str]) -> str:
    """The ``rebrew context`` document for already-collected *blocks*.

    Single producer of the document text: the CLI writes it, and a caller
    that needs the project's context to hash or to compile against gets
    byte-identical content.
    """
    return _CONTEXT_HEADER + "\n\n".join(blocks) + ("\n" if blocks else "")


def collect_context_text(cfg: Any, sources_only: bool = False) -> str:
    """Collect *cfg*'s declarations and render the ``rebrew context`` document."""
    blocks, _file_count = _collect_context(cfg, include_headers=not sources_only)
    return render_context_text(blocks)


app = typer.Typer(
    help="Emit a universal C context file (types + signatures) for decompiler backends.",
    rich_markup_mode="rich",
)


def _collect_context(
    cfg: Any, include_sources: bool = True, include_headers: bool = True
) -> tuple[list[str], int]:
    """Collect deduplicated declaration blocks from headers (and sources).

    Returns ``(blocks, file_count)`` — *blocks* are source snippets (struct
    definitions, typedefs, enums, function prototypes), deduplicated by their
    text, in stable (path-sorted) order.

    ``--sources-only`` is ``(include_sources=True, include_headers=False)``;
    gating only *sources* left the headers in, so no flag combination could
    produce a sources-only file.
    """
    files: list[Path] = []
    if include_headers:
        files += list(iter_library_headers(cfg.reversed_dir, cfg))
    if include_sources:
        files += list(iter_sources(cfg.reversed_dir, cfg))
    seen: set[str] = set()
    blocks: list[str] = []
    for path in files:
        try:
            candidates = (
                list(extract_structs_from_file(path))
                + list(extract_type_definitions(path))
                + list(extract_enums_from_file(path))
                + [f"{sig};" for sig, _ in extract_function_signatures(path)]
                + [f"{sig};" for sig in extract_function_prototypes(path)]
            )
        except (OSError, ValueError, UnicodeDecodeError):
            continue
        for block in candidates:
            block = block.strip()
            if not block or block in seen:
                continue
            seen.add(block)
            blocks.append(block)
    return blocks, len(files)


@app.callback(invoke_without_command=True)
def main(
    output: Path = typer.Option(Path("ctx.c"), "--output", "-o", help="Output context file path"),
    sources_only: bool = typer.Option(
        False,
        "--sources-only",
        help="Include only reversed sources, not library headers",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Write the deduplicated context to *out*."""
    cfg = require_config(target=target, json_mode=json_output)
    blocks, file_count = _collect_context(cfg, include_headers=not sources_only)
    text = render_context_text(blocks)
    atomic_write_text(output, text, encoding="utf-8")

    if json_output:
        from rebrew.cli import json_print

        json_print(
            {
                "output": str(output),
                "files": file_count,
                "blocks": len(blocks),
            }
        )
        return
    console.print(
        f"[green]Wrote {len(blocks)} declaration block(s) from {file_count} file(s) to {output}[/green]"
    )


def main_entry() -> None:
    """Run the Typer CLI application.

    The callback is registered as a plain command on a fresh app: the
    group-style ``invoke_without_command`` callback fails to parse
    positional-then-option invocations (``rebrew-<cmd> ARG --opt`` — click
    treats the positional as a command name), while the umbrella's command
    registration parses both orderings (cli-review F1).
    """
    _standalone = typer.Typer()
    _standalone.command()(main)
    _standalone()


if __name__ == "__main__":
    main_entry()
