"""coverage_toml.py – clear-text TOML coverage output for a catalog snapshot.

The normalizers live in :mod:`rebrew.build_db`, which computed every value in
pure Python before the SQLite writer it also held bound it to a column.  This
module imports those normalizers rather than restating them, so the document and
the catalog snapshot cannot report different facts about the same
the in-process catalog dict — a second implementation of the cell clamp or the status
sanitizer is exactly the drift this file exists to remove.

Only facts are stored.  The removed ``build_db`` materialized per-section
buckets, the per-section cell JSON and the ``summary`` blob because a SQL reader
wanted them cheaply; a TOML reader re-derives every one of them from ``sections``
+ ``cells``, and a stored copy is a second place for the two writers to disagree.

Two consequences of writing TOML are load-bearing and stated once here:

* **TOML has no null.**  ``None`` is written as ``""``, so a reader cannot tell
  a NULL column from an empty one.  Every NULL in this schema is an optional
  field (``label``, ``parent_function``, a section's ``va``/``fileOffset``, a
  function's ``size``/``similarity``), and every consumer of those fields
  already treats missing and empty alike.
* **A bare key belongs to the table above it.**  The bulk arrays are therefore
  written BEFORE the first ``[table]`` header, so they land at the document top
  level; written after ``[sections."…"]`` they would silently nest inside the
  last section instead of beside it.
"""

import contextlib
import json
import logging
import threading
import tomllib
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from types import MappingProxyType
from typing import Any

from rebrew.annotation import FUNCTION_MARKERS, VALID_MARKERS
from rebrew.build_db import (
    DEFAULT_GRID_GEOMETRY,
    FUNCTION_DB_STATUSES,
    GLOBAL_DB_STATUSES,
    HISTORY_RETENTION,
    clamp_nonneg_int,
    clamp_unit_interval,
    dedupe_by_va,
    dedupe_cell_rows,
    import_verify_rows,
    load_coverage_datasets,
    normalize_cell_row,
    parse_int,
    positive_int_or,
    resolve_db_dir,
)
from rebrew.cli import console
from rebrew.errors import RebrewError
from rebrew.metadata import canonical_status
from rebrew.utils import atomic_write_text, clip_span, file_lock, floor_pct, toml_safe
from rebrew.workspace import WorkspaceConfigError, db_dir
from rebrew.workspace.status import MATCHED_STATUSES

log = logging.getLogger(__name__)

#: What ``import *`` from this module means.  Everything else below is
#: build_db's helper borrowed for reuse, not this module's to re-export.
__all__ = [
    "Cell",
    "CoverageSnapshot",
    "CoverageTomlError",
    "Function",
    "Global",
    "Section",
    "load_all_coverage",
    "load_all_coverage_from",
    "load_coverage",
    "load_coverage_from",
    "render_coverage_toml",
    "write_coverage_toml",
]

#: Schema version stamped as the top-level ``version``.  A previous file
#: carrying anything else is not migrated: its history and verify rows are read
#: by these key names, and a foreign layout would be guessed at rather than
#: understood.  An unreadable or absent file is the same case (empty history),
#: which is what replaces ``build_db``'s version-check / unlink / ``--force``
#: dance — there is no sidecar to reset and no partial state to recover.
_TOML_VERSION = 1

#: Pointer-size fallback for a global whose JSON carries a non-int or missing
#: ``size``.  The removed SQLite writer used the same literal, so a document
#: built before the move keeps the size it already reported.
_GLOBAL_DEFAULT_SIZE = 4

#: Emitted as the file's first line.  No timestamp: a rebuild of unchanged
#: input has to be byte-identical, and a generation stamp is the one field that
#: would move on every run.
_HEADER = (
    "# Generated by rebrew's coverage TOML writer from the project tree.\n"
    "# Rebuilt wholesale on every run: edit the annotations, not this file.\n"
)

#: ``cells``/``functions``/``globals`` rows, as inline tables inside one array.
#: Measured on this project: 100k inline-table rows in a single array parse in
#: 0.81 s under ``tomllib``, against minutes for the array-of-tables
#: (``[[cells]]``) form of the same 100k rows.  One row per line keeps the file
#: diffable without giving that up — a newline between array elements costs
#: nothing, an extra table header per row costs everything.
_ROW_INDENT = "  "

#: One normalized cell row, as the file stores it.  ``normalize_cell_row``
#: returns ``(target, section_name, start, end, span, state, functions_json,
#: label, parent_function)``; the file drops ``target`` (one file, one target)
#: and renames ``section_name`` to ``section`` because the reader concatenates
#: every section's cells into one flat list.
_CELL_COLUMNS: tuple[str, ...] = (
    "section",
    "start",
    "end",
    "span",
    "state",
    "functions",
    "label",
    "parent_function",
)

#: The removed SQLite writer's ``cells`` column list, less ``target``: the
#: file's row shape is the shape that writer produced, so an old document and
#: a new one diff against each other instead of being trusted.
_SECTION_COLUMNS: tuple[str, ...] = ("va", "size", "fileOffset", "unitBytes", "columns")

#: ``build_db``'s ``functions`` INSERT column list, less ``target``, in the
#: INSERT's order.  The list is the parity contract: a column added to the
#: database and not here shows up as a missing key, not as a silent omission.
_FUNCTION_COLUMNS: tuple[str, ...] = (
    "va",
    "name",
    "vaStart",
    "size",
    "fileOffset",
    "status",
    "module",
    "cflags",
    "symbol",
    "markerType",
    "ghidra_name",
    "list_name",
    "is_thunk",
    "is_export",
    "sha256",
    "files",
    "detected_by",
    "size_by_tool",
    "textOffset",
    "blocker",
    "blockerDelta",
    "size_reason",
    "similarity",
    "updated_by",
    "updated_at",
)

#: ``build_db``'s ``globals`` INSERT column list, less ``target``.
_GLOBAL_COLUMNS: tuple[str, ...] = ("va", "name", "decl", "files", "module", "size", "status")

#: The removed SQLite writer's ``history`` column list, less ``target`` and
#: less the ``id`` the file's array position already carries.  A history row
#: names its function by VA only; the reader joins the current name, so a row
#: that named a function the transition retired still reads.
_HISTORY_COLUMNS: tuple[str, ...] = (
    "va",
    "old_status",
    "new_status",
    "changed_at",
    "updated_by",
)

#: Columns ``build_db`` stores as a JSON *string* and this file stores as the
#: real TOML value.  They are decoded, not re-derived from ``data``: the
#: normalizer already decided what the field holds (a non-list ``functions``
#: becomes ``[]``, a missing ``size_by_tool`` becomes ``{}``), so decoding the
#: stored spelling is what keeps the two writers from disagreeing.
_JSON_COLUMNS: frozenset[str] = frozenset({"functions", "files", "detected_by", "size_by_tool"})

#: ``build_db``'s ``verify_results`` columns, less ``target``, in the INSERT's
#: order — which is also the order :func:`rebrew.build_db.import_verify_rows`
#: returns its rows in, so the two are one list read from both ends.
_VERIFY_RESULTS_COLUMNS: tuple[str, ...] = (
    "va",
    "verified_at",
    "byte_delta",
    "diff_lines",
    "similarity",
    "reg_delta",
    "effective_match",
)

#: A bare TOML key is these characters only; anything else (``.text``, a
#: section name with a dot or a space) has to be quoted or the document fails
#: to parse.
_BARE_KEY_CHARS = frozenset("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-")


# ---------------------------------------------------------------------------
# TOML value emission
# ---------------------------------------------------------------------------


def _string(value: str) -> str:
    """Render a TOML basic string.

    ``json.dumps`` with the default ``ensure_ascii=True`` is a TOML basic
    string: its escapes (``\\"``, ``\\\\``, ``\\b``, ``\\f``, ``\\n``, ``\\r``,
    ``\\t``, ``\\uXXXX``) are exactly TOML's, and every remaining code point
    either passes through or is escaped to one.  A dedicated escaper would be a
    second, separately-tested answer to the same question.

    :func:`rebrew.utils.toml_safe` runs first because JSON escapes a lone
    surrogate (U+DC80-U+DCFF, what ``read_compile_source`` yields for a
    cp1252 or Shift-JIS byte) as ``\\udc80``, which TOML has no escape for:
    the document is written and then rejected by every reader, losing the whole
    coverage file rather than the one bad name.
    """
    return json.dumps(toml_safe(value))


def _key(name: str) -> str:
    """Render a TOML key, bare when it can be and quoted when it cannot."""
    if name and all(ch in _BARE_KEY_CHARS for ch in name):
        return name
    return _string(name)


def _value(value: Any) -> str:
    """Render a Python value as a TOML value.

    ``None`` becomes ``""`` (see the module docstring: TOML has no null), a
    list becomes a real array, and a dict becomes a real inline table — this
    writer never emits an array-of-tables for bulk rows.
    """
    if value is None:
        return '""'
    if isinstance(value, bool):
        # Before the int branch: bool is an int subclass.
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        # repr of a Python float is always a TOML float: it carries a '.' or an
        # exponent, or it is one of the three special values, all of which TOML
        # spells the same way Python does.
        return repr(value)
    if isinstance(value, str):
        return _string(value)
    if isinstance(value, list | tuple):
        return "[" + ", ".join(_value(item) for item in value) + "]"
    if isinstance(value, dict):
        body = ", ".join(f"{_key(str(k))} = {_value(v)}" for k, v in value.items())
        return "{" + body + "}"
    raise TypeError(f"coverage_toml: no TOML encoding for {type(value).__name__}")


def _kv(key: str, value: Any) -> str:
    """Render one ``key = value`` line: a scalar, or a whole inline table."""
    return f"{_key(key)} = {_value(value)}"


def _kv_block(key: str, rows: Sequence[Any]) -> list[str]:
    """Render a bulk table: one array of inline tables, one row per line."""
    if not rows:
        return [f"{_key(key)} = []"]
    lines = [f"{_key(key)} = ["]
    lines.extend(f"{_ROW_INDENT}{_value(row)}," for row in rows)
    lines.append("]")
    return lines


def _rows_from(columns: tuple[str, ...], row: tuple[Any, ...]) -> dict[str, Any]:
    """Name a positional row's values after *columns*, decoding JSON columns.

    ``row`` is one entry of the list ``build_db`` hands ``executemany``; its
    first element (``target``) is dropped because the file is per-target.
    """
    out = dict(zip(columns, row[1:], strict=True))
    for name in _JSON_COLUMNS:
        if name in out:
            out[name] = json.loads(out[name])
    return out


def _row_va(row: tuple[Any, ...]) -> Any:
    """Sort key for a ``functions``/``globals`` row: its VA (column index 1)."""
    return row[1]


# ---------------------------------------------------------------------------
# Row builders — the field mapping the SQLite writer used, field for field
# ---------------------------------------------------------------------------


def _function_rows(target_name: str, data: dict[str, Any]) -> list[tuple[Any, ...]]:
    """Build the ``functions`` rows, skipping rows with no parseable VA.

    Field-for-field the row the removed SQLite writer inserted, so a document
    written before the move reads the same as one written after it.  The clamps
    exist because that writer's CHECK constraints rejected a whole rebuild on
    one stray negative or bool; a text file has no CHECKs, so they are kept to
    hold the two spellings of the same catalog value together rather than
    because the TOML needs them.
    """
    rows: list[tuple[Any, ...]] = []
    bad_va = 0
    for va, fn in data.get("functions", {}).items():
        if not isinstance(fn, dict):
            bad_va += 1
            continue
        # -1, not 0, marks "unparseable": VA 0 is a real address on 16-bit
        # targets.
        va_int = parse_int(va, -1)
        if va_int < 0:
            va_int = parse_int(fn.get("vaStart"), -1)
        if va_int < 0:
            bad_va += 1
            continue

        va_start_text = str(fn.get("vaStart") or f"0x{va_int:08x}")
        # bool is an int subclass, so True would land as size=1.
        fn_size = fn.get("size")
        if isinstance(fn_size, bool) or (fn_size is not None and not isinstance(fn_size, int)):
            fn_size = None
        elif isinstance(fn_size, int) and fn_size < 0:
            fn_size = 0
        file_off = fn.get("fileOffset")
        if isinstance(file_off, bool) or (file_off is not None and not isinstance(file_off, int)):
            file_off = None
        elif isinstance(file_off, int) and file_off < 0:
            file_off = 0
        text_off = fn.get("textOffset")
        if isinstance(text_off, bool) or (text_off is not None and not isinstance(text_off, int)):
            text_off = None
        elif isinstance(text_off, int) and text_off < 0:
            text_off = 0
        blocker_delta = fn.get("blockerDelta")
        if isinstance(blocker_delta, bool) or (
            blocker_delta is not None and not isinstance(blocker_delta, int)
        ):
            blocker_delta = None
        elif isinstance(blocker_delta, int) and blocker_delta < 0:
            blocker_delta = 0
        fn_marker = str(fn.get("markerType") or "FUNCTION")
        if fn_marker not in VALID_MARKERS:
            fn_marker = "FUNCTION"
        fn_status = canonical_status(str(fn.get("status") or "UNKNOWN"))
        if fn_status not in FUNCTION_DB_STATUSES:
            fn_status = "UNKNOWN"
        rows.append(
            (
                target_name,
                va_int,
                str(fn.get("name") or ""),
                va_start_text,
                fn_size,
                file_off,
                fn_status,
                str(fn.get("module") or fn.get("origin") or ""),
                fn.get("cflags"),
                fn.get("symbol"),
                fn_marker,
                fn.get("ghidra_name"),
                fn.get("list_name"),
                int(bool(fn.get("is_thunk", False))),
                int(bool(fn.get("is_export", False))),
                fn.get("sha256"),
                json.dumps(fn.get("files", [])),
                json.dumps(fn.get("detected_by", [])),
                json.dumps(fn.get("size_by_tool", {})),
                text_off,
                fn.get("blocker", ""),
                blocker_delta,
                fn.get("size_reason", ""),
                clamp_unit_interval(fn.get("similarity")),
                str(fn.get("updated_by") or ""),
                str(fn.get("updated_at") or ""),
            )
        )
    if bad_va:
        console.print(
            f"[yellow]warning:[/yellow] {target_name}: skipped {bad_va} "
            "function row(s) with unparseable VA (no valid key or vaStart)"
        )
    return rows


def _global_rows(target_name: str, data: dict[str, Any]) -> list[tuple[Any, ...]]:
    """Build the ``globals`` rows, skipping rows with no parseable VA.

    Field-for-field the row the removed SQLite writer inserted; see
    :func:`_function_rows` for why the clamps stay.
    """
    rows: list[tuple[Any, ...]] = []
    bad_va = 0
    for va, g in data.get("globals", {}).items():
        if not isinstance(g, dict):
            bad_va += 1
            continue
        # -1, not 0: 16-bit targets place data at segment 0.
        va_int = parse_int(va, -1)
        if va_int < 0:
            va_int = parse_int(g.get("va"), -1)
        if va_int < 0:
            bad_va += 1
            continue
        g_size = g.get("size")
        if isinstance(g_size, bool) or not isinstance(g_size, int):
            g_size = _GLOBAL_DEFAULT_SIZE
        elif g_size < 0:
            g_size = 0
        g_status = str(g.get("status") or "").strip().upper()
        if g_status not in GLOBAL_DB_STATUSES:
            g_status = ""
        rows.append(
            (
                target_name,
                va_int,
                str(g.get("name") or ""),
                str(g.get("decl") or ""),
                json.dumps(g.get("files", [])),
                str(g.get("module") or g.get("origin") or ""),
                g_size,
                g_status,
            )
        )
    if bad_va:
        console.print(
            f"[yellow]warning:[/yellow] {target_name}: skipped "
            f"{bad_va} global row(s) with unparseable VA "
            "(no valid key or va field)"
        )
    return rows


def _section_table(sec_name: str, sec: dict[str, Any]) -> list[str]:
    """Render one ``[sections."<name>"]`` table: the scalars, then the cells.

    The section's name is the table's key, not a field inside it, so the five
    scalars here are the ``sections`` row's other columns.
    """
    values = (
        clamp_nonneg_int(sec.get("va")),
        clamp_nonneg_int(sec.get("size")),
        clamp_nonneg_int(sec.get("fileOffset")),
        # The same fallback the sections row uses: a hand-edited 0 aborts the
        # SQLite rebuild and renders a zero-width grid here.
        positive_int_or(sec.get("unitBytes"), DEFAULT_GRID_GEOMETRY),
        positive_int_or(sec.get("columns"), DEFAULT_GRID_GEOMETRY),
    )
    lines = [f"[sections.{_key(sec_name)}]"]
    lines.extend(_kv(name, value) for name, value in zip(_SECTION_COLUMNS, values, strict=True))
    cell_rows = dedupe_cell_rows(
        [
            normalize_cell_row("", sec_name, cell)
            for cell in sec.get("cells", [])
            if isinstance(cell, dict)
        ],
        target_name=sec_name,
        sec_name=sec_name,
    )
    lines.extend(_kv_block("cells", [_rows_from(_CELL_COLUMNS, r) for r in cell_rows]))
    return lines


def _merge_history(
    previous_functions: Any, previous_history: Any, fn_rows: Sequence[tuple[Any, ...]]
) -> list[dict[str, Any]]:
    """Carry previous history forward and append this build's status deltas.

    The old writer snapshotted the statuses already stored, appended one row
    per change, and kept the newest ``HISTORY_RETENTION`` per target.  Here
    the previous file's ``functions`` array is that snapshot and its ``history``
    array is the table, so the same three steps give the same answer without a
    transaction.
    """
    old_statuses: dict[Any, Any] = {}
    if isinstance(previous_functions, list):
        old_statuses = {
            row["va"]: row["status"]
            for row in previous_functions
            if isinstance(row, dict) and isinstance(row.get("va"), int)
        }
    carried: list[dict[str, Any]] = (
        [dict(row) for row in previous_history if isinstance(row, dict)]
        if isinstance(previous_history, list)
        else []
    )

    now_iso = datetime.now(UTC).isoformat()
    for row in fn_rows:
        new_va, new_status, updated_by = row[1], row[6], row[24]
        old_status = old_statuses.get(new_va)
        if old_status is not None and old_status != new_status:
            old_s = canonical_status(str(old_status or "UNKNOWN"))
            if old_s not in FUNCTION_DB_STATUSES:
                old_s = "UNKNOWN"
            new_s = canonical_status(str(new_status or "UNKNOWN"))
            if new_s not in FUNCTION_DB_STATUSES:
                new_s = "UNKNOWN"
            carried.append(
                {
                    "va": max(0, parse_int(new_va, 0)),
                    "old_status": old_s,
                    "new_status": new_s,
                    "changed_at": now_iso,
                    "updated_by": updated_by or "",
                }
            )
    # Retention: the newest HISTORY_RETENTION rows.  ``sorted`` is stable, so
    # two rows sharing a changed_at keep write order and the file stays
    # byte-identical across runs that changed nothing.
    carried.sort(key=lambda r: str(r.get("changed_at", "")))
    return carried[-HISTORY_RETENTION:]


# ---------------------------------------------------------------------------
# Persistence across rebuilds
# ---------------------------------------------------------------------------


def _measurement(value: Any) -> Any:
    """A stored measurement as a freshly built row spells it.

    TOML has no null: the writer stores an absent ``byte_delta`` as ``""``.  A
    freshly clamped row spells it ``None``, and the two must compare equal or
    every rebuild would read an unchanged verdict as a changed one and restamp
    it.  No measurement is ever a real empty string, so the fold is unambiguous.
    """
    return None if value == "" else value


def _previous_measured(previous: dict[str, Any]) -> dict[int, tuple[Any, ...]]:
    """The previous document's ``verify_results`` as :func:`import_verify_rows` wants them.

    The removed SQLite writer read the same mapping from its own query over
    ``verify_results`` — each VA's five measurement fields beside the stamp it
    was measured at — because a row whose measurements did not move keeps its
    earlier ``verified_at``.  A TOML file holds both facts in its
    ``verify_results`` rows, so the mapping is rebuilt here instead of queried.
    """
    measured: dict[int, tuple[Any, ...]] = {}
    rows = previous.get("verify_results")
    if not isinstance(rows, list):
        return measured
    for row in rows:
        if not isinstance(row, dict):
            continue
        va = row.get("va")
        # bool is an int subclass, and either would key a row no fresh row can
        # match; the row is skipped rather than raising, because this reads a
        # hand-editable file.
        if isinstance(va, bool) or not isinstance(va, int):
            continue
        measured[va] = (
            tuple(_measurement(row.get(column)) for column in _VERIFY_RESULTS_COLUMNS[2:]),
            str(row.get("verified_at") or ""),
        )
    return measured


def _read_previous(path: Path) -> dict[str, Any]:
    """Read the previous document, or ``{}`` when there is nothing to read.

    Missing, unreadable and unparseable all collapse to ``{}``.  A document of
    the wrong *version* is still returned as-is: :func:`render_coverage_toml`
    is what rejects it, so the rule holds for every caller rather than only for
    the one that went through a file.
    """
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except (OSError, ValueError) as exc:
        # tomllib.TOMLDecodeError subclasses ValueError; a UnicodeDecodeError
        # does too.  A half-written file lands in the same place.  Warn, not
        # debug: the caller rebuilds from this and drops the whole history
        # array, so a silent ``{}`` resets every chart on the dashboard.
        log.warning(
            "coverage_toml: cannot read %s (%s); the rebuild carries no history",
            path,
            exc,
        )
        return {}


#: One thread lock per target name; the cross-process half is the ``flock`` in
#: :func:`_coverage_write_lock`.  Both dashboards regenerate from WSGI worker
#: threads, so an in-process lock is not optional.
_COVERAGE_WRITE_LOCKS: dict[str, threading.Lock] = {}
_COVERAGE_WRITE_LOCKS_LOCK = threading.Lock()


@contextlib.contextmanager
def _coverage_write_lock(root_dir: Path, target_name: str) -> Iterator[None]:
    """Hold the coverage read-modify-write lock for *target_name*.

    Same discipline as :func:`rebrew.verify_cache._verify_cache_write_lock`: a
    thread lock plus an advisory ``flock`` sidecar, so an in-process dashboard
    regen and a second process's ``build-db`` cannot interleave.  The sidecar
    lives under ``.rebrew/`` beside the verify cache's rather than in ``db/``,
    which holds the delivered documents and nothing else.

    Separate from the metadata write lock: the coverage document is derived
    output, rewritten whole from the catalog, and shares no file with
    ``rebrew-functions.toml`` or ``rebrew-data.toml``.
    """
    with _COVERAGE_WRITE_LOCKS_LOCK:
        lock = _COVERAGE_WRITE_LOCKS.get(target_name)
        if lock is None:
            lock = _COVERAGE_WRITE_LOCKS[target_name] = threading.Lock()
    with lock, file_lock(root_dir / ".rebrew" / f"coverage-{target_name}.toml.lock"):
        yield


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_coverage_toml(
    target_name: str,
    data: dict[str, Any],
    *,
    previous: dict[str, Any] | None = None,
    verify_rows: Sequence[tuple[Any, ...]] | None = None,
) -> str:
    """Return the whole TOML document for one target, as a string.

    *data* is one catalog snapshot as ``load_coverage_datasets`` returns it.
    *previous* is the prior document for the same target (see
    :func:`_read_previous`); its ``functions`` statuses are this build's
    history baseline and its ``history`` array is carried forward.  A document
    that is missing, unreadable or of another :data:`_TOML_VERSION` contributes
    no history — the replacement for ``build_db``'s version-check / unlink /
    ``--force`` dance, and the reason there is no sidecar here to reset.

    *verify_rows* is :func:`rebrew.build_db.import_verify_rows`'s answer, and it
    keeps that function's three states: ``None`` (the verify cache says nothing
    about this target) carries *previous*'s ``verify_results`` forward verbatim,
    ``[]`` writes none, and a list writes those rows.  Three states rather than
    a default because a cache that never mentioned the target is not evidence
    that the target's verdicts went away.

    Nothing is written and nothing is read, so the same call is what the tests,
    the writer and an in-memory check all use.
    """
    if previous is not None and previous.get("version") != _TOML_VERSION:
        # Same data loss as the unreadable-file case _read_previous logs, and
        # the rebuild below replaces the file, so it has to be said out loud.
        log.warning(
            "coverage_toml: prior document for %s carries version %r, not %r; "
            "the rebuild carries no history",
            target_name,
            previous.get("version"),
            _TOML_VERSION,
        )
    prev = previous if previous is not None and previous.get("version") == _TOML_VERSION else {}
    fn_rows = dedupe_by_va(
        _function_rows(target_name, data), target_name=target_name, table="function"
    )
    g_rows = dedupe_by_va(_global_rows(target_name, data), target_name=target_name, table="global")
    # VA order: a text file has no index, so its row order IS the order a
    # reader walks.  Sorting here means that order means something, instead of
    # inheriting the catalog's JSON key order, which is stable but arbitrary.
    fn_rows.sort(key=_row_va)
    g_rows.sort(key=_row_va)

    sections: dict[str, Any] = data.get("sections", {})
    if verify_rows is None:
        # Copied, not aliased: a caller that mutated the document it handed in
        # would otherwise change what the next render writes.
        previous_rows = prev.get("verify_results")
        verify_list: list[Any] = (
            [dict(row) for row in previous_rows if isinstance(row, dict)]
            if isinstance(previous_rows, list)
            else []
        )
    else:
        verify_list = [_rows_from(_VERIFY_RESULTS_COLUMNS, row) for row in verify_rows]
    history = _merge_history(prev.get("functions"), prev.get("history"), fn_rows)

    lines: list[str] = [_HEADER]
    lines.append(f"version = {_TOML_VERSION}")
    lines.append(_kv("target", target_name))
    # Bulk arrays first: a bare key after a table header belongs to THAT table.
    lines.extend(_kv_block("functions", [_rows_from(_FUNCTION_COLUMNS, r) for r in fn_rows]))
    lines.extend(_kv_block("globals", [_rows_from(_GLOBAL_COLUMNS, r) for r in g_rows]))
    lines.extend(_kv_block("verify_results", verify_list))
    lines.extend(_kv_block("history", history))
    lines.append("")
    lines.append("[metadata]")
    lines.append(_kv("paths", data.get("paths", {})))
    for sec_name, sec in sections.items():
        lines.append("")
        lines.extend(_section_table(sec_name, sec))
    return "\n".join(lines) + "\n"


def write_coverage_toml(
    root_dir: Path,
    *,
    target: str | None = None,
    force: bool = False,
    regen: bool = False,
    json_output: bool = False,
) -> list[Path]:
    """Write ``db/coverage-<target>.toml`` for each dataset; return the paths written.

    The catalog inputs and every normalization come from
    :func:`rebrew.build_db.load_coverage_datasets` and its helpers, so this
    writer and ``build_db`` answer the same questions the same way.  What it
    does not inherit is the SQLite-only ceremony: there is no schema version to
    check, no ``--force`` unlink of a previous file, and no sidecars to
    recover.

    *force* is accepted for signature symmetry with
    :func:`rebrew.build_db.build_db` and has no effect: a stale file is fully
    replaced on every write, so there is nothing to force past.  So is *regen*:
    the catalog analysis always runs in this process.

    Returns the paths written, in dataset order.  Writes nothing else — the
    caller reports.
    """
    db_directory = resolve_db_dir(root_dir, json_output=json_output)
    datasets = load_coverage_datasets(
        root_dir,
        db_directory,
        target=target,
        json_output=json_output,
        regen=regen,
    )
    written: list[Path] = []
    for target_name, data in datasets:
        path = db_directory / f"coverage-{target_name}.toml"
        # The whole read-modify-write holds one write lock per target, like the
        # other tool-owned stores.  atomic_write_text alone stops a torn file
        # but not a lost update: two builders for one target (the dashboard
        # regenerating while a manual `build-db` runs) each read the same
        # `previous`, each carry its own delta rows into `history`, and the
        # second replace drops the first's history and restamps
        # `verified_at` — a silent reset of every chart, invisible until the
        # retention window rolls the rows off.  The lock is per target, so
        # builds of different targets still run concurrently.
        with _coverage_write_lock(root_dir, target_name):
            previous = _read_previous(path)
            # The verify cache is read here, not inside render: render stays a
            # pure function of its arguments (see its docstring), and the
            # previous document is already in hand for it to read the "was
            # this measured identically before" mapping out of.
            verify_rows = import_verify_rows(
                root_dir,
                target_name,
                _previous_measured(previous),
                # Only the fallback stamp: a cache file whose mtime cannot be
                # read still has to be dateable, and the moment of this build
                # is the honest answer.
                datetime.now(UTC).isoformat(),
            )
            atomic_write_text(
                path,
                render_coverage_toml(target_name, data, previous=previous, verify_rows=verify_rows),
            )
        written.append(path)
    return written


# ---------------------------------------------------------------------------
# Reader — the one snapshot type both dashboards import
# ---------------------------------------------------------------------------
#
# The dashboards used to read ``coverage.db`` inside a read transaction, so a
# page never paired one build's cells with the next build's functions.  A frozen
# snapshot is that property in the type system: every collection is a tuple or a
# ``MappingProxyType``, so a caller cannot edit the value it was handed and the
# next caller sees the same thing.  Every aggregate the writer does not store
# (per-section buckets, byte coverage, the by-VA index) is computed here once,
# at load, and never by a consumer.


class CoverageTomlError(RebrewError):
    """A coverage TOML document is missing, malformed, or of another version."""


def _db_directory(root_dir: Path) -> Path:
    """The directory this reader globs, resolved without ever exiting.

    ``build_db.resolve_db_dir`` is the writer's resolver and calls typer's
    ``error_exit`` on a broken ``rebrew-project.toml``; that is right for a CLI
    and wrong here, because both dashboards call these readers inside a WSGI
    request and a ``SystemExit`` there takes the server down instead of
    answering one target with an error page.  ``rebrew.workspace.db_dir`` is the
    same path computation without the exit — the two share it, so they cannot
    disagree on where the file lives — and its one failure is converted into
    this module's own error type, which every caller already handles.
    """
    try:
        return db_dir(root_dir)
    except WorkspaceConfigError as exc:
        # read_config's message already names the file and says what is wrong
        # with it; re-adding the path would print it twice.
        raise CoverageTomlError(str(exc)) from exc


#: The one cell state a section's byte coverage excludes.  This is not a new
#: definition: it is recoverage's ``server.SECTION_STATS_SQL``
#: (``CASE WHEN state != 'none'``) and ``potato``'s, restated here because the
#: sentence has to survive the move off SQLite.
_UNCOVERED_CELL_STATE = "none"

#: Filename shape ``write_coverage_toml`` writes and this reader globs for.
_FILENAME_PREFIX = "coverage-"
_FILENAME_SUFFIX = ".toml"


@dataclass(frozen=True, slots=True)
class Cell:
    """One ``cells`` row.

    ``label`` and ``parent_function`` are the two optional columns build_db
    allows NULL; TOML spells NULL ``""``, so the reader hands back the empty
    string it stores rather than inventing a distinction the file cannot carry.
    """

    start: int
    end: int
    span: int
    state: str
    functions: tuple[str, ...]
    label: str
    parent_function: str

    @property
    def size(self) -> int:
        """Byte length of the span.  Derived, never stored (see the docstring)."""
        return self.end - self.start


@dataclass(frozen=True, slots=True)
class Section:
    """One ``[sections."…"]`` table plus everything derivable from its cells.

    ``buckets`` maps a cell state to the bytes it covers, so it sums to the
    section's cell bytes.  The names of the derived fields are this reader's
    own: nothing stores them, so nothing can disagree with them.
    """

    name: str
    #: Section VA, ``None`` when the catalog had none (``""`` in the file).
    va: int | None
    size: int
    #: File offset of the section's raw data, ``None`` when the catalog had
    #: none (``""`` in the file).  A ``.bss`` is uninitialised and has no file
    #: offset at all; the SQLite row stored NULL for it, and reading that NULL
    #: back as 0 is what let ``/asm`` and ``/bytes`` serve real bytes from the
    #: start of the file for a section that has none.  Absent and 0 are
    #: different answers here, so the file's `""` is not collapsed to 0.
    file_offset: int | None
    unit_bytes: int
    columns: int
    cells: tuple[Cell, ...]
    buckets: Mapping[str, int] = field(init=False)
    covered_bytes: int = field(init=False)
    coverage_pct: float = field(init=False)
    cell_count: int = field(init=False)
    bucket_counts: Mapping[str, int] = field(init=False)

    def __post_init__(self) -> None:
        # Computed here, not in the loader: a Section built by a test or by a
        # consumer carries the same numbers as one the reader built, so there is
        # no second formula to keep in step.
        buckets: dict[str, int] = {}
        for cell in self.cells:
            buckets[cell.state] = buckets.get(cell.state, 0) + cell.size
        total = sum(buckets.values())
        covered = total - buckets.get(_UNCOVERED_CELL_STATE, 0)
        object.__setattr__(self, "buckets", MappingProxyType(buckets))
        object.__setattr__(self, "covered_bytes", covered)
        # Floored, like every other coverage figure in the codebase: to
        # nearest, one unaccounted byte in a 100000-byte section reads 100.0%
        # here while ``catalog.grid`` beside it says 99.99.  An empty section
        # (a target with no cells for it) reports 0.0 instead of dividing by
        # zero.
        object.__setattr__(self, "coverage_pct", floor_pct(covered, total, 2))
        object.__setattr__(self, "cell_count", len(self.cells))
        object.__setattr__(self, "bucket_counts", MappingProxyType(_bucket_counts(self.cells)))


#: What :func:`_bucket_counts` collapses each stored state into.  The database
#: computed these with recoverage's ``server.SECTION_STATS_SQL`` CASE sums; this
#: is that SELECT's rule, restated once because both dashboards serve the counts
#: and a second copy would be a second answer.  ``verified`` is an exact match,
#: ``near_matching`` is the near-match bucket, and a state with no name of its
#: own lands in ``other``.
_BUCKET_OF_STATE: Mapping[str, str] = MappingProxyType(
    {
        "exact": "exact",
        "verified": "exact",
        "reloc": "reloc",
        "near_match": "near_match",
        "near_matching": "near_match",
        "stub": "stub",
        "padding": "padding",
        "data": "data",
        "thunk": "thunk",
        "none": "none",
        "proven": "proven",
        "size_mismatch": "size_mismatch",
    }
)

#: Every key :func:`_bucket_counts` emits, in the order the served dicts use.
_BUCKET_KEYS: tuple[str, ...] = (
    "total_cells",
    "exact",
    "reloc",
    "near_match",
    "stub",
    "padding",
    "data",
    "thunk",
    "none",
    "proven",
    "size_mismatch",
    "other",
)


def _bucket_counts(cells: tuple[Cell, ...]) -> dict[str, int]:
    """Cell COUNTS per served bucket, including the ``other`` catch-all.

    ``other`` is what makes ``total_cells`` equal the sum of the counted
    buckets: rebrew stores verdict states the named buckets do not cover
    (``compile_error``, ``unknown``, the data drift/unchecked verdicts), and a
    section holding one of those undercounts without it.  The database computed
    the same number in SQL, so this is that expression rather than a new rule.
    """
    counts = dict.fromkeys(_BUCKET_KEYS, 0)
    counts["total_cells"] = len(cells)
    for cell in cells:
        counts[_BUCKET_OF_STATE.get(cell.state, "other")] += 1
    return counts


@dataclass(frozen=True, slots=True)
class Function:
    """One ``functions`` row, one field per ``_FUNCTION_COLUMNS`` entry.

    The field names are the file's own key names, camelCase included, so this
    class and that tuple are the same list twice: ``tuple(Function.__slots__) ==
    _FUNCTION_COLUMNS`` is asserted by the tests, which makes a column added,
    dropped or renamed in the writer a reader failure instead of a silent
    omission.  A Python-style rename would be a third spelling of the schema to
    keep in step with the writer's and build_db's.

    ``None`` marks a column build_db allows NULL where NULL means something the
    empty string cannot say: an unknown size is not size 0.  Text columns keep
    ``""``, which is what the writer stores and what every consumer of those
    fields already treats as absent.
    """

    va: int
    name: str
    vaStart: str
    size: int | None
    fileOffset: int | None
    status: str
    module: str
    #: ``build_db`` stores this column without normalizing it, so a catalog may
    #: hand it a string or a list; the reader passes through whatever was
    #: written (frozen) rather than picking one of the two shapes.
    cflags: Any
    symbol: str
    markerType: str
    ghidra_name: str
    list_name: str
    is_thunk: int
    is_export: int
    sha256: str
    files: tuple[str, ...]
    detected_by: tuple[str, ...]
    size_by_tool: Mapping[str, Any]
    textOffset: int | None
    blocker: str
    blockerDelta: int | None
    size_reason: str
    similarity: float | None
    updated_by: str
    updated_at: str


@dataclass(frozen=True, slots=True)
class Global:
    """One ``globals`` row, one field per ``_GLOBAL_COLUMNS`` entry."""

    va: int
    name: str
    decl: str
    files: tuple[str, ...]
    module: str
    size: int
    status: str


@dataclass(frozen=True, slots=True)
class CoverageSnapshot:
    """One target's coverage document, immutable and fully derived.

    ``function_stats`` is read, never recomputed: ``total``, ``covered_bytes``,
    ``matched_bytes`` and ``by_status`` are the numbers
    :func:`_derive_function_stats` produced from the stored function rows, and
    they are the numbers the dashboards' headers show.  A second restatement of
    that aggregate would be the third answer to "what counts as matched".
    """

    target: str
    version: int
    sections: Mapping[str, Section]
    functions: tuple[Function, ...]
    #: The globals table has no matching index here: nothing reads globals by VA
    #: at request rate (the batch lookup walks 346 rows).  Add one when a caller
    #: measures that it needs it.
    globals: tuple[Global, ...]
    verify_results: tuple[Mapping[str, Any], ...]
    history: tuple[Mapping[str, Any], ...]
    function_stats: Mapping[str, Any]
    paths: Mapping[str, Any]
    functions_by_va: Mapping[int, Function] = field(init=False)

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "functions_by_va", MappingProxyType({fn.va: fn for fn in self.functions})
        )


def _text(value: Any) -> str:
    """A text column as ``str``.  TOML's ``""`` stand-in for NULL is ``""``."""
    return value if isinstance(value, str) else ""


def _int(value: Any, default: int) -> int:
    """An integer column, *default* when it is missing or not an int.

    ``bool`` is excluded before ``int``: ``True`` is an int subclass and would
    land as 1.
    """
    if isinstance(value, bool) or not isinstance(value, int):
        return default
    return value


def _opt_int(value: Any) -> int | None:
    """An optional integer column: absent (``""``) and wrong-typed both read None."""
    if isinstance(value, bool) or not isinstance(value, int):
        return None
    return value


def _opt_float(value: Any) -> float | None:
    if isinstance(value, bool) or not isinstance(value, int | float):
        return None
    return float(value)


def _str_tuple(value: Any) -> tuple[str, ...]:
    if isinstance(value, list | tuple):
        return tuple(str(item) for item in value)
    return ()


def _freeze(value: Any) -> Any:
    """Recursively turn a parsed TOML value into an immutable one.

    A nested ``by_status`` dict left mutable would be a hole in the snapshot: one
    caller's edit would show up in the next caller's read, which is the
    guarantee the SQLite read transaction used to give.
    """
    if isinstance(value, dict):
        return MappingProxyType({key: _freeze(item) for key, item in value.items()})
    if isinstance(value, list | tuple):
        return tuple(_freeze(item) for item in value)
    return value


def _table_rows(value: Any, what: str, path: Path) -> list[dict[str, Any]]:
    """*value* as a list of tables, or a ``CoverageTomlError`` naming it."""
    if not isinstance(value, list) or not all(isinstance(row, dict) for row in value):
        raise CoverageTomlError(f"{path}: {what} is not an array of tables")
    return value


def _table(value: Any, what: str, path: Path) -> dict[str, Any]:
    """*value* as a table, or a ``CoverageTomlError`` naming it."""
    if not isinstance(value, dict):
        raise CoverageTomlError(f"{path}: {what} is not a table")
    return value


def _cell(row: dict[str, Any]) -> Cell:
    return Cell(
        start=_int(row.get("start"), 0),
        end=_int(row.get("end"), 0),
        span=_int(row.get("span"), 1),
        state=_text(row.get("state")),
        functions=_str_tuple(row.get("functions")),
        label=_text(row.get("label")),
        parent_function=_text(row.get("parent_function")),
    )


def _section(name: str, table: dict[str, Any], path: Path) -> Section:
    return Section(
        name=name,
        va=_opt_int(table.get("va")),
        size=_int(table.get("size"), 0),
        file_offset=_opt_int(table.get("fileOffset")),
        unit_bytes=_int(table.get("unitBytes"), 0),
        columns=_int(table.get("columns"), 0),
        cells=tuple(
            _cell(row) for row in _table_rows(table.get("cells", []), f"cells of {name}", path)
        ),
    )


def _function(row: dict[str, Any], path: Path) -> Function:
    return Function(
        va=_int(row.get("va"), 0),
        name=_text(row.get("name")),
        vaStart=_text(row.get("vaStart")),
        size=_opt_int(row.get("size")),
        fileOffset=_opt_int(row.get("fileOffset")),
        status=_text(row.get("status")),
        module=_text(row.get("module")),
        cflags=_freeze(row.get("cflags")),
        symbol=_text(row.get("symbol")),
        markerType=_text(row.get("markerType")),
        ghidra_name=_text(row.get("ghidra_name")),
        list_name=_text(row.get("list_name")),
        is_thunk=_int(row.get("is_thunk"), 0),
        is_export=_int(row.get("is_export"), 0),
        sha256=_text(row.get("sha256")),
        files=_str_tuple(row.get("files")),
        detected_by=_str_tuple(row.get("detected_by")),
        size_by_tool=_freeze(_table(row.get("size_by_tool", {}), "size_by_tool", path)),
        textOffset=_opt_int(row.get("textOffset")),
        blocker=_text(row.get("blocker")),
        blockerDelta=_opt_int(row.get("blockerDelta")),
        size_reason=_text(row.get("size_reason")),
        similarity=_opt_float(row.get("similarity")),
        updated_by=_text(row.get("updated_by")),
        updated_at=_text(row.get("updated_at")),
    )


def _global(row: dict[str, Any]) -> Global:
    return Global(
        va=_int(row.get("va"), 0),
        name=_text(row.get("name")),
        decl=_text(row.get("decl")),
        files=_str_tuple(row.get("files")),
        module=_text(row.get("module")),
        size=_int(row.get("size"), 0),
        status=_text(row.get("status")),
    )


def _derive_function_stats(
    functions: tuple[Function, ...], text: Section | None
) -> Mapping[str, Any]:
    """The ``function_stats`` dict, computed from the stored function rows.

    This is the aggregate the removed ``build_db.function_stats`` used to run
    over a throwaway table, with its cursor gone: the same ``FUNCTION_MARKERS``
    code-row filter, the same ``clip_span`` cut at the next function start, the
    same ``MATCHED_STATUSES`` split between identified bytes (every function,
    STUB placeholders included) and matched bytes (EXACT/RELOC, the headline
    figure).

    It is derived rather than stored because it is a pure function of the rows
    already in the file, and a stored copy is a second thing to keep in step on
    every rebuild.  The database stored it because reading it back cost a query;
    here it costs one pass over 600 rows at load.  The two count maps are
    sorted, so a rebuild that writes the same rows in a different order cannot
    change the value.
    """
    rows = [f for f in functions if f.markerType in FUNCTION_MARKERS]
    starts = sorted(f.va for f in rows if f.va is not None)
    by_status: dict[str, int] = {}
    by_module_counts: dict[str, int] = {}
    covered_bytes = 0
    matched_bytes = 0
    for fn in rows:
        status = fn.status or "UNKNOWN"
        by_status[status] = by_status.get(status, 0) + 1
        # Key is the stored module, including "": "GAME" is a real module name,
        # so a blank must not be counted under it.
        module = fn.module or ""
        by_module_counts[module] = by_module_counts.get(module, 0) + 1
        if fn.size is None or fn.va is None:
            continue
        # A negative SIZE is truthy, so it would reach clip_span and move both
        # totals the wrong way; the writer clamps it to 0 on the way in.
        size = clip_span(starts, fn.va, max(fn.size, 0))
        covered_bytes += size
        if status in MATCHED_STATUSES:
            matched_bytes += size
    return MappingProxyType(
        {
            "total": len(rows),
            # Identified bytes: every function, STUB placeholders included.
            "covered_bytes": covered_bytes,
            # EXACT/RELOC only — the headline coverage metric.
            "matched_bytes": matched_bytes,
            "total_bytes": text.size if text is not None else 0,
            "by_status": MappingProxyType(dict(sorted(by_status.items()))),
            "by_module_counts": MappingProxyType(dict(sorted(by_module_counts.items()))),
        }
    )


def _snapshot(path: Path, doc: dict[str, Any], target: str) -> CoverageSnapshot:
    """Build the snapshot from a parsed document, checking both target names.

    The document names its target twice (top level and the filename), and the
    two are written from one value.  They disagreeing means the file was renamed
    or hand-edited, and a request for ``a`` answered with ``b``'s coverage is the
    one failure mode a dashboard cannot show the reader.
    """
    # `type(...) is int`, not isinstance: a float 1.0 and True both compare equal
    # to 1 and neither is this schema's version.
    version = doc.get("version")
    if type(version) is not int or version != _TOML_VERSION:
        raise CoverageTomlError(f"{path}: version is {version!r}, expected {_TOML_VERSION}")
    doc_target = _text(doc.get("target"))
    if doc_target and doc_target != target:
        raise CoverageTomlError(f"{path}: target is {doc_target!r}, expected {target!r}")

    sections_doc = _table(doc.get("sections", {}), "sections", path)
    sections = {
        name: _section(name, _table(table, f'sections."{name}"', path), path)
        for name, table in sections_doc.items()
    }
    functions = tuple(
        _function(row, path) for row in _table_rows(doc.get("functions", []), "functions", path)
    )
    globals_ = tuple(_global(row) for row in _table_rows(doc.get("globals", []), "globals", path))
    verify_results = tuple(
        _freeze(row) for row in _table_rows(doc.get("verify_results", []), "verify_results", path)
    )
    history = tuple(_freeze(row) for row in _table_rows(doc.get("history", []), "history", path))
    metadata = _table(doc.get("metadata", {}), "metadata", path)
    paths = _freeze(_table(metadata.get("paths", {}), "paths", path))
    return CoverageSnapshot(
        target=doc_target or target,
        version=version,
        sections=MappingProxyType(sections),
        functions=functions,
        globals=globals_,
        verify_results=verify_results,
        history=history,
        function_stats=_derive_function_stats(functions, sections.get(".text")),
        paths=paths,
    )


def _read_document(path: Path, target: str) -> CoverageSnapshot:
    """Read and validate one document.  Every failure is a ``CoverageTomlError``.

    An unreadable file, malformed TOML, a foreign ``version`` and a schema
    violation all land in one exception type, because a dashboard's answer to
    all four is the same: this target is not readable, show the others.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        raise CoverageTomlError(f"{path}: cannot read ({exc})") from exc
    try:
        doc = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        # A file torn by anything other than atomic_write_text lands here too.
        raise CoverageTomlError(f"{path}: malformed TOML ({exc})") from exc
    return _snapshot(path, doc, target)


# Memoized directory scan: ((db_dir, ((name, mtime_ns, size, ino), ...)), snapshots).
# The key is every input the answer has — the directory and the stat of every
# file in it — so a rebuilt file, an added target and a removed one all
# invalidate.  load_all_coverage runs on the request path and re-reading and
# re-parsing a 1.25 MB document per request is pure waste; one stat per
# candidate file replaces it.  The tuple swap is atomic under the GIL and a
# racing recomputation yields an equal value, so no lock: the worst case is a
# duplicate parse.  Same pattern, same reason as recoverage's _db_path memo.
# Callers use the returned object's identity as their own cache key, so an
# unchanged directory returns THE SAME snapshots, not equal copies.
_ALL_CACHE: (
    tuple[tuple[Path, tuple[tuple[str, int, int, int], ...]], dict[str, CoverageSnapshot]] | None
) = None


def _stat_key(db_directory: Path) -> tuple[tuple[str, int, int, int], ...]:
    """``(name, mtime_ns, size, ino)`` for every ``coverage-*.toml`` in the directory.

    Sorted, because a directory listing's order is not a fact about the files.
    A file that vanishes between the listing and the stat is skipped: the next
    call's key differs, so the miss is caught then.

    The inode is what catches a document replaced by a same-size rename-over
    inside one mtime tick (a ``cp -p`` restore, a git checkout of a restored
    file, a coarse-timestamp filesystem), which mtime and size alone cannot
    see; this matches every other per-file memo in the tree
    (``verify_hash._SOURCE_MEMO``, ``metadata_doc``, ``utils.read_source_text``).
    """
    entries: list[tuple[str, int, int, int]] = []
    for path in db_directory.glob(f"{_FILENAME_PREFIX}*{_FILENAME_SUFFIX}"):
        try:
            st = path.stat()
        except OSError:
            continue
        entries.append((path.name, st.st_mtime_ns, st.st_size, st.st_ino))
    entries.sort()
    return tuple(entries)


def load_all_coverage_from(db_directory: Path) -> dict[str, CoverageSnapshot]:
    """``load_all_coverage`` for a caller that already holds the directory.

    ``load_all_coverage`` takes a project ROOT and resolves ``[project].db_dir``
    (or ``<root>/db``) itself, which is the right call for a tool started in a
    project.  A dashboard can also be pointed straight at a directory — the
    recoverage ``RECOVERAGE_DB`` override names one — and deriving a root from
    that path to let this module derive the directory back loses whenever the
    parent directory has its own ``rebrew-project.toml`` naming a different db
    dir.  One glob, keyed on the files themselves, is the whole difference.
    """
    global _ALL_CACHE
    db_directory = Path(db_directory)
    key = (db_directory, _stat_key(db_directory))
    cached = _ALL_CACHE
    if cached is not None and cached[0] == key:
        return cached[1]
    snapshots: dict[str, CoverageSnapshot] = {}
    for name, _mtime_ns, _size, _ino in key[1]:
        target = name[len(_FILENAME_PREFIX) : -len(_FILENAME_SUFFIX)]
        path = db_directory / name
        try:
            snapshots[target] = _read_document(path, target)
        except CoverageTomlError as exc:
            log.warning("coverage_toml: skipping %s: %s", path, exc)
    _ALL_CACHE = (key, snapshots)
    return snapshots


def load_coverage_from(db_directory: Path, target: str) -> CoverageSnapshot:
    """One target's snapshot from an explicit *db_directory*.

    The directory-taking twin of :func:`load_coverage`, for the same caller:
    a dashboard whose database location is configuration, not a project root.
    """
    if not target or Path(target).name != target:
        raise CoverageTomlError(f"{target!r} is not a target name")
    path = Path(db_directory) / f"{_FILENAME_PREFIX}{target}{_FILENAME_SUFFIX}"
    return _read_document(path, target)


def load_all_coverage(root_dir: Path) -> dict[str, CoverageSnapshot]:
    """Every target in *root_dir*'s db directory, keyed by target name.

    Returns ``{}`` when the directory holds no ``coverage-*.toml``.  One
    unreadable document is skipped with a warning naming the file and the
    reason, never raised: a dashboard showing two of three targets beats a 500.
    An unchanged directory returns the previously built mapping, so callers can
    use ``is`` as their own cache key.
    """
    return load_all_coverage_from(_db_directory(root_dir))


def load_coverage(root_dir: Path, target: str | None = None) -> CoverageSnapshot:
    """Load one target's snapshot from ``db/coverage-<target>.toml``.

    Raises :class:`CoverageTomlError` when the file is missing, when its
    ``version`` is not :data:`_TOML_VERSION`, when the TOML is malformed, and
    when the document is not shaped like this schema.

    *target* ``None`` means the project has exactly one target: the sole
    ``coverage-*.toml`` is returned and any other number is an error naming the
    candidates.  Resolving a default out of ``rebrew-project.toml`` instead
    would answer with a target the caller did not name, which is the one thing a
    per-target reader must not do.

    A *target* carrying a path separator is refused rather than resolved: the
    dashboards take a target id from the request path, and the SQLite reader
    could not be made to read a foreign database by spelling a VA or a target
    oddly.  A filename can.
    """
    db_directory = _db_directory(root_dir)
    if target is None:
        snapshots = load_all_coverage(root_dir)
        if len(snapshots) != 1:
            found = ", ".join(sorted(snapshots)) or "none"
            raise CoverageTomlError(
                f"{db_directory}: expected exactly one coverage file for target=None, "
                f"found {len(snapshots)} ({found})"
            )
        return next(iter(snapshots.values()))
    if not target or Path(target).name != target:
        raise CoverageTomlError(f"{target!r} is not a target name")
    return _read_document(db_directory / f"{_FILENAME_PREFIX}{target}{_FILENAME_SUFFIX}", target)
