"""data.py – Global data scanner for rebrew.

Scans reversed .c files for ``// GLOBAL: MODULE 0xVA`` and ``// DATA: MODULE 0xVA``
annotations (reccmp standard) and ``extern`` data declarations, cross-references
them with the binary's ``.data``/``.rdata``/``.bss`` sections, detects type conflicts
across files, and outputs a catalog of known globals.

Also provides:
- Dispatch table / vtable detection via ``--dispatch``
- BSS layout verification via ``--bss``
- Header generation via ``--gen-header`` (writes ``rebrew_globals.h``)

Scanning, dispatch detection, and BSS verification live in ``rebrew.data_scan``;
this module is the CLI on top of them.

"""

import re
from pathlib import Path
from typing import Any

import typer

from rebrew.cli import TargetOption, console, error_exit, json_print, require_config
from rebrew.config import module_marker
from rebrew.data_scan import (
    BssReport,
    build_dispatch_known_functions,
    enrich_with_sections,
    find_dispatch_tables,
    scan_data_annotations,
    scan_globals,
    verify_bss_layout,
)
from rebrew.utils import atomic_write_text, untrusted_ident

app = typer.Typer(
    help="Global data scanner — inventory this target's .data/.rdata/.bss globals.",
    rich_markup_mode="rich",
    epilog=(
        "[bold]Modes:[/bold]\n\n"
        "  [dim](default)[/dim] · · · · Scan reversed sources for GLOBAL:/extern declarations\n\n"
        "  --conflicts · · · · Show only globals with type conflicts across files\n\n"
        "  --summary · · · · · Show section-level summary (counts per .data/.rdata/.bss)\n\n"
        "  --dispatch · · · · · Detect dispatch tables / vtables in .data/.rdata sections\n\n"
        "  --bss · · · · · · · Verify .bss layout and detect gaps between globals\n\n"
        "  --fix-bss · · · · · Auto-generate bss_padding.c with dummy arrays for gaps\n\n"
        "  --gen-header · · · · Generate rebrew_globals.h from annotations (no Ghidra)\n\n"
        "[bold]Examples:[/bold]\n\n"
        "  rebrew data list · · · · · · · · · · · · · Scan this target's globals (default mode)\n\n"
        "  rebrew data list --conflicts · · · · · · · · Show type conflicts across files\n\n"
        "  rebrew data list --summary · · · · · · · · · Section-level overview\n\n"
        "  rebrew data dispatch · · · · · · · · · Detect vtables in data sections\n\n"
        "  rebrew data dispatch --min-table-len 5 · Require at least 5 entries per table\n\n"
        "  rebrew data dispatch --max-pointer-stride 8 · Allow 8-byte strides between slots\n\n"
        "  rebrew data bss · · · · · · · · · · · Verify .bss layout and gaps\n\n"
        "  rebrew data fix-bss · · · · · · · · · Generate bss_padding.c for gaps\n\n"
        "  rebrew data header · · · · · · · · Generate rebrew_globals.h\n\n"
        "  rebrew data list --json · · · · · · · · · · · Output as JSON\n\n"
        "[dim]Scans reversed .c files for GLOBAL:/DATA: annotations and extern "
        "declarations, cross-references with binary data sections, and detects "
        "type conflicts across files.[/dim]"
    ),
)


_BSS_PADDING_HEADER = "/* Auto-generated by rebrew data fix-bss */"


def _generate_bss_fix(
    report: BssReport,
    src_dir: Path,
    origin: str,
    *,
    metadata_dir: Path | None = None,
    dry_run: bool = False,
    json_output: bool = False,
) -> None:
    """Generate a bss_padding.c file with dummy arrays for all detected BSS gaps.

    SIZE, SECTION, and NOTE are written to ``rebrew-data.toml`` metadata, not inline.
    With *dry_run*, prints what would be written without touching the disk.

    *src_dir* is where ``bss_padding.c`` is written (``cfg.reversed_dir``);
    *metadata_dir* is the ``rebrew-data.toml`` root (``cfg.metadata_dir`` —
    the reversed_dir's *parent*).  These differ, and routing the metadata
    writes to src_dir orphans them (reads use metadata_dir everywhere).

    Idempotent on re-run: the generated file's OWN ``char gap_`` arrays
    close the gaps they fill, so a second run's gap scan reports fewer gaps —
    regenerating from scratch would DELETE the arrays written by the first
    run while the data metadata still claims coverage (idempotency-review
    F4).  The existing auto-generated declarations are merged with the new
    gaps instead, and the file is written BEFORE its metadata so a crash
    between the two can never leave metadata claiming coverage the source
    does not declare.
    """
    from rebrew.data_metadata import record_migrated_data_markers, set_data_fields_batch
    from rebrew.metadata import identity_file

    meta_dir = metadata_dir if metadata_dir is not None else src_dir
    out_file = src_dir / "bss_padding.c"

    # Existing auto-generated declarations (offset -> size), preserved across
    # re-runs — see docstring.  Only the auto-generated file is merged; a
    # user-created bss_padding.c (different header) is left alone.
    existing_decls: dict[int, int] = {}
    if out_file.exists():
        text = out_file.read_text(encoding="utf-8")
        if not text.startswith(_BSS_PADDING_HEADER):
            # A hand-written bss_padding.c: rewriting it would delete arrays
            # the maintainer wrote, and the metadata rewritten with it would
            # then describe declarations the source no longer has.
            message = (
                f"{out_file.name} exists and was not generated by "
                "rebrew data list --fix-bss; leaving it untouched."
                "Remove it or move it aside to regenerate the padding."
            )
            if json_output:
                json_print(
                    {
                        "action": "fix_bss",
                        "file": out_file.name,
                        "dry_run": dry_run,
                        "existing_arrays": 0,
                        "new_arrays": 0,
                        "message": message,
                    }
                )
                return
            console.print(f"[yellow]{message}[/yellow]")
            return
        for line in text.splitlines():
            m = re.match(r"// DATA: \S+ 0x([0-9a-fA-F]{8})", line)
            if m:
                existing_decls[int(m.group(1), 16)] = 0
        # char gap_XXXXXXXX[N]; — recover the declared size
        for m in re.finditer(r"char gap_([0-9a-fA-F]{8})\[(\d+)\];", text):
            existing_decls[int(m.group(1), 16)] = int(m.group(2))

    if not report.gaps and not existing_decls:
        if json_output:
            json_print(
                {
                    "action": "fix_bss",
                    "file": out_file.name,
                    "dry_run": dry_run,
                    "existing_arrays": 0,
                    "new_arrays": 0,
                    "message": (
                        "No BSS gaps detected. Layout is perfect!"
                        if report.known_entries
                        else "No annotated BSS globals — nothing to verify."
                    ),
                }
            )
            return
        if report.known_entries:
            console.print("No BSS gaps detected. Layout is perfect!")
        else:
            console.print(
                "[yellow]No annotated BSS globals — nothing to verify. "
                "Declare .bss globals (or record them in rebrew-data.toml) "
                "to check the layout.[/yellow]"
            )
        return

    # New gaps = detected gaps not already declared by the auto-generated
    # file.  Already-declared offsets keep their existing arrays untouched.
    new_gaps = [g for g in report.gaps if g.offset not in existing_decls]

    lines = [
        _BSS_PADDING_HEADER,
        "/* SIZE/SECTION/NOTE metadata is in rebrew-data.toml */\n",
    ]
    # Preserve existing declarations first (stable ordering by offset).
    for offset in sorted(existing_decls):
        size = existing_decls[offset]
        if size > 0:
            lines.append(f"char gap_{offset:08x}[{size}];")
    # Then the newly detected gaps.
    for gap in sorted(new_gaps, key=lambda g: g.offset):
        if gap.size <= 0:
            continue
        lines.append(f"char gap_{gap.offset:08x}[{gap.size}];")

    if dry_run:
        if json_output:
            json_print(
                {
                    "action": "fix_bss",
                    "file": out_file.name,
                    "dry_run": True,
                    "existing_arrays": len(existing_decls),
                    "new_arrays": len(new_gaps),
                    "declarations": [line for line in lines if line.startswith("char gap_")],
                }
            )
            return
        console.print(
            f"[dim]Dry run:[/dim] would write {out_file.name} with "
            f"{len(existing_decls)} existing + {len(new_gaps)} new padding array(s):"
        )
        for line in lines:
            if line.startswith("char gap_"):
                console.print(f"  [dim]{untrusted_ident(line)}[/]")
        return

    # File FIRST, then metadata: a crash in between must not leave
    # rebrew-data.toml claiming coverage the .c does not declare.
    # Skip the rewrite when the generated body is byte-identical — a
    # no-op re-run must not bump mtime (verify cache / git dirty).
    new_text = "\n".join(lines)
    if not out_file.exists() or out_file.read_text(encoding="utf-8") != new_text:
        atomic_write_text(out_file, new_text, encoding="utf-8")
    file_rel = identity_file(out_file, meta_dir)
    identity_rows: list[dict[str, Any]] = []
    for offset, size in sorted(existing_decls.items()):
        if size <= 0:
            continue
        identity_rows.append(
            {
                "module": origin,
                "va": offset,
                "identity": {
                    "file": file_rel,
                    "marker_type": "DATA",
                    "name": f"gap_{offset:08x}",
                },
                "fill": {"size": size, "section": ".bss"},
            }
        )
    for gap in new_gaps:
        if gap.size <= 0:
            continue
        identity_rows.append(
            {
                "module": origin,
                "va": gap.offset,
                "identity": {
                    "file": file_rel,
                    "marker_type": "DATA",
                    "name": f"gap_{gap.offset:08x}",
                },
                "fill": {"size": gap.size, "section": ".bss"},
            }
        )
    if identity_rows:
        record_migrated_data_markers(meta_dir, identity_rows)
    if new_gaps:
        # Write metadata to data metadata (the metadata root, not src_dir).
        # Batched: one TOML RMW for all new gaps instead of three writes each.
        set_data_fields_batch(
            meta_dir,
            [
                {
                    "module": origin,
                    "va": gap.offset,
                    "fields": {
                        "size": gap.size,
                        "section": ".bss",
                        "note": f"gap between {gap.before} and {gap.after}",
                    },
                    "updated_by": "data",
                }
                for gap in new_gaps
            ],
        )
        console.print(
            f"Updated {out_file.name}: {len(existing_decls)} existing + "
            f"{len(new_gaps)} new padding array(s)."
        )
        console.print(
            "Metadata written to rebrew-data.toml. Compile this file to fix .bss alignment."
        )
    else:
        console.print(
            f"{out_file.name} is up to date ({len(existing_decls)} padding array(s) already declared)."
        )
    if json_output:
        json_print(
            {
                "action": "fix_bss",
                "file": out_file.name,
                "dry_run": False,
                "existing_arrays": len(existing_decls),
                "new_arrays": len(new_gaps),
                "up_to_date": not new_gaps,
            }
        )


def execute_data(
    link_map: Path | None = None,
    set_storage_kind: list[str] | None = None,
    set_backing: list[str] | None = None,
    set_link_symbol: list[str] | None = None,
    conflicts: bool = False,
    summary: bool = False,
    dispatch: bool = False,
    min_table_len: int = 3,
    max_pointer_stride: int = 4,
    bss: bool = False,
    fix_bss: bool = False,
    gen_header: bool = False,
    annotate: bool = False,
    set_type: list[str] | None = None,
    set_name: list[str] | None = None,
    set_size: list[str] | None = None,
    set_section: list[str] | None = None,
    gen_header_out: Path | None = None,
    force: bool = False,
    dry_run: bool = False,
    layout_audit: bool = False,
    section: str = ".data",
    fill_data: bool = False,
    bss_only: bool = False,
    own: bool = False,
    stub_file: Path | None = None,
    fix_ownership: bool = False,
    converge: bool = False,
    rounds: int = 1,
    json_output: bool = False,
    target: str | None = None,
) -> None:
    """Scan reversed source files for global data declarations."""
    set_storage_kind = set_storage_kind or []
    set_backing = set_backing or []
    set_link_symbol = set_link_symbol or []
    set_type = set_type or []
    set_name = set_name or []
    set_size = set_size or []
    set_section = set_section or []
    if (
        sum(
            bool(value)
            for value in (
                set_type,
                set_name,
                set_size,
                set_section,
                set_storage_kind,
                set_backing,
                set_link_symbol,
            )
        )
        > 1
    ):
        error_exit(
            "Use only one data setter per call: --type, --name, --size, "
            "--section, --storage-kind, --backing, or --link-symbol.",
            json_mode=json_output,
        )
    cfg = require_config(target=target, json_mode=json_output)

    src_dir = cfg.reversed_dir
    bin_path = cfg.target_binary

    # --type: correct a declared global type in the data metadata
    if set_storage_kind or set_backing or set_link_symbol:
        from rebrew.data_annotate import set_data_relation

        try:
            rows = []
            for field, specs in (
                ("storage_kind", set_storage_kind),
                ("backing", set_backing),
                ("link_symbol", set_link_symbol),
            ):
                rows.extend(set_data_relation(cfg, specs, field, dry_run=dry_run))
        except ValueError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print({"dry_run": dry_run, "set": rows})
        else:
            console.print(f"Updated {len(rows)} data storage relationship(s).")
        return

    if set_type:
        from rebrew.data_annotate import set_data_types

        try:
            rows = set_data_types(cfg, set_type, dry_run=dry_run)
        except ValueError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print({"dry_run": dry_run, "set": rows})
        else:
            for row in rows:
                console.print(
                    f"set type {row['type']!r} for {row['va']} ({untrusted_ident(row['module'])})"
                )
        return

    if set_name:
        from rebrew.data_annotate import set_data_names

        try:
            rows = set_data_names(cfg, set_name, dry_run=dry_run)
        except ValueError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print({"dry_run": dry_run, "set": rows})
        else:
            for row in rows:
                console.print(
                    f"set name {row['name']!r} for {row['va']} ({untrusted_ident(row['module'])})"
                )
        return

    if set_size:
        from rebrew.data_annotate import set_data_sizes

        try:
            rows = set_data_sizes(cfg, set_size, dry_run=dry_run)
        except ValueError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print({"dry_run": dry_run, "set": rows})
        else:
            for row in rows:
                console.print(
                    f"set size {row['size']} for {row['va']} ({untrusted_ident(row['module'])})"
                )
        return

    # --section: give a // GLOBAL: marker its SECTION metadata (lint W016)
    if set_section:
        from rebrew.data_annotate import set_data_sections

        try:
            rows = set_data_sections(cfg, set_section, dry_run=dry_run)
        except ValueError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print({"dry_run": dry_run, "set": rows})
        else:
            for row in rows:
                console.print(
                    f"set section {row['section']!r} for {row['va']} "
                    f"({untrusted_ident(row['module'])})"
                )
        return

    # --gen-header: generate rebrew_globals.h from annotations (no Ghidra)
    if gen_header:
        from rebrew.data_annotate import gen_globals_header

        try:
            result = gen_globals_header(
                cfg, src_dir, out_path=gen_header_out, force=force, dry_run=dry_run
            )
        except FileExistsError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print(result)
            return
        out_name = Path(result["path"]).name
        if dry_run:
            console.print(
                f"[cyan]dry-run:[/cyan] would write {untrusted_ident(result['path'])} "
                f"with {result['globals']} globals"
            )
        elif not result["written"]:
            console.print(f"[dim]{out_name} unchanged[/dim] ({result['globals']} globals)")
        else:
            console.print(f"[green]Wrote {out_name}[/green] with {result['globals']} globals")
            for sec, count in result["sections"].items():
                console.print(f"  {untrusted_ident(sec)}: {count}")
        return

    # --layout-audit / --fill-data / --own / --fix-ownership / --converge:
    # .data placement machinery
    if layout_audit or fill_data or own or fix_ownership or converge:
        from rebrew.data_layout import audit_layout, own_data_globals
        from rebrew.data_layout import converge_layout as converge_data_layout
        from rebrew.data_layout import fill_data as fill_data_layout
        from rebrew.data_layout import fix_ownership as fix_data_ownership

        metadata = cfg.metadata_dir / "rebrew-data.toml"
        if not metadata.exists():
            error_exit(f"data metadata not found: {metadata}", json_mode=json_output)
        if layout_audit:
            if section not in (".data", ".rdata"):
                error_exit("--section must be .data or .rdata", json_mode=json_output)
            try:
                report = audit_layout(cfg.root, metadata, section)
            except OSError as exc:
                error_exit(str(exc), json_mode=json_output)
            if json_output:
                json_print(report)
            else:
                console.print(
                    f"{'TU':58} {'#sym':>4} {'min addr':>10} {'max addr':>10} "
                    f"{'data':>7} {'bss':>7}"
                )
                console.print("-" * 104)
                for r in report["rows"]:
                    flag = f"  <== {'/'.join(r['flags'])} VIOLATION" if r["flags"] else ""
                    sym_count = len(set(r["dsyms"]) | set(r["bsyms"]))
                    console.print(
                        f"{untrusted_ident(r['obj']):58} {sym_count:4} "
                        f"{r['min_addr']:#10x} {r['max_addr']:#10x} "
                        f"{r['dsize']:#7x} {r['bsize']:#7x}{flag}"
                    )
                console.print("-" * 104)
                console.print(f"violations: {report['violations']}")
                for r in report["rows"]:
                    if r.get("error"):
                        console.print(
                            f"[red]objdump error on {untrusted_ident(r['obj'])}: "
                            f"{untrusted_ident(r['error'])}[/red]"
                        )
                if report["unowned"]:
                    console.print(
                        f"unowned toml symbols ({len(report['unowned'])}): "
                        + ", ".join(untrusted_ident(s) for s, _ in report["unowned"][:10])
                    )
                if report["duplicate_owned"]:
                    console.print(
                        f"duplicate-owned ({len(report['duplicate_owned'])}): "
                        + ", ".join(
                            untrusted_ident(s) for s, _, _ in report["duplicate_owned"][:10]
                        )
                    )
            return
        if fill_data:
            try:
                result = fill_data_layout(
                    cfg.root,
                    metadata,
                    bin_path,
                    src_dir,
                    dry_run=dry_run,
                    bss_only=bss_only,
                    target=getattr(cfg, "target_name", None),
                    shared_dir=getattr(cfg, "shared_dir", None),
                )
            except OSError as exc:
                error_exit(str(exc), json_mode=json_output)
            if json_output:
                json_print(result)
            else:
                console.print(
                    f"[green]data fill-data:[/green] {result['init_pads']} init pads, "
                    f"{result['bss_pads']} bss pads{' (dry run)' if dry_run else ''}"
                )
            return
        if own:
            stub = stub_file if stub_file is not None else cfg.root / "src" / "link_stubs.c"
            if not stub.exists():
                error_exit(f"stub file not found: {stub} (--stub-file)", json_mode=json_output)
            try:
                own_result = own_data_globals(
                    cfg.root,
                    metadata,
                    bin_path,
                    src_dir,
                    stub,
                    dry_run=dry_run,
                    target=getattr(cfg, "target_name", None),
                    shared_dir=getattr(cfg, "shared_dir", None),
                )
            except OSError as exc:
                error_exit(str(exc), json_mode=json_output)
            if json_output:
                json_print(own_result)
            else:
                console.print(
                    f"[green]data own:[/green] {own_result['owned']} globals materialized"
                    f"{' (dry run)' if dry_run else ''}"
                )
                if own_result["skipped"]:
                    console.print(
                        f"  skipped ({len(own_result['skipped'])}): "
                        + ", ".join(untrusted_ident(s) for s in own_result["skipped"][:10])
                    )
            return
        if fix_ownership:
            try:
                fix_result = fix_data_ownership(
                    cfg.root,
                    metadata,
                    bin_path,
                    src_dir,
                    dry_run=dry_run,
                    target=getattr(cfg, "target_name", None),
                    shared_dir=getattr(cfg, "shared_dir", None),
                )
            except OSError as exc:
                error_exit(str(exc), json_mode=json_output)
            if json_output:
                json_print(fix_result)
            else:
                console.print(
                    f"[green]data fix-ownership:[/green] {fix_result['edits']} edits "
                    f"({fix_result['moved']} definitions moved){' (dry run)' if dry_run else ''}"
                )
            return
        try:
            conv_result = converge_data_layout(
                cfg.root,
                metadata,
                bin_path,
                src_dir,
                rounds=rounds,
                dry_run=dry_run,
                # The target names both the build output (build/<target>) and
                # the .data geometry the pads are sized against; without it a
                # multi-target project converges the default target's numbers.
                target=cfg.target_name,
            )
        except OSError as exc:
            error_exit(str(exc), json_mode=json_output)
        if json_output:
            json_print(conv_result)
        else:
            console.print(
                f"[green]data converge:[/green] {len(conv_result['adjustments'])} pad adjustments "
                f"over {conv_result['rounds']} round(s){' (dry run)' if dry_run else ''}"
            )
        return

    # --annotate: bind data rows that lack a file to the declaration's source.
    if annotate:
        from rebrew.data_annotate import annotate_globals

        metadata = cfg.metadata_dir / "rebrew-data.toml"
        if not metadata.exists():
            error_exit(f"data metadata not found: {metadata}", json_mode=json_output)
        marker = module_marker(cfg)
        per_file, skipped_unnamed = annotate_globals(
            src_dir, metadata, marker, dry_run=dry_run, cfg=cfg
        )
        total = sum(per_file.values())
        if json_output:
            json_print({"bound": total, "files": per_file, "skipped_unnamed": skipped_unnamed})
        else:
            console.print(f"[green]data annotate:[/green] {total} row(s) bound")
            if skipped_unnamed:
                console.print(
                    f"[yellow]{skipped_unnamed} metadata entr{'y' if skipped_unnamed == 1 else 'ies'}"
                    " skipped — no `name` field in rebrew-data.toml (the declaration"
                    " names the row)[/yellow]"
                )
            for f, n in sorted(per_file.items()):
                console.print(f"  {untrusted_ident(f)}: {n}")
        return

    scan = scan_globals(src_dir, cfg=cfg)

    sections: dict[str, dict[str, Any]] = {}
    bin_info: Any = None  # single lazy binary parse, shared with --dispatch
    if bin_path.exists():
        try:
            from rebrew.binary_loader import load_binary
            from rebrew.sections import sections_from_info

            bin_info = load_binary(bin_path)
            sections = sections_from_info(bin_info)
        except (ImportError, OSError, KeyError, ValueError) as exc:
            # Every section-derived view below (global sections, the
            # out-of-range VA cross-check, BSS layout) is silently degraded
            # without this, and the BSS report then tells the user to go
            # annotate globals that were never the problem.
            console.print(
                f"[yellow]warning:[/yellow] cannot read sections from "
                f"{untrusted_ident(bin_path)} ({untrusted_ident(exc)}); "
                "global sections, the out-of-range VA check and the BSS layout "
                "report are omitted"
            )
            bin_info = None
            sections = {}
        enrich_with_sections(scan, sections)

        # R4 (np-rebrew TOOLCHAIN_BUGS): cross-check annotated global VAs
        # against the real PE section ranges.  A typo'd or stale VA silently
        # no-ops in the grid/catalog and shows up as an unexplained coverage
        # gap — surface it instead.
        section_ranges = [
            (s["va"], s["va"] + s["size"])
            for s in sections.values()
            if s.get("va") and s.get("size")
        ]
        if section_ranges:
            out_of_range = [
                (name, g.va)
                for name, g in scan.globals.items()
                if g.va and not any(lo <= g.va < hi for lo, hi in section_ranges)
            ]
            if out_of_range:
                console.print(
                    f"[yellow]warning:[/yellow] {len(out_of_range)} annotated global(s) "
                    "fall outside every PE section range: "
                    + ", ".join(f"{untrusted_ident(n)}@0x{va:x}" for n, va in out_of_range[:8])
                )

    data_anns = scan_data_annotations(src_dir, cfg=cfg)
    scan.data_annotations = data_anns

    # Presentation helpers — CLI-only; keep library imports of scan_globals free
    # of Rich / annotate writers.
    from rebrew.data_render import (
        render_bss,
        render_dispatch,
        render_globals,
        render_summary,
        section_summary,
    )

    if bss or fix_bss:
        bss_report = verify_bss_layout(scan, sections)
        if fix_bss:
            _generate_bss_fix(
                bss_report,
                src_dir,
                # Match --annotate's marker fallback: an empty origin would
                # emit `// DATA:  0x...` which the annotation parser rejects.
                module_marker(cfg),
                metadata_dir=cfg.metadata_dir,
                dry_run=dry_run,
                json_output=json_output,
            )
            return

        if json_output:
            json_print(bss_report.to_dict())
        else:
            console.print()
            render_bss(console, bss_report)
        return

    if dispatch:
        if not bin_path.exists():
            error_exit("target binary not found (needed for --dispatch)", json_mode=json_output)

        if bin_info is None:
            error_exit(
                "target binary could not be parsed (needed for --dispatch)",
                json_mode=json_output,
            )
        binary_data = bin_info.data
        from rebrew.binary_loader import section_dict

        sec_dict = section_dict(bin_info)

        # Build known functions map from reversed source files, then merge in
        # function-list / Ghidra-structure names for targets without sources.
        known_functions = build_dispatch_known_functions(cfg, src_dir)

        tables = find_dispatch_tables(
            binary_data,
            sec_dict,
            known_functions,
            min_entries=min_table_len,
            max_stride=max_pointer_stride,
            info=bin_info,
        )

        if json_output:
            json_print([t.to_dict() for t in tables])
        else:
            console.print()
            render_dispatch(console, tables)
        return

    from rebrew.data_ownership import enrich_library_owners

    try:
        enrich_library_owners(scan, cfg, link_map)
    except (OSError, ValueError) as exc:
        error_exit(f"cannot read link map: {exc}", json_mode=json_output)

    if json_output:
        data = scan.to_dict()
        if conflicts:
            # --conflicts ("Show only globals with type conflicts") filters
            # JSON output like the Rich path.  The summary counts describe
            # the filtered set so the payload stays self-consistent.
            conflict_names = {c["name"] for c in scan.type_conflicts}
            data["globals"] = {
                k: v for k, v in data["globals"].items() if v["name"] in conflict_names
            }
            data["summary"]["total"] = len(data["globals"])
            data["summary"]["annotated"] = sum(
                1 for g in data["globals"].values() if g["annotated"]
            )
            data["summary"]["unannotated"] = data["summary"]["total"] - data["summary"]["annotated"]
            data["summary"]["multiple_definitions"] = sum(
                len(g["defined_in"]) > 1 for g in data["globals"].values()
            )
            data["summary"]["library_owned"] = sum(
                bool(g["library_owners"]) for g in data["globals"].values()
            )
        data["sections"] = {
            name: {"va": f"0x{s['va']:08x}", "size": s["size"]} for name, s in sections.items()
        }
        if summary:
            # --summary composes with --json: emit a structured section progress view.
            data["summary"] = {
                "sections": section_summary(scan, sections),
                "conflicts": len(scan.type_conflicts),
            }
        json_print(data)
        return

    console.print()

    if summary:
        render_summary(console, scan, sections)
    elif conflicts:
        render_globals(console, scan, conflicts_only=True)
        if scan.type_conflicts:
            console.print()
            for c in scan.type_conflicts:
                console.print(f"  [bold red]⚠ {untrusted_ident(c['name'])}[/]:")
                for t, files in c["types"].items():
                    console.print(
                        f"    {untrusted_ident(t):30s} ← "
                        f"{', '.join(untrusted_ident(f) for f in files)}"
                    )
    else:
        render_globals(console, scan)
        if scan.type_conflicts:
            console.print(
                f"\n  [yellow]⚠ {len(scan.type_conflicts)} type conflict(s) detected — run with --conflicts for details[/]"
            )

    console.print()


@app.command(
    "list",
    epilog="Examples:\n\n  rebrew data list --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def list_data(
    link_map: Path | None = typer.Option(
        None, "--link-map", help="MSVC link map for library data owners (default: raw_link's .map)"
    ),
    conflicts: bool = typer.Option(
        False, "--conflicts", help="Show only globals with type conflicts"
    ),
    summary: bool = typer.Option(False, "--summary", help="Show section-level summary only"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Inventory globals and report section summaries or conflicts."""
    execute_data(
        link_map=link_map,
        conflicts=conflicts,
        summary=summary,
        json_output=json_output,
        target=target,
    )


@app.command(
    "set",
    epilog="Examples:\n\n  rebrew data set --type 0x401000=int --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def set_data(
    set_storage_kind: list[str] = typer.Option(
        [], "--storage-kind", help="0xVA=object|alias|literal|span|import (repeatable)"
    ),
    set_backing: list[str] = typer.Option(
        [], "--backing", help="0xVA=GLOBAL: backing storage for an alias (repeatable)"
    ),
    set_link_symbol: list[str] = typer.Option(
        [],
        "--link-symbol",
        help="0xVA=SYMBOL: exact native linker symbol for an analysis label (repeatable)",
    ),
    set_type: list[str] = typer.Option(
        [],
        "--type",
        help="Set a global's declared type in rebrew-data.toml: 0xVA=TYPE (repeatable)",
    ),
    set_name: list[str] = typer.Option(
        [],
        "--name",
        help="Set a global's C identifier in rebrew-data.toml: 0xVA=NAME (repeatable)",
    ),
    set_size: list[str] = typer.Option(
        [],
        "--size",
        help="Set a global's positive byte size: 0xVA=BYTES (decimal or hex, repeatable); "
        "clears its stored verification verdict",
    ),
    set_section: list[str] = typer.Option(
        [],
        "--section",
        help="Set a global's PE section in rebrew-data.toml: 0xVA=.data (repeatable)",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Set one metadata field through the locked data writers."""
    if (
        sum(
            bool(value)
            for value in [
                set_storage_kind,
                set_backing,
                set_link_symbol,
                set_type,
                set_name,
                set_size,
                set_section,
            ]
        )
        == 0
    ):
        error_exit("Choose exactly one data field to set", json_mode=json_output)
    execute_data(
        set_storage_kind=set_storage_kind,
        set_backing=set_backing,
        set_link_symbol=set_link_symbol,
        set_type=set_type,
        set_name=set_name,
        set_size=set_size,
        set_section=set_section,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
    )


@app.command(
    "dispatch",
    epilog="Examples:\n\n  rebrew data dispatch --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def dispatch(
    link_map: Path | None = typer.Option(
        None, "--link-map", help="MSVC link map for library data owners (default: raw_link's .map)"
    ),
    min_table_len: int = typer.Option(
        3,
        "--min-table-len",
        help="Minimum number of entries to qualify as a dispatch table",
    ),
    max_pointer_stride: int = typer.Option(
        4,
        "--max-pointer-stride",
        help="Maximum byte stride between pointer slots when scanning for tables",
    ),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Decode dispatch tables and their storage extents."""
    execute_data(
        link_map=link_map,
        min_table_len=min_table_len,
        max_pointer_stride=max_pointer_stride,
        json_output=json_output,
        target=target,
        dispatch=True,
    )


@app.command(
    "bss",
    epilog="Examples:\n\n  rebrew data bss --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def bss(
    link_map: Path | None = typer.Option(
        None, "--link-map", help="MSVC link map for library data owners (default: raw_link's .map)"
    ),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Report BSS extents and gaps."""
    execute_data(link_map=link_map, json_output=json_output, target=target, bss=True)


@app.command(
    "fix-bss",
    epilog="Examples:\n\n  rebrew data fix-bss --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def fix_bss(
    link_map: Path | None = typer.Option(
        None, "--link-map", help="MSVC link map for library data owners (default: raw_link's .map)"
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite an existing generated header",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Generate BSS padding from proven extents."""
    execute_data(
        link_map=link_map,
        force=force,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
        fix_bss=True,
    )


@app.command(
    "header",
    epilog="Examples:\n\n  rebrew data header --output include/rebrew_globals.h --dry-run\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def header(
    gen_header_out: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Header output file (default: {reversed_dir}/rebrew_globals.h)",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Overwrite an existing generated header",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Generate canonical global declarations."""
    execute_data(
        gen_header_out=gen_header_out,
        force=force,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
        gen_header=True,
    )


@app.command(
    "annotate",
    epilog="Examples:\n\n  rebrew data annotate --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def annotate(
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Write accepted discovered data annotations."""
    execute_data(dry_run=dry_run, json_output=json_output, target=target, annotate=True)


layout_app = typer.Typer(
    help="Audit and repair linked data layout.", epilog="Examples: rebrew data layout audit --json"
)
app.add_typer(layout_app, name="layout")


@layout_app.command(
    "audit",
    epilog="Examples:\n\n  rebrew data layout audit --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def layout_audit(
    section: str = typer.Option(
        ".data",
        "--section",
        help="Section to audit (.data or .rdata)",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Audit linked layout using provenance and locked metadata owners."""
    execute_data(
        section=section, dry_run=dry_run, json_output=json_output, target=target, layout_audit=True
    )


@layout_app.command(
    "fill",
    epilog="Examples:\n\n  rebrew data layout fill --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def layout_fill(
    section: str = typer.Option(
        ".data",
        "--section",
        help="Section to audit (.data or .rdata)",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Fill linked layout using provenance and locked metadata owners."""
    execute_data(
        section=section, dry_run=dry_run, json_output=json_output, target=target, fill_data=True
    )


@layout_app.command(
    "own",
    epilog="Examples:\n\n  rebrew data layout own --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def layout_own(
    bss_only: bool = typer.Option(
        False, "--bss-only", help="Only BSS pads; skip initialized-region pads"
    ),
    stub_file: Path | None = typer.Option(
        None,
        "--stub-file",
        help="Stub TU whose placeholders to own (default src/link_stubs.c)",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Own linked layout using provenance and locked metadata owners."""
    execute_data(
        bss_only=bss_only,
        stub_file=stub_file,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
        own=True,
    )


@layout_app.command(
    "fix-ownership",
    epilog="Examples:\n\n  rebrew data layout fix-ownership --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def layout_fix_ownership(
    stub_file: Path | None = typer.Option(
        None,
        "--stub-file",
        help="Stub TU whose placeholders to own (default src/link_stubs.c)",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Fix-ownership linked layout using provenance and locked metadata owners."""
    execute_data(
        stub_file=stub_file,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
        fix_ownership=True,
    )


@layout_app.command(
    "converge",
    epilog="Examples:\n\n  rebrew data layout converge --dry-run --json\n\nMetadata writes use locked writers. Storage ownership and byte verification remain separate.",
)
def layout_converge(
    stub_file: Path | None = typer.Option(
        None,
        "--stub-file",
        help="Stub TU whose placeholders to own (default src/link_stubs.c)",
    ),
    rounds: int = typer.Option(
        1,
        "--rounds",
        help="With --converge: measure/adjust rounds in this invocation.  The built binary is "
        "not re-linked between them, so an extra round re-measures the same build; rebuild and "
        "re-run for a new fixed point",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Converge linked layout using provenance and locked metadata owners."""
    execute_data(
        stub_file=stub_file,
        rounds=rounds,
        dry_run=dry_run,
        json_output=json_output,
        target=target,
        converge=True,
    )


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_cli

    run_cli(app)


if __name__ == "__main__":
    main_entry()
