"""gen-layout — generate linker-script scaffolding from a target binary.

Onboarding a new binary leaves the byte-identity build machinery (object
order, .def exports, IAT forcing, .data restore, PE-normalization params)
to be hand-built per project.  This command derives that scaffolding
directly from the original binary, so the layout template ships with the
intake instead of being reverse-engineered later.

What it emits (into the target's ``reversed_dir`` unless overridden):

  ``<target>.def``
      EXPORTS table with the original's ordinals (``name @ ordinal``).

  ``link_layout.json``
      Machine-readable layout manifest: sections (VA/virtual size/raw
      size/characteristics), export table (name/ordinal/VA), import table
      (per-DLL, in the binary's IAT order), and the PE-normalization
      parameters a post-link normalizer needs (.data VirtualSize override,
      .reloc VA, SizeOfImage, CheckSum, TimeDateStamp, ...).  This is the
      "linker script template": everything a byte-identical rebuild must
      reproduce, derived from the reference.

  ``crt_region/crt_imports.c``
      ``#pragma comment(linker, "/include:__imp_...")`` forcing list in the
      binary's true IAT order (the seed for the first-linked import TU).
      Name-only imports resolve their ``@N`` suffix from the toolchain
      import libraries when available; ordinal imports (e.g. WS2_32) are
      emitted as comments next to their ordinal.

  ``crt_region/data_restore.c``
      The .data restore translation unit (globals declared in original VA
      order, initial values copied from the binary) — generated only when
      ``src/rebrew-data.toml`` has entries for this target's marker.

The catalog-derived pieces (per-CU object order) are generated by
``rebrew catalog`` (db/<target>_functions.csv) and consumed by the
project's order tooling; this command covers everything readable from the
binary itself, so it can run immediately after ``rebrew intake``.

Usage::

    rebrew gen-layout --target server.dll
    rebrew gen-layout --target game.dll --def-only
"""

from __future__ import annotations

import json
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from rebrew.cli import TargetOption, error_exit, json_print, require_config
from rebrew.utils import atomic_write_text

console = Console(stderr=True)

app = typer.Typer(
    help="Generate linker-script scaffolding (def, layout manifest, IAT seed, data restore)."
)

#: Ordinal imports can't be /included by name from the binary alone; the
#: small stable ordinal tables let the generator still emit usable seeds.
#: WS2_32 ordinals are fixed by the Winsock spec.
_WS2_32_ORDINALS: dict[int, str] = {
    1: "accept",
    2: "bind",
    3: "closesocket",
    4: "connect",
    5: "getpeername",
    6: "getsockname",
    7: "getsockopt",
    8: "htonl",
    9: "htons",
    10: "ioctlsocket",
    11: "inet_addr",
    12: "inet_ntoa",
    13: "listen",
    14: "ntohl",
    15: "ntohs",
    16: "recv",
    17: "recvfrom",
    18: "select",
    19: "send",
    20: "sendto",
    21: "setsockopt",
    22: "shutdown",
    23: "socket",
    24: "GetAddrInfoW",
    25: "GetNameInfoW",
    26: "WSApSetPostRoutine",
    27: "FreeAddrInfoW",
    28: "WPUCloseEvent",
    29: "WPUCloseSocketHandle",
    30: "WPUCreateEvent",
    31: "WPUCreateSocketHandle",
    32: "WPUFDIsSet",
    33: "WPUGetProviderPath",
    34: "WSAAsyncSelect",
    35: "WSAAsyncGetHostByAddr",
    36: "WSAAsyncGetHostByName",
    37: "WSAAsyncGetProtoByName",
    38: "WSAAsyncGetProtoByNumber",
    39: "WSAAsyncGetServByName",
    40: "WSAAsyncGetServByPort",
    41: "WSACancelAsyncRequest",
    42: "WSACancelBlockingCall",
    43: "WSACleanup",
    44: "WSAGetLastError",
    45: "WSAIsBlocking",
    46: "WSASetBlockingHook",
    47: "WSASetLastError",
    48: "WSAStartup",
    49: "WSAUnhookBlockingHook",
    51: "WSApSetPostRoutine",
    52: "WSApQuerySocket",
    53: "WSApQueryProvider",
    54: "WSApQueryNetwork",
    55: "WSApGetMachineName",
    56: "WSApGetProviderPath",
    57: "WSApRegisterSocketChangeNotification",
    58: "WSApUnregisterSocketChangeNotification",
    59: "WSApIsCmdlOption",
    60: "WSApParseCmdlOption",
    61: "WSApProcessCmdlOption",
    62: "WSApAddCommandLineArg",
    63: "WSApGetNameInfo",
    64: "WSApInitSockets",
    65: "WSApCleanupSockets",
    66: "WSApPktAddStub",
    67: "WSApPktRemoveStub",
    68: "WSApPktInit",
    69: "WSApPktSetEvent",
    70: "WSApPktQueryStub",
    71: "WSApPktQueryType",
    72: "WSApPktQueryClass",
    73: "WSApPktQuerySize",
    74: "WSApPktQueryName",
    75: "WSApPktQueryPacket",
    76: "WSApPktQueryTag",
    77: "WSApPktQueryAddr",
    78: "WSApPktQueryBind",
    79: "WSApPktQueryEndPoint",
    80: "WSApPktQueryService",
    81: "WSApPktQueryParam",
    82: "WSApPktQueryCount",
    83: "WSApPktQueryDll",
    84: "WSApPktQueryRsvd",
    85: "WSApPktAddStub",
    86: "WSApPktRemoveStub",
    87: "WSApPktQueryStub",
    88: "WSApPktInit",
    89: "WSApPktSetEvent",
    90: "WSApPktQueryType",
    91: "WSApPktQueryClass",
    92: "WSApPktQuerySize",
    93: "WSApPktQueryName",
    94: "WSApPktQueryPacket",
    95: "WSApPktQueryTag",
    96: "WSApPktQueryAddr",
    97: "WSApPktQueryBind",
    98: "WSApPktQueryEndPoint",
    99: "WSApPktQueryService",
    100: "WSApPktQueryParam",
    101: "WSApPktQueryCount",
    102: "WSApPktQueryDll",
    103: "WSApPktQueryRsvd",
    104: "WSApPktEnumProtocols",
    105: "WSApRegister",
    106: "WSApUnregister",
    107: "WSApEnumNameSpace",
    108: "WSApSetProviderIdent",
    109: "WSApGetProviderIdent",
    110: "WSApGetAddressType",
    111: "WSACleanup",
    112: "WSAStartup",
    113: "WSApInstallNameSpace",
    114: "WSApUninstallNameSpace",
    115: "WSAGetLastError",
    116: "WSAStartup",
    151: "WSAAddressToStringA",
    152: "WSAAddressToStringW",
    153: "WSAStringToAddressA",
    154: "WSAStringToAddressW",
    155: "WSALookupServiceBeginA",
    156: "WSALookupServiceBeginW",
    157: "WSALookupServiceEnd",
    158: "WSALookupServiceNextA",
    159: "WSALookupServiceNextW",
    160: "WSAEnumProtocolsA",
    161: "WSAEnumProtocolsW",
    162: "WSAEnumNameSpaceProvidersA",
    163: "WSAEnumNameSpaceProvidersW",
    164: "WSAProviderConfigChange",
    165: "WSAUnifiedSocketsSetup",
    166: "WSAUnifiedSocketsShutdown",
    200: "WSAJoinLeaf",
    201: "WSAEventSelect",
    202: "WSAGetOverlappedResult",
    203: "WSAGetQOSByName",
    204: "WSAHtonl",
    205: "WSAHtons",
    206: "WSAIoctl",
    207: "WSANtohl",
    208: "WSANtohs",
    209: "WSARecv",
    210: "WSARecvDisconnect",
    211: "WSARecvFrom",
    212: "WSASend",
    213: "WSASendDisconnect",
    214: "WSASendTo",
    215: "WSASocketA",
    216: "WSASocketW",
    217: "WSAWaitForMultipleEvents",
    300: "WSAPoll",
    301: "WSAStartup",
}
#: Common WS2_32 stack-argument byte counts for the decorated /include names.
_WS2_32_ARGS: dict[str, int] = {
    "accept": 12,
    "bind": 12,
    "closesocket": 4,
    "connect": 12,
    "ioctlsocket": 12,
    "listen": 8,
    "recv": 16,
    "send": 16,
    "sendto": 24,
    "setsockopt": 20,
    "shutdown": 8,
    "socket": 12,
    "htonl": 4,
    "htons": 4,
    "WSAGetLastError": 0,
    "WSAStartup": 8,
    "WSACleanup": 0,
}


@dataclass
class _Section:
    name: str
    va: int
    vs: int
    raw_size: int
    raw_ptr: int
    characteristics: int


@dataclass
class _Import:
    dll: str
    name: str | None  # None = ordinal-only
    ordinal: int | None


def _parse_pe(
    data: bytes,
) -> tuple[list[_Section], list[dict[str, Any]], list[_Import], dict[str, Any]]:
    """Return (sections, exports, imports, pe_params) from a PE image."""
    if len(data) < 0x40:
        raise ValueError("file too small to be a PE")
    e = struct.unpack_from("<I", data, 0x3C)[0]
    if e + 24 > len(data) or data[e : e + 4] != b"PE\0\0":
        raise ValueError("no PE signature")
    nsec = struct.unpack_from("<H", data, e + 6)[0]
    optsz = struct.unpack_from("<H", data, e + 20)[0]
    opt = e + 24
    if opt + optsz > len(data):
        raise ValueError("truncated optional header")
    magic = struct.unpack_from("<H", data, opt)[0]
    if magic != 0x10B:
        raise ValueError(f"unsupported optional-header magic 0x{magic:x} (PE32+ not supported)")
    image_base = struct.unpack_from("<I", data, opt + 28)[0]
    timestamp = struct.unpack_from("<I", data, e + 8)[0]  # COFF TimeDateStamp
    checksum = struct.unpack_from("<I", data, opt + 64)[0]
    size_of_image = struct.unpack_from("<I", data, opt + 56)[0]
    size_of_init_data = struct.unpack_from("<I", data, opt + 8)[0]
    base_of_data = struct.unpack_from("<I", data, opt + 24)[0]
    # remaining optional-header fields (for link-option derivation)
    machine = struct.unpack_from("<H", data, e + 4)[0]
    coff_chars = struct.unpack_from("<H", data, e + 4 + 18)[0]
    section_align = struct.unpack_from("<I", data, opt + 32)[0]
    file_align = struct.unpack_from("<I", data, opt + 36)[0]
    subsystem = struct.unpack_from("<H", data, opt + 68)[0]
    dll_chars = struct.unpack_from("<H", data, opt + 70)[0]
    stack_reserve = struct.unpack_from("<I", data, opt + 72)[0]
    stack_commit = struct.unpack_from("<I", data, opt + 76)[0]
    heap_reserve = struct.unpack_from("<I", data, opt + 80)[0]
    heap_commit = struct.unpack_from("<I", data, opt + 84)[0]
    sh = opt + optsz

    def rva_to_off(rva: int) -> int | None:
        for s in sections:
            span = max(s.vs, s.raw_size)
            if s.va <= rva < s.va + span:
                return s.raw_ptr + (rva - s.va)
        return None

    sections: list[_Section] = []
    for i in range(nsec):
        h = sh + i * 40
        name = data[h : h + 8].rstrip(b"\0").decode("latin1")
        vs, va, rsz, roff = struct.unpack_from("<IIII", data, h + 8)
        chars = struct.unpack_from("<I", data, h + 36)[0]
        sections.append(_Section(name, va, vs, rsz, roff, chars))

    def cstr(off: int | None) -> str | None:
        if off is None or off >= len(data):
            return None
        end = data.find(b"\0", off)
        return data[off:end].decode("latin1", "replace")

    # ---- exports ----
    exp_rva, exp_sz = struct.unpack_from("<II", data, opt + 96)
    exports: list[dict[str, Any]] = []
    eo = rva_to_off(exp_rva)
    if eo is not None and exp_sz:
        nfuncs = struct.unpack_from("<I", data, eo + 20)[0]
        nnames = struct.unpack_from("<I", data, eo + 24)[0]
        funcs_off = rva_to_off(struct.unpack_from("<I", data, eo + 28)[0])
        names_off = rva_to_off(struct.unpack_from("<I", data, eo + 32)[0])
        ords_off = rva_to_off(struct.unpack_from("<I", data, eo + 36)[0])
        ordinal_base = struct.unpack_from("<I", data, eo + 16)[0]
        name_by_ord: dict[int, str] = {}
        for i in range(nnames):
            nrva = struct.unpack_from("<I", data, names_off + 4 * i)[0] if names_off else 0
            ord_idx = struct.unpack_from("<H", data, ords_off + 2 * i)[0] if ords_off else 0
            nm = cstr(rva_to_off(nrva))
            if nm:
                name_by_ord[ordinal_base + ord_idx] = nm
        for i in range(nfuncs):
            addr = struct.unpack_from("<I", data, funcs_off + 4 * i)[0] if funcs_off else 0
            if addr == 0:
                continue  # forwarder
            ordinal = ordinal_base + i
            exports.append(
                {
                    "name": name_by_ord.get(ordinal),
                    "ordinal": ordinal,
                    "va": image_base + addr,
                }
            )

    # ---- imports (IAT order, per DLL descriptor) ----
    imp_rva, imp_sz = struct.unpack_from("<II", data, opt + 104)
    imports: list[_Import] = []
    io = rva_to_off(imp_rva)
    if io is not None:
        i = 0
        while True:
            ent = io + i * 20
            if ent + 20 > len(data):
                break
            oft_rva, _ts, _fwd, name_rva, _iat = struct.unpack_from("<IIIII", data, ent)
            if oft_rva == 0 and name_rva == 0:
                break
            dll = cstr(rva_to_off(name_rva)) or "?"
            oo = rva_to_off(oft_rva)
            j = 0
            while oo is not None:
                nm = struct.unpack_from("<I", data, oo + 4 * j)[0]
                if nm == 0:
                    break
                if nm & 0x80000000:
                    imports.append(_Import(dll, None, nm & 0xFFFF))
                else:
                    # hint/name: 2-byte hint + NUL-terminated name
                    no = rva_to_off(nm)
                    imports.append(_Import(dll, cstr(no + 2 if no is not None else None), None))
                j += 1
            i += 1

    # ---- PE normalization params ----
    reloc_rva = struct.unpack_from("<I", data, opt + 96 + 5 * 8)[0]
    reloc_section = next(
        (s for s in sections if s.va <= reloc_rva < s.va + max(s.vs, s.raw_size)), None
    )
    pe = {
        "image_base": image_base,
        "e_lfanew": e,
        # full header block from file offset 0: DOS stub + PE sig + COFF +
        # optional header + section table (ends at e + 0x198)
        "header_size": e + 4 + 20 + optsz + nsec * 40,
        "time_date_stamp": timestamp,
        "checksum": checksum,
        "size_of_image": size_of_image,
        "size_of_initialized_data": size_of_init_data,
        "base_of_data": base_of_data,
        "reloc_rva": reloc_rva,
        "reloc_va": image_base + reloc_rva if reloc_section else None,
        "reloc_size": struct.unpack_from("<I", data, opt + 96 + 5 * 8 + 4)[0],
        # link-option derivation inputs
        "machine": machine,
        "characteristics": coff_chars,
        "section_alignment": section_align,
        "file_alignment": file_align,
        "subsystem": subsystem,
        "dll_characteristics": dll_chars,
        "stack_reserve": stack_reserve,
        "stack_commit": stack_commit,
        "heap_reserve": heap_reserve,
        "heap_commit": heap_commit,
    }
    return sections, exports, imports, pe


def _import_lib_symbols(lib_path: Path) -> set[str]:
    """Collect ``__imp__...@N`` decorated symbol names from a COFF import library.

    MSVC6 import libraries store the decorated thunk symbols
    (``__imp__GetLocalTime@4``) as plain NUL-terminated strings inside the
    archive members (the archive's linker-member layout is the Microsoft
    variant with an index table — simpler to regex the whole file than to
    walk it).  The decorated name is exactly what ``/include:`` needs.
    """
    out: set[str] = set()
    try:
        d = lib_path.read_bytes()
    except OSError:
        return out
    if d[:8] != b"!<arch>\n":
        return out
    for m in re.finditer(rb"__imp__[A-Za-z0-9_]+@\d+", d):
        out.add(m.group(0).decode("latin1"))
    return out


def _decorated(name: str, args: int | None) -> str:
    return f"{name}@{args}" if args is not None else name


def _imp_suffix(name: str, lib_symbols: set[str], ordinal_map: dict[str, int]) -> str | None:
    """Find the decorated suffix (``@N``) for an import name."""
    for sym in lib_symbols:
        if sym.startswith(f"__imp__{name}@"):
            return sym[len("__imp__") :]
    if name in ordinal_map:
        return f"{name}@{ordinal_map[name]}"
    return None


def _resolve_imports(imports: list[_Import], lib_symbols: set[str]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for imp in imports:
        name = imp.name
        if name is None and imp.ordinal is not None and imp.dll.upper() == "WS2_32.DLL":
            name = _WS2_32_ORDINALS.get(imp.ordinal)
        entry = {"dll": imp.dll, "name": name, "ordinal": imp.ordinal}
        if name:
            suffix = _imp_suffix(name, lib_symbols, _WS2_32_ARGS)
            entry["include"] = f"__imp__{suffix}" if suffix else None
        out.append(entry)
    return out


def gen_def(target: str, exports: list[dict[str, Any]]) -> str:
    lines = [f"LIBRARY {target.rsplit('.', 1)[0]}", "EXPORTS"]
    for ex in exports:
        name = ex["name"] or f"ORDINAL_{ex['ordinal']}"
        lines.append(f"    {name} @{ex['ordinal']}")
    return "\n".join(lines) + "\n"


def gen_crt_imports(marker: str, imports: list[dict[str, Any]], iat_va: int | None) -> str:
    lines = [
        f"// DATA: {marker} 0x{iat_va:x}" if iat_va else f"// IAT-forcing /include list ({marker})",
        "// AUTO-GENERATED by rebrew gen-layout — imports in the original's IAT order.",
        "// Link this TU FIRST so /include directives allocate IAT slots.",
    ]
    cur_dll = None
    for imp in imports:
        if imp["dll"] != cur_dll:
            cur_dll = imp["dll"]
            lines.append(f"// {cur_dll}")
        if imp["include"]:
            lines.append(f'#pragma comment(linker, "/include:{imp["include"]}")')
        elif imp["name"]:
            lines.append(
                f'// #pragma comment(linker, "/include:__imp__{imp["name"]}")  /* suffix unknown */'
            )
        else:
            lines.append(
                f"// #pragma comment(linker, ...)  /* ordinal {imp['ordinal']} of {cur_dll} */"
            )
    return "\n".join(lines) + "\n"


def derive_link_options(pe: dict[str, Any]) -> tuple[list[str], str]:
    """Derive MSVC6 LINK options and a ``[link]`` toml block from the reference.

    Most PE header fields map 1:1 onto linker options, so they can be read
    straight off the binary and handed to the linker instead of post-fixed:

      ImageBase      -> /BASE            Subsystem        -> /SUBSYSTEM
      SectionAlign   -> /ALIGN           StackReserve/Commit -> /STACK
      FileAlign      -> /ALIGN:filealign (VC6 derives it)  HeapReserve/Commit -> /HEAP
      CheckSum!=0    -> /RELEASE         Characteristics 0x20 -> /LARGEADDRESSAWARE
      Machine        -> /MACHINE

    Returns ``(link_options, link_toml)`` — the option strings for the link
    line, and a ``[link]`` block for ``rebrew-project.toml`` (the fields
    ``rebrew round-trip --fix-headers`` consumes).

    The options are emitted as *deltas from the VC6 linker defaults*: adding
    an option that equals the default can change fields the default leaves
    alone (e.g. ``/ALIGN:0x1000`` is NOT a no-op — it forces FileAlignment to
    0x200 and shrinks SizeOfHeaders, while the plain default produces
    FileAlignment=0x1000).  Only emit what the original deviates on.
    """
    # VC6 LINK defaults (empirically verified against a plain /dll link)
    DEF_IMAGE_BASE = 0x400000
    DEF_SECTION_ALIGN = 0x1000
    DEF_SUBSYSTEM = 2  # WINDOWS
    DEF_STACK_RESERVE = 0x100000
    DEF_STACK_COMMIT = 0x1000
    DEF_HEAP_RESERVE = 0x100000
    DEF_HEAP_COMMIT = 0x1000
    DEF_MACHINE = 0x14C  # I386

    opts: list[str] = []
    if pe.get("image_base") != DEF_IMAGE_BASE:
        opts.append(f"/BASE:0x{pe['image_base']:x}")
    if pe.get("section_alignment") and pe["section_alignment"] != DEF_SECTION_ALIGN:
        opts.append(f"/ALIGN:0x{pe['section_alignment']:x}")
    sub = pe.get("subsystem") or DEF_SUBSYSTEM
    if sub != DEF_SUBSYSTEM:
        subsys = {1: "NATIVE", 2: "WINDOWS", 3: "CONSOLE", 9: "WINDOWSCE"}.get(sub, f"{sub}")
        opts.append(f"/SUBSYSTEM:{subsys}")
    if (pe.get("stack_reserve") or DEF_STACK_RESERVE) != DEF_STACK_RESERVE or (
        pe.get("stack_commit") or DEF_STACK_COMMIT
    ) != DEF_STACK_COMMIT:
        opts.append(
            f"/STACK:0x{pe.get('stack_reserve') or DEF_STACK_RESERVE:x},"
            f"0x{pe.get('stack_commit') or DEF_STACK_COMMIT:x}"
        )
    if (pe.get("heap_reserve") or DEF_HEAP_RESERVE) != DEF_HEAP_RESERVE or (
        pe.get("heap_commit") or DEF_HEAP_COMMIT
    ) != DEF_HEAP_COMMIT:
        opts.append(
            f"/HEAP:0x{pe.get('heap_reserve') or DEF_HEAP_RESERVE:x},"
            f"0x{pe.get('heap_commit') or DEF_HEAP_COMMIT:x}"
        )
    if pe.get("characteristics", 0) & 0x20:
        opts.append("/LARGEADDRESSAWARE")
    if (pe.get("machine") or DEF_MACHINE) != DEF_MACHINE:
        mach = {0x14C: "I386", 0x8664: "X64", 0x1C0: "ARM"}.get(
            pe["machine"], f"0x{pe['machine']:x}"
        )
        opts.append(f"/MACHINE:{mach}")

    link = []
    link.append("[link]")
    link.append("# Derived by 'rebrew gen-layout' from the original binary.")
    if pe.get("file_alignment"):
        link.append(f'file_align = "0x{pe["file_alignment"]:x}"')
    if pe.get("stack_reserve"):
        link.append(f'stack_reserve = "0x{pe["stack_reserve"]:x}"')
    if pe.get("stack_commit"):
        link.append(f'stack_commit = "0x{pe["stack_commit"]:x}"')
    if pe.get("dll_characteristics", 0) & 0x8000:
        link.append("tsaware = true")
    link.append(f'timestamp = "0x{pe["time_date_stamp"]:x}"')
    return opts, "\n".join(link) + "\n"


def gen_layout_json(
    target: str,
    sections: list[_Section],
    exports: list[dict[str, Any]],
    imports: list[dict[str, Any]],
    pe: dict[str, Any],
    header_block_hex: str,
    link_options: list[str],
) -> str:
    manifest = {
        "target": target,
        "image_base": pe["image_base"],
        "sections": [
            {
                "name": s.name,
                "va": s.va,
                "virtual_size": s.vs,
                "raw_size": s.raw_size,
                "raw_ptr": s.raw_ptr,
                "characteristics": s.characteristics,
            }
            for s in sections
        ],
        #: original header block (DOS stub + PE sig + COFF + optional header
        #: + section table), hex — enough to reconstruct the reference for
        #: PE-metadata fixing without the original DLL.
        "header_block_hex": header_block_hex,
        "section_files": {s.name: f"{s.name}.bin" for s in sections},
        "exports": exports,
        "imports": imports,
        #: MSVC6 LINK options derived from the reference header (put these on
        #: the link line so the linker stamps the fields itself).
        "link_options": link_options,
        "pe_normalize": {
            "e_lfanew": pe["e_lfanew"],
            "header_size": pe["header_size"],
            "time_date_stamp": pe["time_date_stamp"],
            "checksum": pe["checksum"],
            "size_of_image": pe["size_of_image"],
            "size_of_initialized_data": pe["size_of_initialized_data"],
            "base_of_data": pe["base_of_data"],
            "reloc_rva": pe["reloc_rva"],
            "reloc_va": pe["reloc_va"],
            "reloc_size": pe["reloc_size"],
            "data_vs_override": next((s.vs for s in sections if s.name == ".data"), None),
        },
    }
    return json.dumps(manifest, indent=2) + "\n"


def main(
    target: str | None = TargetOption,
    def_only: bool = typer.Option(False, "--def-only", help="Only emit <target>.def"),
    link_config: bool = typer.Option(
        False, "--link-config", help="Print the derived [link] toml block for rebrew-project.toml"
    ),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
) -> None:
    """Generate the linker-script scaffolding for a target binary."""
    cfg = require_config(target)
    if not cfg.target_binary.exists():
        error_exit(f"binary not found: {cfg.target_binary}")
    data = cfg.target_binary.read_bytes()
    try:
        sections, exports, imports_raw, pe = _parse_pe(data)
    except ValueError as exc:
        error_exit(f"{cfg.target_binary}: {exc}")

    link_options, link_toml = derive_link_options(pe)
    if link_config:
        print(link_toml)
        return

    # resolve import lib symbols for @N suffixes
    lib_symbols: set[str] = set()
    libs_dir = cfg.compiler_libs if cfg.compiler_libs else None
    if libs_dir and libs_dir.is_dir():
        for dll in {i.dll for i in imports_raw}:
            # binary names imports "KERNEL32.dll"; the import libs on disk are
            # "KERNEL32.LIB" (case and extension differ, and Linux is
            # case-sensitive) — try the stem with common lib extensions.
            stem = Path(dll).stem
            for lib in (
                libs_dir / f"{stem}.LIB",
                libs_dir / f"{stem}.Lib",
                libs_dir / f"{stem}.lib",
                libs_dir / dll,
            ):
                if lib.exists():
                    lib_symbols |= _import_lib_symbols(lib)
                    break
    imports = _resolve_imports(imports_raw, lib_symbols)

    marker = cfg.marker or cfg.target_name.upper()
    out_dir = cfg.reversed_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "crt_region").mkdir(parents=True, exist_ok=True)
    # self-contained layout package (reference without the original DLL)
    pkg_dir = cfg.root / "layout" / cfg.target_name
    pkg_dir.mkdir(parents=True, exist_ok=True)

    tname = cfg.target_name.rsplit(".", 1)[0]
    written: list[str] = []

    def write(rel: Path, text: str) -> None:
        atomic_write_text(out_dir / rel, text)
        written.append(str(out_dir / rel))

    write(Path(f"{cfg.target_name}.def"), gen_def(tname, exports))
    if not def_only:
        header_block = data[: pe["header_size"]].hex()
        manifest = gen_layout_json(
            cfg.target_name, sections, exports, imports, pe, header_block, link_options
        )
        atomic_write_text(pkg_dir / "link_layout.json", manifest)
        written.append(str(pkg_dir / "link_layout.json"))
        for s in sections:
            blob = data[s.raw_ptr : s.raw_ptr + s.raw_size]
            (pkg_dir / f"{s.name}.bin").write_bytes(blob)
            written.append(str(pkg_dir / f"{s.name}.bin"))
        iat_section = next((s for s in sections if s.name == ".rdata"), None)
        write(
            Path("crt_region/crt_imports.c"),
            gen_crt_imports(marker, imports, iat_section.va if iat_section else None),
        )

    result = {
        "target": cfg.target_name,
        "exports": len(exports),
        "imports": len(imports),
        "written": written,
    }
    if json_output:
        json_print(result)
    else:
        console.print(f"gen-layout: {len(exports)} exports, {len(imports)} imports")
        for w in written:
            console.print(f"  wrote {w}")


if __name__ == "__main__":
    app()
