"""gen-link-stubs — BSS placeholder TU from the data metadata.

A byte-identity build needs the raw link's ``.data`` VirtualSize to reach
the reference's (the BSS tail lives beyond the raw size).  This command
emits a ``link_stubs.c``-style TU: a non-tentative zero-init placeholder for
every ``.data`` symbol in the data metadata (``src/rebrew-data.toml``), so
the linker emits them into ``.data``'s BSS (raw=0, VS grows), plus a
calibratable ``g_bss_tail`` pad.

Run ``rebrew calibrate-bss`` afterwards to size the tail so the raw link's
``.data`` VirtualSize matches the reference exactly.

Usage:
    rebrew gen-link-stubs [--data-metadata src/rebrew-data.toml] [--out src/link_stubs.c]
"""

from __future__ import annotations

import tomllib
from pathlib import Path

import typer
from rich.console import Console

from rebrew.cli import error_exit, json_print

console = Console(stderr=True)

app = typer.Typer(
    help="Generate a link_stubs.c-style BSS placeholder TU from the data metadata.",
    rich_markup_mode="rich",
)

_TAIL_DEFAULT = 0x400000  # generous; `rebrew calibrate-bss` fixes it


def load_data_symbols(metadata: Path) -> list[tuple[int, str, str]]:
    """Sorted ``(address, name, type)`` of the ``.data`` symbols in *metadata*."""
    with open(metadata, "rb") as f:
        doc = tomllib.load(f)
    out: list[tuple[int, str, str]] = []
    for key, val in doc.items():
        if val.get("section") != ".data":
            continue
        try:
            addr = int(key.rsplit(".", 1)[1], 16)
        except (IndexError, ValueError):
            continue
        name = val.get("name") or f"g_data_{addr:x}"
        out.append((addr, str(name), str(val.get("type", "int"))))
    out.sort()
    return out


def gen_link_stubs(metadata: Path) -> str:
    """The BSS placeholder TU text."""
    symbols = load_data_symbols(metadata)
    lines = [
        "/* link_stubs.c - AUTO-GENERATED by rebrew gen-link-stubs",
        " * Non-tentative zero-init placeholders for every .data symbol in the",
        " * data metadata, so the linker emits them into .data's BSS (raw=0,",
        " * VirtualSize grows).  The g_bss_tail pad extends VS to the reference;",
        " * size it with: rebrew calibrate-bss",
        " * DO NOT hand-edit.  Regenerate with: rebrew gen-link-stubs",
        " */",
        "#include <time.h>",
        "",
        "/* .data symbol placeholders (zero-init -> .data BSS) */",
    ]
    for _addr, name, _type in symbols:
        lines.append(f"char {name}[1] = {{0}};")
    lines.append("")
    lines.append("/* BSS tail pad: grows .data VS toward the reference (calibrate-bss) */")
    lines.append(f"unsigned char g_bss_tail[0x{_TAIL_DEFAULT:x}] = {{0}};")
    lines.append("")
    return "\n".join(lines) + "\n"


@app.callback(invoke_without_command=True)
def main(
    data_metadata: Path = typer.Option(
        Path("src/rebrew-data.toml"), "--data-metadata", help="Data metadata toml path"
    ),
    out: Path = typer.Option(Path("src/link_stubs.c"), "--out", help="Output TU path"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Print instead of writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
) -> None:
    """Generate the BSS placeholder TU."""
    root = Path.cwd()
    metadata = data_metadata if data_metadata.is_absolute() else root / data_metadata
    if not metadata.exists():
        error_exit(f"data metadata not found: {metadata}")
    content = gen_link_stubs(metadata)
    if dry_run or json_output:
        if json_output:
            json_print(
                {
                    "symbols": len(load_data_symbols(metadata)),
                    "tail": f"0x{_TAIL_DEFAULT:x}",
                    "generated": content,
                }
            )
        else:
            print(content)
        return
    target = out if out.is_absolute() else root / out
    target.write_text(content, encoding="utf-8")
    console.print(f"[green]gen-link-stubs:[/] wrote {target}")
    console.print("  next: rebrew calibrate-bss to size g_bss_tail")


def main_entry() -> None:
    """Run the Typer CLI application."""
    app()


if __name__ == "__main__":
    main_entry()
