"""gen-layout — generate linker-script scaffolding from a target binary.

Onboarding a new binary leaves the byte-identity build machinery (object
order, .def exports, IAT forcing, .data restore, PE-normalization params)
to be hand-built per project.  This command derives that scaffolding
directly from the original binary, so the layout template ships with the
intake instead of being reverse-engineered later.

What it emits (into the target's ``reversed_dir`` unless overridden):

  ``<target>.def``
      EXPORTS table with the original's ordinals (``name @ ordinal``).

  ``layout/<target>/`` (text-only layout package, committed to git)
      Everything ``rebrew postlink --layout`` needs to reconstruct the
      reference with **zero binary blobs at rest**: a structured
      ``rebrew-layout.toml`` (image base, sections with raw pointers, exports,
      imports with reference IAT-slot VAs, export-directory stamp) plus hex
      dumps of the opaque linker-stamped regions (header block, IAT,
      import bookkeeping + drift-check prefix, ``.data`` raw, ``.reloc``
      content) and sparse ``.text`` maps (data operands, E8/E9 call
      targets).  The original DLL is not needed at build time.

  ``crt_region/crt_imports.c``
      ``#pragma comment(linker, "/include:__imp_...")`` forcing list in the
      binary's true IAT order (the seed for the first-linked import TU).
      Name-only imports resolve their ``@N`` suffix from the toolchain
      import libraries when available; ordinal imports (e.g. WS2_32) are
      emitted as comments next to their ordinal.

  ``crt_region/data_restore.c``
      The .data restore translation unit (globals declared in original VA
      order, initial values copied from the binary) — generated only when
      ``src/rebrew-data.toml`` has entries for this target's marker.

The catalog-derived pieces (per-CU object order) are generated by
``rebrew catalog`` (db/<target>_functions.csv) and consumed by the
project's order tooling; this command covers everything readable from the
binary itself, so it can run immediately after ``rebrew intake``.

Usage::

    rebrew gen-layout --target server.dll
    rebrew gen-layout --target game.dll --def-only
"""

from __future__ import annotations

import re
import struct
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from rebrew.cli import TargetOption, error_exit, json_print, require_config
from rebrew.layout_meta import LayoutMetadata, extract_layout, write_package
from rebrew.pe_headers import pe_layout, pe_lfanew, sections_at
from rebrew.utils import atomic_write_text, container_runtime

console = Console(stderr=True)

#: Cap on import name-table / descriptor slots read from one PE.  A missing
#: null terminator would otherwise walk past EOF into ``struct.error`` or
#: spin on a wrapped offset; matches ``pe_symbols._MAX_TABLE_ENTRIES``.
_MAX_IMPORT_SLOTS = 65536

#: Cap on export AddressOfFunctions / AddressOfNames entries.  A forged
#: NumberOfNames/NumberOfFunctions of ``0xFFFFFFFF`` would otherwise hang in
#: ``range()`` or raise ``struct.error`` past EOF.
_MAX_EXPORT_ENTRIES = 65536

app = typer.Typer(
    help="Generate linker-script scaffolding (def, layout manifest, IAT seed, data restore)."
)

#: Ordinal imports can't be /included by name from the binary alone; the
#: small stable ordinal tables let the generator still emit usable seeds.
#: WS2_32 ordinals are fixed by the Winsock spec.
_WS2_32_ORDINALS: dict[int, str] = {
    # Ordinals fixed by the Winsock spec (verified against the export table
    # of the classic ws2_32.dll — Wine 1.8's ws2_32.spec matches the Windows
    # 2000/XP-era DLL, and the 1-23 / 51-57 / 101-116 / 151 ranges stayed
    # stable through Windows 10).  The previous table was a garbled blend of
    # Win95-era guesses and modern ordinals: WSAStartup appeared at FOUR
    # ordinals (48/112/116/301) and the 51-57 block claimed internal WSAp*
    # helpers where the real DLL exports gethostbyaddr & co.
    1: "accept",
    2: "bind",
    3: "closesocket",
    4: "connect",
    5: "getpeername",
    6: "getsockname",
    7: "getsockopt",
    8: "htonl",
    9: "htons",
    10: "ioctlsocket",
    11: "inet_addr",
    12: "inet_ntoa",
    13: "listen",
    14: "ntohl",
    15: "ntohs",
    16: "recv",
    17: "recvfrom",
    18: "select",
    19: "send",
    20: "sendto",
    21: "setsockopt",
    22: "shutdown",
    23: "socket",
    51: "gethostbyaddr",
    52: "gethostbyname",
    53: "getprotobyname",
    54: "getprotobynumber",
    55: "getservbyname",
    56: "getservbyport",
    57: "gethostname",
    101: "WSAAsyncSelect",
    102: "WSAAsyncGetHostByAddr",
    103: "WSAAsyncGetHostByName",
    104: "WSAAsyncGetProtoByNumber",
    105: "WSAAsyncGetProtoByName",
    106: "WSAAsyncGetServByPort",
    107: "WSAAsyncGetServByName",
    108: "WSACancelAsyncRequest",
    109: "WSASetBlockingHook",
    110: "WSAUnhookBlockingHook",
    111: "WSAGetLastError",
    112: "WSASetLastError",
    113: "WSACancelBlockingCall",
    114: "WSAIsBlocking",
    115: "WSAStartup",
    116: "WSACleanup",
    151: "__WSAFDIsSet",
}
#: Common WS2_32 stack-argument byte counts for the decorated /include names.
_WS2_32_ARGS: dict[str, int] = {
    "accept": 12,
    "bind": 12,
    "closesocket": 4,
    "connect": 12,
    "ioctlsocket": 12,
    "listen": 8,
    "recv": 16,
    "send": 16,
    "sendto": 24,
    "setsockopt": 20,
    "shutdown": 8,
    "socket": 12,
    "htonl": 4,
    "htons": 4,
    "WSAGetLastError": 0,
    "WSAStartup": 8,
    "WSACleanup": 0,
}


@dataclass
class _Section:
    name: str
    va: int
    vs: int
    raw_size: int
    raw_ptr: int
    characteristics: int


@dataclass
class _Import:
    dll: str
    name: str | None  # None = ordinal-only
    ordinal: int | None


def parse_pe(
    data: bytes,
) -> tuple[list[_Section], list[dict[str, Any]], list[_Import], dict[str, Any]]:
    """Return (sections, exports, imports, pe_params) from a PE image."""
    if len(data) < 0x40:
        raise ValueError("file too small to be a PE")
    e = pe_lfanew(data)
    if e is None or e + 24 > len(data):
        raise ValueError("no PE signature")
    nsec = struct.unpack_from("<H", data, e + 6)[0]
    optsz = struct.unpack_from("<H", data, e + 20)[0]
    opt = e + 24
    if opt + optsz > len(data):
        raise ValueError("truncated optional header")
    magic = struct.unpack_from("<H", data, opt)[0]
    if magic != 0x10B:
        raise ValueError(f"unsupported optional-header magic 0x{magic:x} (PE32+ not supported)")
    image_base = struct.unpack_from("<I", data, opt + 28)[0]
    timestamp = struct.unpack_from("<I", data, e + 8)[0]  # COFF TimeDateStamp
    checksum = struct.unpack_from("<I", data, opt + 64)[0]
    size_of_image = struct.unpack_from("<I", data, opt + 56)[0]
    size_of_init_data = struct.unpack_from("<I", data, opt + 8)[0]
    base_of_data = struct.unpack_from("<I", data, opt + 24)[0]
    # remaining optional-header fields (for link-option derivation)
    machine = struct.unpack_from("<H", data, e + 4)[0]
    coff_chars = struct.unpack_from("<H", data, e + 4 + 18)[0]
    section_align = struct.unpack_from("<I", data, opt + 32)[0]
    file_align = struct.unpack_from("<I", data, opt + 36)[0]
    subsystem = struct.unpack_from("<H", data, opt + 68)[0]
    dll_chars = struct.unpack_from("<H", data, opt + 70)[0]
    stack_reserve = struct.unpack_from("<I", data, opt + 72)[0]
    stack_commit = struct.unpack_from("<I", data, opt + 76)[0]
    heap_reserve = struct.unpack_from("<I", data, opt + 80)[0]
    heap_commit = struct.unpack_from("<I", data, opt + 84)[0]
    sh = opt + optsz
    # Same guard as layout_meta.parse_pe: an unhandled struct.error here would
    # escape main's ``except ValueError`` as a raw traceback.
    if sh + 40 * nsec > len(data):
        raise ValueError("truncated section table")

    def rva_to_off(rva: int) -> int | None:
        for s in sections:
            span = max(s.vs, s.raw_size)
            if s.va <= rva < s.va + span:
                return s.raw_ptr + (rva - s.va)
        return None

    sections: list[_Section] = [
        _Section(
            s.name,
            s.virtual_address,
            s.virtual_size,
            s.size_of_raw_data,
            s.pointer_to_raw_data,
            s.characteristics,
        )
        for s in sections_at(data, sh, nsec)
    ]

    def cstr(off: int | None) -> str | None:
        if off is None or off >= len(data):
            return None
        end = data.find(b"\0", off)
        if end < 0:
            # Unterminated — read to EOF.  ``data[off:-1]`` would drop the
            # last byte (same trap layout_meta already guards against).
            end = len(data)
        return data[off:end].decode("latin1", "replace")

    # ---- exports ----
    exp_rva, exp_sz = struct.unpack_from("<II", data, opt + 96)
    exports: list[dict[str, Any]] = []
    eo = rva_to_off(exp_rva)
    # IMAGE_EXPORT_DIRECTORY is 40 bytes; require the full header before
    # reading counts / RVAs, and cap table walks like the import path.
    if eo is not None and exp_sz and eo + 40 <= len(data):
        nfuncs = min(struct.unpack_from("<I", data, eo + 20)[0], _MAX_EXPORT_ENTRIES)
        nnames = min(struct.unpack_from("<I", data, eo + 24)[0], _MAX_EXPORT_ENTRIES)
        funcs_off = rva_to_off(struct.unpack_from("<I", data, eo + 28)[0])
        names_off = rva_to_off(struct.unpack_from("<I", data, eo + 32)[0])
        ords_off = rva_to_off(struct.unpack_from("<I", data, eo + 36)[0])
        ordinal_base = struct.unpack_from("<I", data, eo + 16)[0]
        name_by_ord: dict[int, str] = {}
        for i in range(nnames):
            if names_off is not None and names_off + 4 * (i + 1) > len(data):
                break
            if ords_off is not None and ords_off + 2 * (i + 1) > len(data):
                break
            nrva = struct.unpack_from("<I", data, names_off + 4 * i)[0] if names_off else 0
            ord_idx = struct.unpack_from("<H", data, ords_off + 2 * i)[0] if ords_off else 0
            nm = cstr(rva_to_off(nrva))
            if nm:
                name_by_ord[ordinal_base + ord_idx] = nm
        for i in range(nfuncs):
            if funcs_off is not None and funcs_off + 4 * (i + 1) > len(data):
                break
            addr = struct.unpack_from("<I", data, funcs_off + 4 * i)[0] if funcs_off else 0
            if addr == 0:
                continue  # true null entry: no function at this ordinal
            if exp_rva <= addr < exp_rva + exp_sz:
                continue  # forwarder: the RVA points at a forwarder string
                # inside the export directory, not at code
            ordinal = ordinal_base + i
            exports.append(
                {
                    "name": name_by_ord.get(ordinal),
                    "ordinal": ordinal,
                    "va": image_base + addr,
                }
            )

    # ---- imports (IAT order, per DLL descriptor) ----
    imp_rva, imp_sz = struct.unpack_from("<II", data, opt + 104)
    imports: list[_Import] = []
    io = rva_to_off(imp_rva)
    if io is not None:
        for i in range(_MAX_IMPORT_SLOTS):
            ent = io + i * 20
            if ent + 20 > len(data):
                break
            oft_rva, _ts, _fwd, name_rva, iat_rva = struct.unpack_from("<IIIII", data, ent)
            if oft_rva == 0 and name_rva == 0:
                break
            dll = cstr(rva_to_off(name_rva)) or "?"
            # An unbound descriptor (OFT == 0) carries its names in the IAT
            # itself, so the IAT array is the lookup table (the same fallback
            # layout_meta.extract_layout uses).  Reading only the OFT left such
            # a DLL's imports empty: no /include pragmas in the emitted
            # crt_imports.c and an empty `imports` list in layout_config_dict.
            lookup_rva = oft_rva or iat_rva
            oo = rva_to_off(lookup_rva)
            if oo is None:
                continue
            for j in range(_MAX_IMPORT_SLOTS):
                slot_off = oo + 4 * j
                if slot_off + 4 > len(data):
                    break
                nm = struct.unpack_from("<I", data, slot_off)[0]
                if nm == 0:
                    break
                if nm & 0x80000000:
                    imports.append(_Import(dll, None, nm & 0xFFFF))
                else:
                    # hint/name: 2-byte hint + NUL-terminated name
                    no = rva_to_off(nm)
                    imports.append(_Import(dll, cstr(no + 2 if no is not None else None), None))

    # ---- PE normalization params ----
    reloc_rva = struct.unpack_from("<I", data, opt + 96 + 5 * 8)[0]
    reloc_section = next(
        (s for s in sections if s.va <= reloc_rva < s.va + max(s.vs, s.raw_size)), None
    )
    pe = {
        "image_base": image_base,
        "e_lfanew": e,
        # full header block from file offset 0: DOS stub + PE sig + COFF +
        # optional header + section table (ends at e + 0x198)
        "header_size": e + 4 + 20 + optsz + nsec * 40,
        "time_date_stamp": timestamp,
        "checksum": checksum,
        "size_of_image": size_of_image,
        "size_of_initialized_data": size_of_init_data,
        "base_of_data": base_of_data,
        "reloc_rva": reloc_rva,
        "reloc_va": image_base + reloc_rva if reloc_section else None,
        "reloc_size": struct.unpack_from("<I", data, opt + 96 + 5 * 8 + 4)[0],
        # link-option derivation inputs
        "machine": machine,
        "characteristics": coff_chars,
        "section_alignment": section_align,
        "file_alignment": file_align,
        "subsystem": subsystem,
        "dll_characteristics": dll_chars,
        "stack_reserve": stack_reserve,
        "stack_commit": stack_commit,
        "heap_reserve": heap_reserve,
        "heap_commit": heap_commit,
    }
    return sections, exports, imports, pe


def _import_lib_symbols(lib_path: Path) -> set[str]:
    """Collect ``__imp__...@N`` decorated symbol names from a COFF import library.

    MSVC6 import libraries store the decorated thunk symbols
    (``__imp__GetLocalTime@4``) as plain NUL-terminated strings inside the
    archive members (the archive's linker-member layout is the Microsoft
    variant with an index table — simpler to regex the whole file than to
    walk it).  The decorated name is exactly what ``/include:`` needs.
    """
    out: set[str] = set()
    try:
        d = lib_path.read_bytes()
    except OSError:
        return out
    if d[:8] != b"!<arch>\n":
        return out
    for m in re.finditer(rb"__imp__[A-Za-z0-9_]+@\d+", d):
        out.add(m.group(0).decode("latin1"))
    return out


#: POSIX sh run in the toolchain image: grep the ``__imp__`` symbols out of
#: the file in dir ``$1`` whose upper-cased name equals ``$2``.
_IMAGE_LIB_GREP_SCRIPT = (
    'for f in "$1"/*; do '
    'if [ "$(basename "$f" | tr \'[:lower:]\' \'[:upper:]\')" = "$2" ]; then '
    "exec grep -ao '__imp__[A-Za-z0-9_]*@[0-9]*' \"$f\"; fi; "
    "done; exit 1"
)


def _import_lib_symbols_from_image(dll_stem: str) -> set[str]:
    """Collect the decorated import symbols from the toolchain image's own libs.

    The project config's ``libs`` dir (host MSVC tree) is gone on docker-only
    setups — the import libraries now live inside the toolchain image.  Grep
    the same ``__imp__...@N`` strings out of the image's ``Lib/<DLL>.LIB``.
    """
    from rebrew.toolchain import TOOLCHAINS

    spec = TOOLCHAINS.get("msvc-6.0")
    if spec is None or spec.image is None or spec.tool_root is None:
        return set()
    lib_dir = str(Path(spec.tool_root).parent / "Lib")
    # Unique name: a fixed ``rebrew-libgrep-{dll}`` collided when two
    # gen-layout runs hit the same DLL, and a timed-out orphan blocked the
    # next attempt until manual ``docker rm``.
    # The stem comes from the target's import table, so it stays out of the
    # container name (docker rejects most punctuation) and out of the script
    # body: it travels as a positional arg, matched case-insensitively
    # because the image filesystem is case-sensitive.
    name = f"rebrew-libgrep-{uuid.uuid4().hex[:12]}"
    try:
        r = subprocess.run(
            [
                container_runtime(),
                "run",
                "--rm",
                "--network=none",  # read-only grep inside the image
                "--security-opt=no-new-privileges",  # no setuid escalation inside the image
                # Named so the timeout path can kill it (a killed docker CLI
                # leaves the container running under dockerd).
                "--name",
                name,
                "--entrypoint",
                "sh",
                spec.image,
                "-c",
                _IMAGE_LIB_GREP_SCRIPT,
                "sh",
                lib_dir,
                f"{dll_stem}.LIB".upper(),
            ],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60,
        )
    except subprocess.TimeoutExpired:
        from rebrew.toolchain import kill_container

        kill_container(name)
        return set()
    except OSError:
        return set()
    return set(r.stdout.split()) if r.returncode == 0 else set()


def _imp_suffix(name: str, lib_symbols: set[str], ordinal_map: dict[str, int]) -> str | None:
    """Find the decorated suffix (``@N``) for an import name."""
    for sym in lib_symbols:
        if sym.startswith(f"__imp__{name}@"):
            return sym[len("__imp__") :]
    if name in ordinal_map:
        return f"{name}@{ordinal_map[name]}"
    return None


def _resolve_imports(imports: list[_Import], lib_symbols: set[str]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for imp in imports:
        name = imp.name
        if name is None and imp.ordinal is not None and imp.dll.upper() == "WS2_32.DLL":
            name = _WS2_32_ORDINALS.get(imp.ordinal)
        entry: dict[str, Any] = {
            "dll": imp.dll,
            "name": name,
            "ordinal": imp.ordinal,
            # Always present: gen_crt_imports indexes it unconditionally, even
            # for an ordinal-only import (name None) from a DLL other than WS2_32.
            "include": None,
        }
        if name:
            suffix = _imp_suffix(name, lib_symbols, _WS2_32_ARGS)
            entry["include"] = f"__imp__{suffix}" if suffix else None
        out.append(entry)
    return out


def gen_def(target: str, exports: list[dict[str, Any]]) -> str:
    """Render the `.def` export block: LIBRARY name + one EXPORTS line per ordinal."""
    lines = [f"LIBRARY {target.rsplit('.', 1)[0]}", "EXPORTS"]
    for ex in exports:
        name = ex["name"] or f"ORDINAL_{ex['ordinal']}"
        lines.append(f"    {name} @{ex['ordinal']}")
    return "\n".join(lines) + "\n"


def gen_crt_imports(marker: str, imports: list[dict[str, Any]], iat_va: int | None) -> str:
    """The auto-generated CRT import TU: /include directives in IAT order, linked first."""
    lines = [
        f"// DATA: {marker} 0x{iat_va:x}" if iat_va else f"// IAT-forcing /include list ({marker})",
        "// AUTO-GENERATED by rebrew gen-layout — imports in the original's IAT order.",
        "// Link this TU FIRST so /include directives allocate IAT slots.",
    ]
    cur_dll = None
    for imp in imports:
        if imp["dll"] != cur_dll:
            cur_dll = imp["dll"]
            lines.append(f"// {cur_dll}")
        if imp["include"]:
            lines.append(f'#pragma comment(linker, "/include:{imp["include"]}")')
        elif imp["name"]:
            lines.append(
                f'// #pragma comment(linker, "/include:__imp__{imp["name"]}")  /* suffix unknown */'
            )
        else:
            lines.append(
                f"// #pragma comment(linker, ...)  /* ordinal {imp['ordinal']} of {cur_dll} */"
            )
    return "\n".join(lines) + "\n"


def derive_link_options(pe: dict[str, Any]) -> tuple[list[str], str]:
    """Derive MSVC6 LINK options and a ``[link]`` toml block from the reference.

    Most PE header fields map 1:1 onto linker options, so they can be read
    straight off the binary and handed to the linker instead of post-fixed:

      ImageBase      -> /BASE            Subsystem        -> /SUBSYSTEM
      SectionAlign   -> /ALIGN           StackReserve/Commit -> /STACK
      FileAlign      -> /ALIGN:filealign (VC6 derives it)  HeapReserve/Commit -> /HEAP
      CheckSum!=0    -> /RELEASE         Characteristics 0x20 -> /LARGEADDRESSAWARE
      Machine        -> /MACHINE

    Returns ``(link_options, link_toml)`` — the option strings for the link
    line, and a ``[link]`` block for ``rebrew-project.toml`` (the fields
    ``rebrew round-trip --fix-headers`` consumes).

    The options are emitted as *deltas from the VC6 linker defaults*: adding
    an option that equals the default can change fields the default leaves
    alone (e.g. ``/ALIGN:0x1000`` is NOT a no-op — it forces FileAlignment to
    0x200 and shrinks SizeOfHeaders, while the plain default produces
    FileAlignment=0x1000).  Only emit what the original deviates on.
    """
    # VC6 LINK defaults (empirically verified against a plain /dll link)
    DEF_IMAGE_BASE = 0x400000
    DEF_SECTION_ALIGN = 0x1000
    DEF_SUBSYSTEM = 2  # WINDOWS
    DEF_STACK_RESERVE = 0x100000
    DEF_STACK_COMMIT = 0x1000
    DEF_HEAP_RESERVE = 0x100000
    DEF_HEAP_COMMIT = 0x1000
    DEF_MACHINE = 0x14C  # I386

    opts: list[str] = []
    if pe.get("image_base") != DEF_IMAGE_BASE:
        opts.append(f"/BASE:0x{pe['image_base']:x}")
    if pe.get("section_alignment") and pe["section_alignment"] != DEF_SECTION_ALIGN:
        opts.append(f"/ALIGN:0x{pe['section_alignment']:x}")
    sub = pe.get("subsystem") or DEF_SUBSYSTEM
    if sub != DEF_SUBSYSTEM:
        subsys = {1: "NATIVE", 2: "WINDOWS", 3: "CONSOLE", 9: "WINDOWSCE"}.get(sub, f"{sub}")
        opts.append(f"/SUBSYSTEM:{subsys}")

    # ``.get(key) or DEF`` treated a legitimate 0 as "absent" and dropped the
    # option, so the built binary never matched a reference whose field is 0.
    def _size(key: str, default: int) -> int:
        value = pe.get(key)
        return default if value is None else int(value)

    stack_reserve, stack_commit = (
        _size("stack_reserve", DEF_STACK_RESERVE),
        _size("stack_commit", DEF_STACK_COMMIT),
    )
    if (stack_reserve, stack_commit) != (DEF_STACK_RESERVE, DEF_STACK_COMMIT):
        opts.append(f"/STACK:0x{stack_reserve:x},0x{stack_commit:x}")
    heap_reserve, heap_commit = (
        _size("heap_reserve", DEF_HEAP_RESERVE),
        _size("heap_commit", DEF_HEAP_COMMIT),
    )
    if (heap_reserve, heap_commit) != (DEF_HEAP_RESERVE, DEF_HEAP_COMMIT):
        opts.append(f"/HEAP:0x{heap_reserve:x},0x{heap_commit:x}")
    if pe.get("characteristics", 0) & 0x20:
        opts.append("/LARGEADDRESSAWARE")
    if (pe.get("machine") or DEF_MACHINE) != DEF_MACHINE:
        mach = {0x14C: "I386", 0x8664: "X64", 0x1C0: "ARM"}.get(
            pe["machine"], f"0x{pe['machine']:x}"
        )
        opts.append(f"/MACHINE:{mach}")

    link = []
    link.append("[link]")
    link.append("# Derived by 'rebrew gen-layout' from the original binary.")
    if pe.get("file_alignment"):
        link.append(f'file_align = "0x{pe["file_alignment"]:x}"')
    if stack_reserve != DEF_STACK_RESERVE:
        link.append(f'stack_reserve = "0x{stack_reserve:x}"')
    if stack_commit != DEF_STACK_COMMIT:
        link.append(f'stack_commit = "0x{stack_commit:x}"')
    if pe.get("dll_characteristics", 0) & 0x8000:
        link.append("tsaware = true")
    link.append(f'timestamp = "0x{pe["time_date_stamp"]:x}"')
    return opts, "\n".join(link) + "\n"


def layout_config_dict(
    meta: LayoutMetadata,
    resolved_imports: list[dict[str, Any]],
    link_options: list[str],
    resolve_names: bool = True,
) -> dict[str, Any]:
    """The layout package dict (``rebrew-layout.toml`` content + extras).

    *resolved_imports* is the import list with ordinal names resolved (the
    same order as ``meta.imports``).  With ``resolve_names=True`` (the
    reviewable package) those names are kept and the reference IAT-slot
    VA from ``meta.imports`` is attached by position.  With
    ``resolve_names=False`` (the exact input the post-link fixers compare
    against) the raw imports are used — ordinal-only entries stay
    ordinal-only, which is what the import-set signature and the IAT-slot
    remap compare against.
    """
    if not resolve_names:
        imports: list[dict[str, Any]] = [i.as_dict() for i in meta.imports]
    else:
        imports = []
        for i, imp in enumerate(resolved_imports):
            entry: dict[str, Any] = {"dll": imp["dll"]}
            if imp.get("name"):
                entry["name"] = imp["name"]
            if imp.get("ordinal") is not None:
                entry["ordinal"] = imp["ordinal"]
            if i < len(meta.imports):
                entry["iat"] = meta.imports[i].iat_va
            imports.append(entry)
    return {
        "target": meta.target,
        "link_options": link_options,
        "image_base": meta.image_base,
        "sections": [s.as_dict() for s in meta.sections],
        "exports": [
            {
                "name": ex.get("name") or f"ORD_{ex['ordinal']}",
                "ordinal": ex["ordinal"],
                "va": ex["va"],
            }
            for ex in meta.exports
        ],
        "imports": imports,
        "export_stamp": list(meta.export_stamp),
        "exp_rva": meta.exp_rva,
    }


def fmt_layout_toml(
    meta: LayoutMetadata, resolved_imports: list[dict[str, Any]], link_options: list[str]
) -> str:
    """Render the ``rebrew-layout.toml`` structured file (TOML) for a layout package.

    Uses the raw import list (ordinal-only entries stay ordinal-only) so the
    package is the exact input the post-link fixers compare against.
    """
    import tomlkit

    lay = tomlkit.inline_table()
    for k, v in layout_config_dict(
        meta, resolved_imports, link_options, resolve_names=False
    ).items():
        lay[k] = v
    doc = tomlkit.document()
    doc["layout"] = lay
    return tomlkit.dumps(doc)


def gen_data_restore(data: bytes, marker: str, raw_start: int) -> str:
    """The ``.data`` gap TU: the reference's raw ``.data`` bytes ``[raw_start : raw_end]``.

    Project TUs emit only part of the initialized ``.data``; this TU declares
    the missing tail (bytes copied from the reference) so the raw link's
    ``.data`` rsz reaches the reference's raw size without post-processing.
    Link it first (after crt_imports) so the section-derived header fields
    fall out of the link.
    """
    layout = pe_layout(data)
    if layout is None:
        raise ValueError("reference binary is not a PE")
    section = next((s for s in layout.sections if s.name == ".data"), None)
    if section is None:
        raise ValueError("no .data section in the reference binary")
    data_va = section.virtual_address
    data_raw = section.size_of_raw_data
    data_ro = section.pointer_to_raw_data
    image_base = struct.unpack_from("<I", data, layout.optional_header_offset + 28)[0]
    if not 0 <= raw_start < data_raw:
        raise ValueError(f"raw-size {raw_start:#x} outside [0, {data_raw:#x})")
    blob = data[data_ro + raw_start : data_ro + data_raw]
    lines = [
        "/* data_restore.c - AUTO-GENERATED by rebrew gen-layout --data-gap",
        f" * Declares the original's raw .data bytes [{raw_start:#x}:{data_raw:#x}] that",
        " * the project TUs do not emit, so the raw link's .data rsz reaches",
        f" * {data_raw:#x}.  Content is the reference's bytes; postlink copies",
        " * the reference .data over it for byte identity.  Link FIRST (after",
        " * crt_imports).  Regenerate with: rebrew gen-layout --data-gap <raw-size>",
        " */",
        f"// DATA: {marker} 0x{image_base + data_va + raw_start:x}",
        "#pragma pack(push, 1)",
        f"unsigned char g_data_restore_gap[0x{len(blob):x}] = {{",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i : i + 16]
        lines.append("\t" + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("#pragma pack(pop)")
    return "\n".join(lines) + "\n"


@app.callback(invoke_without_command=True)
def main(
    def_only: bool = typer.Option(False, "--def-only", help="Only emit <target>.def"),
    link_config: bool = typer.Option(
        False,
        "--link-config",
        help=r"Print the derived \[link] toml block for rebrew-project.toml",
    ),
    layout_config: bool = typer.Option(
        False,
        "--layout-config",
        help=r"Print the \[targets.<t>.layout] toml block (readable metadata) for rebrew-project.toml",
    ),
    data_gap: str | None = typer.Option(
        None,
        "--data-gap",
        help="Also emit crt_region/data_restore.c: the reference's raw .data bytes "
        "[<raw-size>:raw_end] the project TUs do not emit (hex, e.g. 0x3000), so the "
        "raw link's .data rsz matches without post-processing",
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Generate the linker-script scaffolding for a target binary."""
    cfg = require_config(target, json_mode=json_output)
    if not cfg.target_binary.exists():
        error_exit(f"binary not found: {cfg.target_binary}", json_mode=json_output)
    data = cfg.target_binary.read_bytes()
    try:
        sections, exports, imports_raw, pe = parse_pe(data)
    except ValueError as exc:
        error_exit(f"{cfg.target_binary}: {exc}", json_mode=json_output)

    link_options, link_toml = derive_link_options(pe)

    # resolve import lib symbols for @N suffixes (readable list + the
    # crt_imports.c /include seed).  Host lib dir first (legacy); fall back
    # to the toolchain image's own Lib dir (docker-only setups have no host
    # MSVC tree anymore).
    lib_symbols: set[str] = set()
    libs_dir = cfg.compiler_libs
    for dll in {i.dll for i in imports_raw}:
        # binary names imports "KERNEL32.dll"; the import libs on disk are
        # "KERNEL32.LIB" (case and extension differ, and Linux is
        # case-sensitive) — match "<stem>.lib", then the DLL name, ignoring case.
        stem = Path(dll).stem
        lib: Path | None = None
        if libs_dir.is_dir():
            by_name = {p.name.casefold(): p for p in libs_dir.iterdir() if p.is_file()}
            lib = by_name.get(f"{stem}.lib".casefold()) or by_name.get(dll.casefold())
        if lib is not None:
            lib_symbols |= _import_lib_symbols(lib)
        else:
            lib_symbols |= _import_lib_symbols_from_image(stem)
    imports = _resolve_imports(imports_raw, lib_symbols)

    if link_config:
        if json_output:
            json_print({"link_toml": link_toml})
        else:
            print(link_toml)
        return
    if layout_config:
        layout_toml = fmt_layout_toml(
            extract_layout(cfg.target_binary.read_bytes(), cfg.target_name),
            imports,
            link_options,
        )
        if json_output:
            json_print({"layout_toml": layout_toml})
        else:
            print(layout_toml)
        return

    marker = cfg.marker or cfg.target_name.upper()
    out_dir = cfg.reversed_dir

    result = {
        "target": cfg.target_name,
        "exports": len(exports),
        "imports": len(imports),
        "written": [],
    }
    if dry_run:
        if json_output:
            result["dry_run"] = True
            json_print(result)
        else:
            console.print(
                f"[cyan]dry-run:[/cyan] would write {len(exports)} exports, "
                f"{len(imports)} imports scaffolding under {out_dir} "
                f"and layout/{cfg.target_name}/"
            )
        return
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "crt_region").mkdir(parents=True, exist_ok=True)

    # Text-only layout package (committed, no binary blobs): the structured
    # rebrew-layout.toml + hex dumps of the opaque linker-stamped regions + sparse
    # .text maps land in layout/<target>/, which the build's
    # 'rebrew postlink --layout' consumes without the original DLL.
    try:
        meta = extract_layout(data, cfg.target_name)
    except ValueError as exc:
        error_exit(str(exc), json_mode=json_output)

    pkg_dir = cfg.root / "layout" / cfg.target_name
    tname = cfg.target_name.rsplit(".", 1)[0]
    written: list[str] = []

    def write(rel: Path, text: str) -> None:
        atomic_write_text(out_dir / rel, text)
        written.append(str(out_dir / rel))

    write(Path(f"{cfg.target_name}.def"), gen_def(tname, exports))
    if not def_only:
        written.extend(
            str(p)
            for p in write_package(
                meta, pkg_dir, fmt_toml=lambda m: fmt_layout_toml(m, imports, link_options)
            )
        )
        from rebrew.binary_gate import layout_fingerprint

        fingerprint = layout_fingerprint(cfg.target_binary)
        if fingerprint:
            atomic_write_text(pkg_dir / "layout.fingerprint", fingerprint + "\n")
            written.append(str(pkg_dir / "layout.fingerprint"))
        # `Section.va` is an RVA, and a `// DATA:` marker is a VA -- every other
        # generator here adds the image base (see gen_data_restore).  Emitting
        # the bare RVA wrote `// DATA: SERVER 0x24000` for an IAT that lives at
        # 0x10024000, which falls outside every section range and made the
        # annotation unresolvable to every tool that reads it.
        iat_section = next((s for s in sections if s.name == ".rdata"), None)
        write(
            Path("crt_region/crt_imports.c"),
            gen_crt_imports(
                marker,
                imports,
                pe["image_base"] + iat_section.va if iat_section else None,
            ),
        )
        if data_gap:
            write(
                Path("crt_region/data_restore.c"),
                gen_data_restore(data, marker, int(data_gap, 0)),
            )

    result = {
        "target": cfg.target_name,
        "exports": len(exports),
        "imports": len(imports),
        "written": written,
        "dry_run": False,
    }
    if json_output:
        json_print(result)
    else:
        console.print(f"gen-layout: {len(exports)} exports, {len(imports)} imports")
        for w in written:
            console.print(f"  wrote {w}")


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_standalone

    run_standalone(main)


if __name__ == "__main__":
    main_entry()
