"""gen-link-stubs — BSS placeholder TU from the data metadata.

A byte-identity build needs the raw link's ``.data`` VirtualSize to reach
the reference's (the BSS tail lives beyond the raw size).  This command
emits a ``link_stubs.c``-style TU: a non-tentative zero-init placeholder for
every ``.data`` symbol in the data metadata (``src/rebrew-data.toml``), so
the linker emits them into ``.data``'s BSS (raw=0, VS grows), plus a
calibratable ``g_bss_tail`` pad.

Run ``rebrew calibrate-bss`` afterwards to size the tail so the raw link's
``.data`` VirtualSize matches the reference exactly.

Usage:
    rebrew gen-link-stubs [--data-metadata src/rebrew-data.toml] [--output src/link_stubs.c]
"""

from __future__ import annotations

import re
from pathlib import Path

import typer

from rebrew.cli import console, error_exit, json_print
from rebrew.data_metadata import iter_data_symbols
from rebrew.utils import atomic_write_text, is_safe_c_ident, load_tomllib, read_source_text

app = typer.Typer(
    help="Generate a link_stubs.c-style BSS placeholder TU from the data metadata.",
    rich_markup_mode="rich",
)

_TAIL_DEFAULT = 0x400000  # generous; `rebrew calibrate-bss` fixes it

#: The pad `rebrew calibrate-bss` tunes in place, and the marker proving a
#: file is ours to rewrite.
TAIL_SYMBOL = "g_bss_tail"
_AUTO_MARKER = "AUTO-GENERATED by rebrew gen-link-stubs"
_TAIL_RE = re.compile(
    r"^unsigned char " + re.escape(TAIL_SYMBOL) + r"\[(0x[0-9a-fA-F]+|\d+)\] = \{0\};$",
    re.M,
)


def read_calibrated_tail(path: Path) -> int | None:
    """The BSS tail size already tuned into *path*, or ``None``.

    ``rebrew calibrate-bss`` rewrites ``g_bss_tail[<size>]`` in the generated
    TU and leaves it there.  Regenerating the TU must not silently reset that
    measurement, so the size is read back before rewriting.  ``None`` means
    "no size to preserve": the file is missing, unreadable, not a generated
    TU (a hand-written ``link_stubs.c`` keeps its own tail), or carries no
    tail declaration.
    """
    if not path.is_file():
        return None
    try:
        text, _encoding = read_source_text(path)
    except (OSError, ValueError):
        return None
    if _AUTO_MARKER not in text:
        return None
    m = _TAIL_RE.search(text)
    if m is None:
        return None
    raw = m.group(1)
    try:
        return int(raw, 16 if raw.lower().startswith("0x") else 10)
    except ValueError:
        return None


def load_data_symbols(metadata: Path) -> list[tuple[int, str, str]]:
    """Sorted ``(address, name, type)`` of the ``.data`` symbols in *metadata*."""
    doc = load_tomllib(metadata)
    out = [
        (va, str(val.get("name") or f"g_data_{va:x}"), str(val.get("type", "int")))
        for _, va, val in iter_data_symbols(doc)
    ]
    out.sort()
    return out


def gen_link_stubs(metadata: Path, tail: int = _TAIL_DEFAULT) -> str:
    """The BSS placeholder TU text, with *tail* as the pad size.

    *tail* is passed in rather than hard-coded so a regeneration can keep the
    size ``rebrew calibrate-bss`` already converged on (see
    :func:`read_calibrated_tail`) instead of resetting the build to the
    placeholder value.
    """
    symbols = load_data_symbols(metadata)
    lines = [
        "/* link_stubs.c - AUTO-GENERATED by rebrew gen-link-stubs",
        " * Non-tentative zero-init placeholders for every .data symbol in the",
        " * data metadata, so the linker emits them into .data's BSS (raw=0,",
        " * VirtualSize grows).  The g_bss_tail pad extends VS to the reference;",
        " * size it with: rebrew calibrate-bss",
        " * DO NOT hand-edit.  Regenerate with: rebrew gen-link-stubs",
        " */",
        "#include <time.h>",
        "",
        "/* .data symbol placeholders (zero-init -> .data BSS) */",
    ]
    # Two addresses carrying one name (a re-annotated global, a merged module)
    # would emit the same definition twice and the TU would not compile.  The
    # lowest address wins; the later ones are already covered by it.
    emitted: set[str] = set()
    for addr, name, _type in symbols:
        if not is_safe_c_ident(name):
            # Non-identifier names (mangled/corrupt metadata) emitted verbatim
            # would produce an uncompilable TU — fall back to an
            # address-derived identifier.
            name = f"g_data_{addr:x}"
        if name in emitted:
            continue
        emitted.add(name)
        lines.append(f"char {name}[1] = {{0}};")
    lines.append("")
    lines.append("/* BSS tail pad: grows .data VS toward the reference (calibrate-bss) */")
    lines.append(f"unsigned char {TAIL_SYMBOL}[{tail:#x}] = {{0}};")
    lines.append("")
    return "\n".join(lines) + "\n"


@app.callback(invoke_without_command=True)
def main(
    data_metadata: Path = typer.Option(
        Path("src/rebrew-data.toml"), "--data-metadata", help="Data metadata toml path"
    ),
    output: Path = typer.Option(Path("src/link_stubs.c"), "--output", "-o", help="Output TU path"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
) -> None:
    """Generate the BSS placeholder TU."""
    root = Path.cwd()
    metadata = data_metadata if data_metadata.is_absolute() else root / data_metadata
    if not metadata.exists():
        error_exit(f"data metadata not found: {metadata}", json_mode=json_output)
    target = output if output.is_absolute() else root / output
    # Regeneration is the common case (a new data symbol), and it must not
    # throw away the tail size calibrate-bss converged on.
    measured = read_calibrated_tail(target)
    preserved = measured is not None
    tail = measured if measured is not None else _TAIL_DEFAULT
    content = gen_link_stubs(metadata, tail=tail)
    symbols = load_data_symbols(metadata)
    if dry_run:
        if json_output:
            json_print(
                {
                    "symbols": len(symbols),
                    "tail": f"{tail:#x}",
                    "tail_preserved": preserved,
                    "generated": content,
                    "written": False,
                }
            )
        else:
            print(content)
        return
    atomic_write_text(target, content, encoding="utf-8")
    if json_output:
        json_print(
            {
                "symbols": len(symbols),
                "tail": f"{tail:#x}",
                "tail_preserved": preserved,
                "generated": content,
                "written": True,
                "output": str(target),
            }
        )
        return
    console.print(f"[green]gen-link-stubs:[/] wrote {target}")
    if preserved:
        console.print(f"  kept the calibrated {TAIL_SYMBOL} size {tail:#x}")
    else:
        console.print(f"  {TAIL_SYMBOL}[{tail:#x}] is a placeholder — re-run rebrew calibrate-bss")


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_standalone

    run_standalone(main)


if __name__ == "__main__":
    main_entry()
