"""imports.py — ``rebrew imports``: list import-table symbols and mark import stubs.

CLI layer over :mod:`rebrew.import_table`.  Together the import table and the
``jmp dword ptr [iat]`` stubs name the library functions a target binary
imports — the first half of the "library identification" pass (the FLIRT half
lives in :mod:`rebrew.flirt` and needs ``.sig`` files).

Usage:
    rebrew imports [binary]
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import typer
from rich.console import Console

from rebrew.cli import EXIT_ERROR, TargetOption, error_exit, json_print, require_config
from rebrew.config import module_marker
from rebrew.import_table import find_import_stubs, parse_imports
from rebrew.utils import read_source_text

console = Console(stderr=True)


def imports_payload(
    binary_path: Path,
    stubs: dict[int, str] | None = None,
) -> dict[str, Any]:
    """Build the ``--json`` payload for ``rebrew imports``.

    Combines :func:`parse_imports` with the ``jmp dword ptr [iat]`` stub map
    *stubs* (computed via :func:`find_import_stubs` when omitted) into the
    exact object ``rebrew imports --json`` prints: one record per imported API
    with a hex ``iat_va`` string, and one stub record per detected import
    thunk with a hex ``va`` string.  An unrecognized or unparseable binary
    yields empty ``imports`` / ``stubs`` lists, never an exception.
    """
    if stubs is None:
        stubs = find_import_stubs(binary_path)
    return {
        "binary": str(binary_path),
        "imports": [
            {
                "dll": i["dll"],
                "name": i["name"],
                "iat_va": f"0x{i['iat_va']:08x}",
            }
            for i in parse_imports(binary_path)
        ],
        # Stub VAs as hex strings (matching every other rebrew JSON)
        # instead of decimal stringified dict keys.
        "stubs": [{"va": f"0x{va:08x}", "name": name} for va, name in sorted(stubs.items())],
    }


def mark_import_stubs(
    cfg: Any,
    stubs: dict[int, str],
    *,
    dry_run: bool = False,
) -> int:
    """Write ``// LIBRARY: <marker> 0xVA`` annotations for import stubs.

    Appends to ``<reversed_dir>/library_imports.h`` (created if missing),
    skipping VAs that already carry an annotation.  Returns the number of
    NEW annotations written.  Completes the library-identification loop:
    import stubs detected in .text become LIBRARY functions that
    ``rebrew crt-match`` can then attribute to CRT sources.
    """
    marker = module_marker(cfg)
    out_file = Path(cfg.reversed_dir) / "library_imports.h"
    existing, encoding = read_source_text(out_file) if out_file.exists() else ("", "utf-8")

    existing_upper = existing.upper()
    blocks: list[str] = []
    for va in sorted(stubs):
        if f"0X{va:08X}" in existing_upper:
            continue
        blocks.append(f"// LIBRARY: {marker} 0x{va:08X}\n// {stubs[va]}\n")
    if not blocks:
        console.print("No new import stubs to annotate.")
        return 0

    if dry_run:
        console.print(
            f"[dim]Dry run:[/dim] would add {len(blocks)} LIBRARY annotation(s) to {out_file.name}:"
        )
        for block in blocks:
            console.print(f"  [dim]{block.strip()}[/]")
        return len(blocks)

    # The banner is written once, on creation; re-runs only append new blocks.
    body = "\n".join(blocks)
    if existing.strip():
        text = existing.rstrip("\n") + "\n\n" + body
    else:
        text = "/* Auto-generated by rebrew imports --mark. DO NOT EDIT. */\n\n" + body
    from rebrew.utils import atomic_write_text

    atomic_write_text(out_file, text, encoding=encoding)
    console.print(f"[green]Annotated {len(blocks)} import stub(s) in {out_file.name}[/green]")
    return len(blocks)


app = typer.Typer(
    help="List import-table symbols (PE IAT, ELF dynamic imports, or 16-bit NE modules) and detect import stubs.",
    rich_markup_mode="rich",
    epilog=(
        "[bold]Examples:[/bold]\n\n"
        "  rebrew imports · · · · · · · · · · · · Use the project's target binary\n\n"
        "  rebrew imports original/game.exe · · · Scan a specific binary\n\n"
        "  rebrew imports game.exe --json · · · Machine-readable output\n\n"
        "[bold]What it shows:[/bold]\n\n"
        "  IAT VA · · · · · · · · Virtual address of the imported function slot\n\n"
        "  API name · · · · · · · e.g. MessageBoxA (from KERNEL32.dll)\n\n"
        "  Import stubs · · · · · jmp dword ptr [iat] functions in .text\n\n"
        "[dim]Part of the library-identification workflow: pair with rebrew flirt "
        "(FLIRT signatures) to name statically-linked CRT/zlib functions.[/dim]"
    ),
)


@app.callback(invoke_without_command=True)
def main(
    binary: Path | None = typer.Argument(None, help="Binary path (default: project target)"),
    mark: bool = typer.Option(
        False, "--mark", help="Write LIBRARY annotations for detected import stubs"
    ),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Scan a binary's import table and report its imported APIs."""
    cfg: Any = None
    if binary is None or mark:
        cfg = require_config(target=target, json_mode=json_output)
    if binary is None:
        binary = cfg.target_binary
        if not binary.exists():
            error_exit(f"target binary missing: {binary}", json_mode=json_output, code=EXIT_ERROR)
    if not binary.exists():
        error_exit(f"binary not found: {binary}", json_mode=json_output)

    imports = parse_imports(binary)
    stubs = find_import_stubs(binary)

    if mark:
        if json_output:
            # --mark writes annotations; --json promises machine output that
            # mark_import_stubs does not produce.  Refuse the combination
            # instead of silently dropping --json.
            error_exit(
                "--mark writes annotations and is not JSON-output compatible; "
                "use --json alone to list imports, or --mark alone to write.",
                json_mode=json_output,
                code=EXIT_ERROR,
            )
        mark_import_stubs(cfg, stubs, dry_run=dry_run)
        return

    if json_output:
        json_print(imports_payload(binary, stubs))
        return

    if dry_run:
        console.print("[dim]--dry-run only applies with --mark; nothing to preview.[/dim]")

    if not imports:
        console.print(f"[yellow]No import table found in {binary}.[/]")
        return
    console.print(f"[bold]{len(imports)}[/] imported APIs from [bold]{binary}[/]:")
    for rec in sorted(imports, key=lambda r: r["iat_va"]):
        if rec["name"]:
            console.print(f"  0x{rec['iat_va']:08x}  {rec['name']:30s}  {rec['dll']}")
        else:
            # Module-level record: a 16-bit NE without a classic import table,
            # or an ELF library no versioned symbol was attributed to.
            console.print(f"  [dim]0x00000000  {rec['dll']:30s} (module reference)[/dim]")
    if stubs:
        console.print(f"\n[bold]{len(stubs)}[/] import stubs found in .text:")
        for va, name in sorted(stubs.items()):
            console.print(f"  0x{va:08x}  jmp [{name}]")


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_standalone

    run_standalone(main)


if __name__ == "__main__":
    main_entry()
