"""imports.py — ``rebrew binary imports list``: list import-table symbols and mark import stubs.

CLI layer over :mod:`rebrew.import_table`.  Together the import table and the
``jmp dword ptr [iat]`` stubs name the library functions a target binary
imports — the first half of the "library identification" pass (the FLIRT half
lives in :mod:`rebrew.flirt` and needs ``.sig`` files).

Usage:
    rebrew binary imports list [binary]
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import typer

from rebrew.annotation import NEW_FUNC_CAPTURE_RE
from rebrew.cli import (
    EXIT_ERROR,
    TargetOption,
    console,
    error_exit,
    json_print,
    require_config,
    resolve_binary_arg,
)
from rebrew.config import module_marker
from rebrew.import_table import find_import_stubs, parse_imports
from rebrew.utils import pe_name_token, read_source_text, untrusted_text


def imports_payload(
    binary_path: Path,
    stubs: dict[int, str] | None = None,
) -> dict[str, Any]:
    """Build the ``--json`` payload for ``rebrew binary imports list``.

    Combines :func:`parse_imports` with the ``jmp dword ptr [iat]`` stub map
    *stubs* (computed via :func:`find_import_stubs` when omitted) into the
    exact object ``rebrew binary imports list --json`` prints: one record per imported API
    with a hex ``iat_va`` string and an ``ordinal`` (null when the import is by
    name), and one stub record per detected import thunk with a hex ``va``
    string.  An unrecognized or unparseable binary
    yields empty ``imports`` / ``stubs`` lists, never an exception.
    """
    if stubs is None:
        stubs = find_import_stubs(binary_path)
    return {
        "binary": str(binary_path),
        "imports": [
            {
                "dll": i["dll"],
                "name": i["name"],
                "iat_va": f"0x{i['iat_va']:08x}",
                "ordinal": i["ordinal"],
            }
            for i in parse_imports(binary_path)
        ],
        # Stub VAs as hex strings (matching every other rebrew JSON)
        # instead of decimal stringified dict keys.
        "stubs": [{"va": f"0x{va:08x}", "name": name} for va, name in sorted(stubs.items())],
    }


def mark_import_stubs(
    cfg: Any,
    stubs: dict[int, str],
    *,
    dry_run: bool = False,
) -> int:
    """Write ``// LIBRARY: <marker> 0xVA`` annotations for import stubs.

    Appends to ``<reversed_dir>/library_imports.h`` (created if missing),
    skipping VAs that already carry an annotation.  Returns the number of
    NEW annotations written.  Completes the library-identification loop:
    import stubs detected in .text become LIBRARY functions that
    ``rebrew library crt-match`` can then attribute to CRT sources.
    """
    marker = module_marker(cfg)
    out_file = Path(cfg.reversed_dir) / "library_imports.h"
    existing, encoding = read_source_text(out_file) if out_file.exists() else ("", "utf-8")

    # Only a marker line counts as "already annotated".  A substring search
    # over the whole file also fires on an unrelated comment or a value
    # inside a different annotation, which suppresses that VA forever: the
    # gap never heals on a re-run, because the mention is still there.
    annotated = {
        int(match.group("va"), 16)
        for match in NEW_FUNC_CAPTURE_RE.finditer(existing)
        if match.group("va")
    }
    blocks: list[str] = []
    for va in sorted(stubs):
        if va in annotated:
            continue
        # The stub name comes from the target's hint/name table, so it is
        # attacker-controlled whenever the binary is; a newline would end the
        # comment and make the rest compile as C in this header.
        blocks.append(f"// LIBRARY: {marker} 0x{va:08X}\n// {pe_name_token(stubs[va])}\n")
    if not blocks:
        console.print("No new import stubs to annotate.")
        return 0

    if dry_run:
        console.print(
            f"[dim]Dry run:[/dim] would add {len(blocks)} LIBRARY annotation(s) to {out_file.name}:"
        )
        for block in blocks:
            console.print(f"  [dim]{block.strip()}[/]")
        return len(blocks)

    # The banner is written once, on creation; re-runs only append new blocks.
    body = "\n".join(blocks)
    if existing.strip():
        text = existing.rstrip("\n") + "\n\n" + body
    else:
        text = "/* Auto-generated by rebrew binary imports mark. DO NOT EDIT. */\n\n" + body
    from rebrew.utils import atomic_write_text

    atomic_write_text(out_file, text, encoding=encoding)
    console.print(f"[green]Annotated {len(blocks)} import stub(s) in {out_file.name}[/green]")
    return len(blocks)


app = typer.Typer(
    help="List import-table symbols (PE IAT, ELF dynamic imports, or 16-bit NE modules) and detect import stubs.",
    rich_markup_mode="rich",
    epilog=(
        "[bold]Examples:[/bold]\n\n"
        "  rebrew binary imports list · · · · · · · · · · · · Use the project's target binary\n\n"
        "  rebrew binary imports list original/game.exe · · · Scan a specific binary\n\n"
        "  rebrew binary imports list game.exe --json · · · Machine-readable output\n\n"
        "[bold]What it shows:[/bold]\n\n"
        "  IAT VA · · · · · · · · Virtual address of the imported function slot\n\n"
        "  API name · · · · · · · e.g. MessageBoxA (from KERNEL32.dll)\n\n"
        "  Import stubs · · · · · jmp dword ptr \\[iat] functions in .text\n\n"
        "[dim]Part of the library-identification workflow: pair with rebrew library scan-signatures "
        "(FLIRT signatures) to name statically-linked CRT/zlib functions.[/dim]"
    ),
)


def inspect_imports(
    binary: Path | None = None,
    mark: bool = False,
    dry_run: bool = False,
    json_output: bool = False,
    target: str | None = None,
) -> None:
    """Scan a binary's import table and report its imported APIs."""
    cfg: Any = None
    if binary is None or mark:
        cfg = require_config(target=target, json_mode=json_output)
        if binary is None:
            binary = cfg.target_binary
    binary = resolve_binary_arg(binary, target=target, json_mode=json_output)

    imports = parse_imports(binary)
    stubs = find_import_stubs(binary)

    if mark:
        if json_output:
            # --mark writes annotations; --json promises machine output that
            # mark_import_stubs does not produce.  Refuse the combination
            # instead of silently dropping --json.
            error_exit(
                "binary imports mark writes annotations and is not JSON-output compatible; "
                "use binary imports list --json to inspect, or mark without --json to write.",
                json_mode=json_output,
                code=EXIT_ERROR,
            )
        mark_import_stubs(cfg, stubs, dry_run=dry_run)
        return

    if json_output:
        json_print(imports_payload(binary, stubs))
        return

    if dry_run:
        console.print("[dim]--dry-run only applies with --mark; nothing to preview.[/dim]")

    if not imports:
        console.print(f"[yellow]No import table found in {binary}.[/]")
        return
    console.print(f"[bold]{len(imports)}[/] imported APIs from [bold]{binary}[/]:")
    for rec in sorted(imports, key=lambda r: r["iat_va"]):
        if rec["name"]:
            console.print(
                f"  0x{rec['iat_va']:08x}  {untrusted_text(rec['name']):30s}  "
                f"{untrusted_text(rec['dll'])}"
            )
        else:
            # Module-level record: a 16-bit NE without a classic import table,
            # or an ELF library no versioned symbol was attributed to.
            console.print(
                f"  [dim]0x00000000  {untrusted_text(rec['dll']):30s} (module reference)[/dim]"
            )
    if stubs:
        console.print(f"\n[bold]{len(stubs)}[/] import stubs found in .text:")
        for va, name in sorted(stubs.items()):
            console.print(f"  0x{va:08x}  jmp [{untrusted_text(name)}]")


@app.command(
    "list",
    epilog="Examples:\n\n  rebrew binary imports list --json\n\nUse --target to select a configured project target.",
)
def list_imports(
    binary: Path | None = typer.Argument(None, help="Binary path (default: project target)"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """List imported APIs and detected forwarding stubs."""
    inspect_imports(binary=binary, json_output=json_output, target=target)


@app.command(
    "mark",
    epilog="Examples:\n\n  rebrew binary imports mark --dry-run --json\n\nUse --target to select a configured project target.",
)
def mark(
    binary: Path | None = typer.Argument(None, help="Binary path (default: project target)"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without writing"),
    json_output: bool = typer.Option(False, "--json", help="Output results as JSON"),
    target: str | None = TargetOption,
) -> None:
    """Annotate detected import stubs through the owning writers."""
    inspect_imports(
        binary=binary, dry_run=dry_run, json_output=json_output, target=target, mark=True
    )


def main_entry() -> None:
    """Run the Typer CLI application."""
    from rebrew.cli import run_cli

    run_cli(app)


if __name__ == "__main__":
    main_entry()
